Repository mage-ai/mage-ai, pull requests merged in 2023-12, with the labels that each got.

#4104 [td] Add upstream block dependencies for dynamic child blocks at runtime
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
Labels: feature

#4107 [xy] Fix chromadb dependency.
  setup.py
Labels: bug

#4108 [xy] Fix chromadb in all package.
  setup.py
Labels: bug

#4110 [xy] Improve the interface for Chroma class.
  docs/integrations/databases/Chroma.mdx
  mage_ai/io/chroma.py
Labels: enhancement

#4111 [jk] Update local timezone project setting from header
  docs/development/project/local-timezone.mdx
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/PipelineDetail/Syncs/SyncRow/index.tsx
  mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/ServerTimeDropdown/index.style.tsx
  mage_ai/frontend/components/ServerTimeDropdown/index.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/settings/workspace/utils.ts
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/storage/constants.ts
  mage_ai/frontend/storage/serverTime.ts
Labels: bug, enhancement

#4116 [td] Fix runtime variables not showing when creating new trigger
  mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
  mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
  mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
Labels: bug

#4117 [td] Add global hooks route to server
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/server/server.py
Labels: enhancement

#4120 [xy] Fix executing conditional blocks with pipeline executor.
  mage_ai/data_preparation/executors/pipeline_executor.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#4121 [jk] Add docs for detaching blocks
  docs/guides/blocks/detach-blocks.mdx
  docs/mint.json
Labels: documentation

#4124 [sm] Doc bugfix in data-loading doc for DuckDB and Snowflake
  docs/design/data-loading.mdx
Labels: documentation

#4087 [dy] Optimize calculate metrics for integration pipelines
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/orchestration/metrics/pipeline_run.py
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#4048 Fixed Salesforce Source not running sync
  mage_integrations/mage_integrations/sources/salesforce/README.md
  mage_integrations/mage_integrations/sources/salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/.gitignore
  mage_integrations/mage_integrations/sources/salesforce/client/README.md
  mage_integrations/mage_integrations/sources/salesforce/client/spikes/test_threads.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/bulk.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/credentials.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/exceptions.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/rest.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/sync.py
  mage_integrations/mage_integrations/sources/salesforce/templates/config.json
Labels: bug, python, data integration

#4130 Fixed Salesforce Destination Upsert action
  mage_integrations/mage_integrations/destinations/salesforce/README.md
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/sinks.py
Labels: bug, python, data integration

#4128 [dy] Fix external cloud storage logs for k8s blocks
  mage_ai/data_preparation/logging/gcs_logger_manager.py
  mage_ai/data_preparation/logging/logger_manager.py
  mage_ai/data_preparation/logging/s3_logger_manager.py
  mage_ai/services/k8s/job_manager.py
Labels: bug

#4072 Added Dremio source to Data Integration Pipelines
  Dockerfile
  dev.Dockerfile
  docs/data-integrations/overview.mdx
  mage_ai/data_integrations/sources/constants.py
  mage_integrations/mage_integrations/connections/dremio/__init__.py
  mage_integrations/mage_integrations/sources/dremio/README.md
  mage_integrations/mage_integrations/sources/dremio/__init__.py
  mage_integrations/mage_integrations/sources/dremio/templates/config.json
  mage_integrations/mage_integrations/sources/dremio/utils.py
Labels: feature, python, data integration

#4125 Update setup.mdx
  docs/getting-started/setup.mdx
Labels: documentation

#4133 [jk] Manually run pipeline once in same trigger
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: feature

#4144 [td] Add resource parent in the input data for hooks
  mage_ai/api/operations/base.py
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/global_hooks/utils.py
  mage_ai/frontend/interfaces/GlobalHookType.ts
  mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/data_preparation/models/global_hooks/test_utils.py
Labels: enhancement

#4148 [jk] Update DownloadPolicy to allow downloading pipeline zip files
  mage_ai/api/presenters/DownloadPresenter.py
Labels: bug

#4109 [dy] Fix block runs page when there are a large number of block runs
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
Labels: enhancement

#4152 [td] Fix pagination
  mage_ai/api/resources/PipelineResource.py
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#4153 [td] Update terraform-apply-policy.mdx
  docs/production/deploying-to-cloud/aws/terraform-apply-policy.mdx
Labels: documentation

#4156 [td] Add tests and improve logs table
  mage_ai/api/resources/LogResource.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DependencyGraph/utils.ts
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: bug

#4157 [td] Dynamic blocks 2.0
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/__init__.py
  mage_ai/data_preparation/models/block/dynamic/dynamic_child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/models/block/dynamic/__init__.py
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_block_and_dynamic_child_block.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_blocks_and_upstream_dynamic_child_blocks.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_blocks_upstream_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple_level2.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple_levels.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_level1.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_level1_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_multiple_levels.json
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_child_block_factory.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_helpers.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_utils.py
  mage_ai/tests/data_preparation/models/block/test_utils.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: enhancement

#4159 [td] Add more tests for pipeline execute global hook
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: enhancement

#4160 [td] 0.9.49
  mage_ai/server/constants.py
  setup.py
Labels: feature

#4162 [td] Add tags to pipeline cache
  mage_ai/api/resources/PipelineResource.py
  mage_ai/cache/utils.py
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/tests/cache/example_pipeline.json
  mage_ai/tests/cache/pipeline_details_mapping_template
  mage_ai/tests/cache/test_pipeline_cache.py
Labels: bug

#4154 [dy] Update git settings when environment variables are set
  docs/production/data-sync/git-sync.mdx
  mage_ai/data_preparation/preferences.py
  mage_ai/settings/__init__.py
Labels: enhancement

#4170 [dy] Remove double quotes for postgres
  mage_ai/io/postgres.py
  mage_integrations/mage_integrations/destinations/sql/base.py
Labels: bug

#4173 [td] Fix silent errors from global hooks
  mage_ai/api/operations/base.py
  mage_ai/data_preparation/models/global_hooks/models.py
Labels: bug

#4174 [td] Add more user information in hooks kwargs
  mage_ai/api/operations/base.py
Labels: enhancement

#4175 [jk] Fix block sorting bug
  mage_ai/frontend/components/DependencyGraph/utils.ts
Labels: bug

#4177 [jk] Update custom block template
  mage_ai/data_preparation/templates/custom/python/default.jinja
Labels: enhancement

#4179 [td] Don’t save error details in the block run DB
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/global_hooks/models.py
Labels: bug

#4180 0.9.51
  mage_ai/server/constants.py
  setup.py
Labels: enhancement

#4149 [edw] Add custom 404 page
  mage_ai/frontend/pages/404.tsx
Labels: enhancement

#4183 [jk] Reset page after applying pipeline filters
  mage_ai/frontend/components/Logs/Toolbar/constants.ts
  mage_ai/frontend/components/Logs/Toolbar/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/utils/routing.ts
Labels: bug

#4185 [dy] Rewrite schedule queries
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/data_preparation/shared/__init__.py
  mage_ai/tests/data_preparation/shared/test_secrets.py
  mage_ai/tests/orchestration/db/models/__init__.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: enhancement

#4176 [dy] Add support for Bitbucket in version control app
  mage_ai/api/policies/GitBranchPolicy.py
  mage_ai/api/policies/GitCustomBranchPolicy.py
  mage_ai/api/policies/PullRequestPolicy.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/OauthResource.py
  mage_ai/api/resources/PullRequestResource.py
  mage_ai/authentication/oauth/constants.py
  mage_ai/authentication/providers/bitbucket.py
  mage_ai/authentication/providers/constants.py
  mage_ai/data_preparation/git/api.py
  mage_ai/data_preparation/git/clients/base.py
  mage_ai/data_preparation/git/clients/bitbucket.py
  mage_ai/data_preparation/git/clients/ghe.py
  mage_ai/data_preparation/git/clients/github.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/VersionControl/Commit/index.tsx
  mage_ai/frontend/components/VersionControl/Remote/Authentication.tsx
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/interfaces/OauthType.ts
  mage_ai/frontend/oracle/icons/custom/BitbucketWithText.tsx
  mage_ai/frontend/oracle/icons/index.tsx
Labels: feature

#4186 [td] Trigger and run pipelines across projects
  mage_ai/api/operations/base.py
  mage_ai/api/resources/BaseResource.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/ComputeServiceResource.py
  mage_ai/api/resources/DataProviderResource.py
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/api/resources/PipelineInteractionResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/api/resources/SparkApplicationResource.py
  mage_ai/api/resources/SparkExecutorResource.py
  mage_ai/api/resources/SparkStageResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/data_preparation/models/block/platform/utils.py
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/global_hooks/pipelines.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/triggers/api.py
  mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
  mage_ai/server/websocket_server.py
  mage_ai/settings/platform/__init__.py
  mage_ai/settings/platform/constants.py
  mage_ai/settings/platform/utils.py
  mage_ai/shared/models.py
  mage_ai/tests/api/endpoints/mixins.py
  mage_ai/tests/api/endpoints/test_files.py
  mage_ai/tests/api/endpoints/test_pipeline_runs.py
  mage_ai/tests/api/endpoints/test_pipeline_schedules.py
  mage_ai/tests/api/resources/test_pipeline_resource.py
  mage_ai/tests/data_preparation/models/block/platform/test_mixins.py
  mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/data_preparation/models/global_hooks/test_pipelines.py
  mage_ai/tests/data_preparation/models/global_hooks/test_utils.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
  mage_ai/tests/data_preparation/test_variable_manager.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
  mage_ai/tests/settings/platform/__init__.py
  mage_ai/tests/settings/platform/test_utils.py
  mage_ai/tests/settings/test_platform.py
  mage_ai/tests/shared/mixins.py
Labels: feature

#4191 [td] Don’t raise errors when adding dbt files
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/profiles.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_adapter.py
  mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py
Labels: enhancement

#4192 [td] Add models for custom design framework
  mage_ai/api/policies/CustomDesignPolicy.py
  mage_ai/api/presenters/CustomDesignPresenter.py
  mage_ai/api/resources/CustomDesignResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/data_preparation/models/project/models.py
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/presenters/design/__init__.py
  mage_ai/presenters/design/constants.py
  mage_ai/presenters/design/models.py
Labels: feature

#4193 [td] Add dbt cache
  mage_ai/api/operations/base.py
  mage_ai/api/policies/CacheItemPolicy.py
  mage_ai/api/presenters/CacheItemPresenter.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/CacheItemResource.py
  mage_ai/api/resources/FileContentResource.py
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/api/resources/WidgetResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/cache/base.py
  mage_ai/cache/constants.py
  mage_ai/cache/dbt/__init__.py
  mage_ai/cache/dbt/cache.py
  mage_ai/cache/dbt/constants.py
  mage_ai/cache/dbt/models.py
  mage_ai/cache/dbt/utils.py
  mage_ai/cache/models.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/data_preparation/models/file.py
  mage_ai/data_preparation/models/global_hooks/pipelines.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/server/server.py
  mage_ai/settings/platform/__init__.py
  mage_ai/settings/platform/utils.py
  mage_ai/settings/repo.py
  mage_ai/tests/api/endpoints/test_file_contents.py
  mage_ai/tests/api/endpoints/test_files.py
  mage_ai/tests/api/endpoints/test_folders.py
  mage_ai/tests/api/endpoints/test_pipelines.py
  mage_ai/tests/api/endpoints/test_statuses.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/models/block/platform/test_mixins.py
  mage_ai/tests/data_preparation/models/block/platform/test_utils.py
  mage_ai/tests/data_preparation/models/test_file.py
  mage_ai/tests/data_preparation/models/test_project.py
  mage_ai/tests/data_preparation/shared/test_secrets.py
  mage_ai/tests/data_preparation/test_repo_manager.py
  mage_ai/tests/settings/test_platform.py
  mage_ai/tests/shared/mixins.py
  mage_ai/tests/shared/test_path_fixer.py
Labels: feature

#4194 [td] Custom design for UI
  mage_ai/api/policies/CustomDesignPolicy.py
  mage_ai/api/presenters/CustomDesignPresenter.py
  mage_ai/api/resources/CustomDesignResource.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/ButtonItems.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/constants.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/components/shared/Header/index.style.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/CacheItemType.ts
  mage_ai/frontend/interfaces/ClientPageType.ts
  mage_ai/frontend/interfaces/CustomDesignType.ts
  mage_ai/frontend/interfaces/ProjectPlatformType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/test.tsx
  mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts
  mage_ai/presenters/design/models.py
  mage_ai/shared/hash.py
Labels: feature

#4169 [Enhancement] Add queue_subscription support for nats jetstream streaming source
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/templates/data_loaders/streaming/nats.yaml
  mage_ai/streaming/sources/nats_js.py
Labels: feature

#4196 [td] Don’t try to use file source if not exist
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/shared/path_fixer.py
Labels: bug

#4197 [td] Only fetch custom design if enabled
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/ButtonItems.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/presenters/design/models.py
  mage_ai/tests/api/endpoints/mocks/mock_dbt_configuration_options.json
  mage_ai/tests/api/endpoints/mocks/mock_dbt_configuration_options_project_platform.json
  mage_ai/tests/api/endpoints/mocks/mock_design.json
  mage_ai/tests/api/endpoints/mocks/mock_design_project_platform.json
  mage_ai/tests/api/endpoints/test_configuration_options.py
  mage_ai/tests/api/endpoints/test_custom_designs.py
  mage_ai/tests/settings/models/example_options_project_platform.json
  mage_ai/tests/settings/models/test_configuration_option.py
  mage_ai/tests/shared/mixins.py
  mage_ai/tests/shared/mocks/dbt/test_project/dbt_project.yml
  mage_ai/tests/shared/mocks/dbt/test_project/models/example/my_first_dbt_model.sql
  mage_ai/tests/shared/mocks/dbt/test_project/models/example/my_second_dbt_model.sql
  mage_ai/tests/shared/mocks/dbt/test_project/models/example/schema.yml
  mage_ai/tests/shared/mocks/dbt/test_project/profiles.yml
  mage_ai/tests/shared/mocks/mock_design.yaml
  mage_ai/tests/shared/mocks/mock_design2.yaml
Labels: enhancement

#4203 [td] Collapse or expand folders
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/FileBrowser/Folder.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/interfaces/FileType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/storage/localStorage.ts
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/events/constants.ts
  mage_ai/frontend/utils/events/index.ts
  mage_ai/frontend/utils/string.ts
  scripts/dev.sh
Labels: feature

#4208 [dy] Restrict opentelemetry package versions
  requirements.txt
  setup.py
Labels: bug

#4213 [dy] Add actions to GitBranchPolicy
  mage_ai/api/policies/GitBranchPolicy.py
  mage_ai/api/policies/GitCustomBranchPolicy.py
Labels: bug

#4219 [dy] Add default values for workspace creation
  docs/production/developing-in-the-cloud/workspaces/overview.mdx
  mage_ai/api/presenters/ProjectPresenter.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/manage/index.tsx
Labels: enhancement

#4221 [td] Improve folder performance
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/frontend/components/FileBrowser/Folder.tsx
  mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
  mage_ai/frontend/components/FileBrowser/NewFolder/index.tsx
  mage_ai/frontend/components/FileBrowser/constants.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/FileSelectorPopup/index.tsx
  mage_ai/frontend/interfaces/FileType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/files.ts
  mage_ai/tests/data_preparation/models/block/platform/test_mixins.py
  mage_ai/tests/data_preparation/models/test_block.py
Labels: enhancement

#4222 [td] Fix files page not opening files
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/Files/index.tsx
Labels: bug

#4223 [td] Fix file browser not refreshing
  mage_ai/api/parsers/ProjectParser.py
  mage_ai/api/policies/CustomDesignPolicy.py
  mage_ai/api/policies/ProjectPolicy.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/FileBrowser/Folder.tsx
  mage_ai/frontend/components/FileBrowser/NewFolder/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/utils/events/constants.ts
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/tests/api/endpoints/test_projects.py
Labels: enhancement

#4224 0.9.56
  mage_ai/server/constants.py
  setup.py
Labels: bug

#4225 [td] Fix dbt profiles interpolation
  mage_ai/cache/dbt/utils.py
  mage_ai/settings/models/configuration_option.py
Labels: bug

#4233 [td] Split pipeline scheduler and schedule models for project platform
  .flake8
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
  mage_ai/tests/api/endpoints/test_pipeline_runs.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
  mage_ai/tests/orchestration/test_pipeline_scheduler_project_platform.py
  mage_ai/tests/shared/mixins.py
Labels: bug

#4231 [td] Re-use file browser and editor in notebook
  mage_ai/data_preparation/models/file.py
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/useFileIcon.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/FileEditor/Controller.tsx
  mage_ai/frontend/components/FileEditor/Header/index.tsx
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/FileTabsScroller/index.style.tsx
  mage_ai/frontend/components/FileTabsScroller/index.tsx
  mage_ai/frontend/components/FileVersions/index.tsx
  mage_ai/frontend/components/Files/index.style.tsx
  mage_ai/frontend/components/Files/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/Files/utils.ts
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/VersionControl/index.tsx
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/pages/manage/files/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: enhancement

#4228 Added url protocol option to rabbitmq streaming
  docs/streaming/destinations/rabbitmq.mdx
  docs/streaming/sources/rabbitmq.mdx
  mage_ai/streaming/sinks/rabbitmq.py
  mage_ai/streaming/sources/rabbitmq.py
Labels: feature, python, streaming

#4237 [td] File browser bug bash
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/NewFile/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileSelectorPopup/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/Sidekick/constants.ts
  mage_ai/frontend/pages/manage/files/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4240 [td] Remove logs
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
Labels: bug

#4242 [td] Update test branch Dockerfile
  test_branch.Dockerfile
Labels: enhancement

#4243 [td] Fix bug when deleting block from file browser
  mage_ai/cache/dbt/cache.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
Labels: bug

#4245 0.9.57
  mage_ai/server/constants.py
  setup.py
Labels: bug

#4235 [jk] View or hide hidden files in file browser
  mage_ai/frontend/components/FileBrowser/FileHeaderMenu/index.style.ts
  mage_ai/frontend/components/FileBrowser/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/FileEditor/Header/index.tsx
  mage_ai/frontend/components/Files/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/constants.ts
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/interfaces/FileType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/storage/files.ts
Labels: enhancement

#4244 [td] Upgrade dbt to 1.7
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
  mage_ai/data_preparation/models/block/dbt/constants.py
  mage_ai/data_preparation/models/block/dbt/dbt_adapter.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_adapter.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_cli.py
  mage_integrations/requirements.txt
  requirements.txt
  setup.py
Labels: enhancement

#4200 [td] dbt v2 browser UI
  mage_ai/api/policies/CacheItemPolicy.py
  mage_ai/api/resources/CacheItemResource.py
  mage_ai/cache/dbt/utils.py
  mage_ai/cache/models.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  mage_ai/data_preparation/models/file.py
  mage_ai/frontend/components/AutocompleteDropdown/index.tsx
  mage_ai/frontend/components/BlockBrowser/BlockDetail/constants.tsx
  mage_ai/frontend/components/BlockBrowser/BlockDetail/index.tsx
  mage_ai/frontend/components/BlockBrowser/BlocksDetails/index.tsx
  mage_ai/frontend/components/BlockBrowser/BrowserHeader/index.style.tsx
  mage_ai/frontend/components/BlockBrowser/BrowserHeader/index.tsx
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/Header.tsx
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/constants.tsx
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/index.style.tsx
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/index.tsx
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/utils.tsx
  mage_ai/frontend/components/BlockBrowser/GroupsOfBlocks/index.tsx
  mage_ai/frontend/components/BlockBrowser/index.style.tsx
  mage_ai/frontend/components/BlockBrowser/index.tsx
  mage_ai/frontend/components/BlockBrowser/utils.ts
  mage_ai/frontend/components/CustomTemplates/BrowseTemplates/Navigation/BlockNavigation.tsx
  mage_ai/frontend/components/CustomTemplates/BrowseTemplates/constants.tsx
  mage_ai/frontend/components/CustomTemplates/BrowseTemplates/index.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/useFileIcon.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/CacheItemType.ts
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
  mage_ai/frontend/oracle/elements/Text/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/cache_items.json
  mage_ai/frontend/pages/test.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/models/file/useFiles.ts
Labels: feature

#4250 [td] Add custom code block tags
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Editor/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Header/index.style.tsx
  mage_ai/frontend/components/CodeBlockV2/Header/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Output/index.tsx
  mage_ai/frontend/components/CodeBlockV2/constants.ts
  mage_ai/frontend/components/CodeBlockV2/dbt/useCodeBlockProps.tsx
  mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/oracle/styles/colors/main.ts
  mage_ai/frontend/oracle/styles/themes/constants.ts
  mage_ai/frontend/oracle/styles/themes/dark.ts
Labels: enhancement

#4251 [td] Don’t import any dbt files until needed
  mage_ai/api/resources/ProjectResource.py
Labels: bug

#4252 [td] Disable sample query when using raw SQL
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/interfaces/ChartBlockType.ts
Labels: enhancement

#4253 0.9.58
  mage_ai/server/constants.py
  setup.py
Labels: feature

#4249 [td] Command center
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/api/utils/use.ts
  mage_ai/frontend/components/CommandCenter/ItemRow/constants.tsx
  mage_ai/frontend/components/CommandCenter/ItemRow/index.style.tsx
  mage_ai/frontend/components/CommandCenter/ItemRow/index.tsx
  mage_ai/frontend/components/CommandCenter/constants.ts
  mage_ai/frontend/components/CommandCenter/index.style.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/CommandCenter/mocks.ts
  mage_ai/frontend/components/CommandCenter/utils.ts
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/Files/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/interfaces/CommandCenterType.ts
  mage_ai/frontend/oracle/styles/themes/constants.ts
  mage_ai/frontend/oracle/styles/themes/dark.ts
  mage_ai/frontend/pages/files.tsx
  mage_ai/frontend/pages/test.tsx
  mage_ai/frontend/storage/CommandCenter/constants.ts
  mage_ai/frontend/storage/CommandCenter/utils.ts
  mage_ai/frontend/utils/elements.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/utils.ts
Labels: feature

#4255 [td] Fix dataframe validation
  mage_ai/io/mongodb.py
Labels: bug

#4263 [td] Fix add new button tooltips
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/KernelResource.py
  mage_ai/api/resources/LogResource.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/project.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Editor/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Header/index.tsx
  mage_ai/frontend/components/CodeBlockV2/Output/index.tsx
  mage_ai/frontend/components/CodeBlockV2/dbt/useCodeBlockProps.tsx
  mage_ai/frontend/components/DataTable/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/FileEditor/utils.ts
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/ButtonItems.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/StatusFooter/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/utils/files.ts
  mage_ai/frontend/utils/models/computeService/useComputeService.ts
  mage_ai/frontend/utils/models/kernel/useKernel.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
  mage_ai/settings/platform/__init__.py
  mage_ai/shared/path_fixer.py
  requirements.txt
  setup.py
Labels: bug

#4264 [td] Fix git bugs
  mage_ai/api/policies/GitBranchPolicy.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitFileResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/components/VersionControl/index.tsx
  mage_ai/frontend/context/Project/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
Labels: bug
