Repository mage-ai/mage-ai, pull requests merged in 2023-10, with the labels that each got.

#3634 [td] Reduce dynamic child block at any level
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/Logs/Detail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: enhancement

#3635 [td] Create Interaction class and other models
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/templates/repo/interactions/__init__.py
  mage_ai/data_preparation/templates/utils.py
  mage_ai/presenters/interactions/__init__.py
  mage_ai/presenters/interactions/constants.py
  mage_ai/presenters/interactions/models.py
  mage_ai/presenters/interactions/utils.py
Labels: feature

#3636 [td] Add API for interactions
  mage_ai/api/policies/InteractionPolicy.py
  mage_ai/api/presenters/InteractionPresenter.py
  mage_ai/api/resources/InteractionResource.py
  mage_ai/presenters/interactions/models.py
Labels: feature

#3637 [td] Created class to handle interactions for pipelines
  mage_ai/data_preparation/models/pipelines/constants.py
  mage_ai/data_preparation/models/pipelines/interactions.py
  mage_ai/presenters/interactions/models.py
Labels: feature

#3638 [td] Add CRUD API endpoint for interactions in a pipeline
  mage_ai/api/policies/PipelineInteractionPolicy.py
  mage_ai/api/presenters/PipelineInteractionPresenter.py
  mage_ai/api/resources/PipelineInteractionResource.py
Labels: feature

#3641 [xy] Fix memory leak in data integration pipelines.
  mage_integrations/mage_integrations/destinations/oracledb/__init__.py
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/destinations/redshift/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/sql/base.py
  mage_integrations/mage_integrations/sources/oracledb/__init__.py
  mage_integrations/mage_integrations/sources/postgresql/__init__.py
Labels: bug

#3609 [dy] Initialize db connection session
  mage_ai/server/websocket_server.py
Labels: bug

#3643 Apache Kafka - SASL_PLAINTEXT
  mage_ai/streaming/sources/kafka.py
Labels: enhancement

#3644 [mp] dbt hotfix
  docs/guides/dbt/developing-dbt-in-mage.mdx
Labels: documentation

#3625 [dy] Update search_path command
  mage_ai/orchestration/db/__init__.py
Labels: enhancement

#3647 [xy] Fix auto generating mage_sources.yml for dbt upstream blocks
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/pipeline.py
Labels: bug

#3648 [jk] Pipelines list fixes
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#3649 [xy] Support Kafka SASL_SSL SCRAM-SHA-512 authentication.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/streaming/sinks/kafka.py
  mage_ai/streaming/sources/kafka.py
Labels: enhancement

#3640 [td] Block interactions application
  mage_ai/api/policies/InteractionPolicy.py
  mage_ai/api/policies/PipelineInteractionPolicy.py
  mage_ai/api/resources/InteractionResource.py
  mage_ai/api/resources/PipelineInteractionResource.py
  mage_ai/data_preparation/models/pipelines/interactions.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItem.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItemWithDrag.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/RowDivider.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/components/Interactions/index.style.tsx
  mage_ai/frontend/components/PipelineInteractions/PermissionRow/index.tsx
  mage_ai/frontend/components/PipelineInteractions/index.style.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/components/Sidekick/Header.tsx
  mage_ai/frontend/components/Sidekick/Navigation/constants.ts
  mage_ai/frontend/components/Sidekick/constants.ts
  mage_ai/frontend/interfaces/InteractionType.ts
  mage_ai/frontend/interfaces/PipelineInteractionType.ts
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/interfaces/UserType.ts
  mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
  mage_ai/frontend/oracle/components/Accordion/index.tsx
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/oracle/styles/themes/dark.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/test.tsx
  mage_ai/frontend/utils/array.ts
  mage_ai/presenters/interactions/models.py
Labels: feature

#3652 [td] Add interactions app to sidekick
  mage_ai/data_preparation/models/pipelines/interactions.py
  mage_ai/frontend/components/Breadcrumbs/index.tsx
  mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/components/PipelineInteractions/index.style.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/components/PipelineLayout/index.tsx
  mage_ai/frontend/components/Sidekick/Header.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: feature

#3646 [dy] Throw exception if a variable is not defined in jinja for sql blocks
  mage_ai/data_preparation/models/block/sql/druid.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
Labels: bug

#3645 [dy] Add support for dbt-synapse
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/constants.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  requirements.txt
  setup.py
Labels: feature

#3658 [jk] Storybook cleanup
  mage_ai/frontend/oracle/components/Table/SimpleDataTable.tsx
  mage_ai/frontend/stories/components/charts/BarGraphHorizontal.stories.tsx
  mage_ai/frontend/stories/components/charts/BoxPlotHorizontal.stories.tsx
  mage_ai/frontend/stories/components/charts/Histogram.stories.tsx
  mage_ai/frontend/stories/components/charts/PieChart.stories.tsx
  mage_ai/frontend/stories/oracle/components/Accordion.stories.tsx
  mage_ai/frontend/stories/oracle/components/Badge.stories.tsx
  mage_ai/frontend/stories/oracle/components/Breadcrumbs.stories.tsx
  mage_ai/frontend/stories/oracle/components/Chip.stories.tsx
  mage_ai/frontend/stories/oracle/components/Menu.stories.tsx
  mage_ai/frontend/stories/oracle/components/Panel.stories.tsx
  mage_ai/frontend/stories/oracle/components/ProgressBar.stories.tsx
  mage_ai/frontend/stories/oracle/components/RowDataTable.stories.tsx
  mage_ai/frontend/stories/oracle/components/SimpleDataTable.stories.tsx
  mage_ai/frontend/stories/oracle/components/Spinner.stories.tsx
  mage_ai/frontend/stories/oracle/components/Tabs.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Button/Button.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Button/ButtonGroup.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Checkbox.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Inputs/Select.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Inputs/TextInput.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Link.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Text.stories.tsx
Labels: enhancement

#3657 [dy] Add support for dbt-synapse v2
  Dockerfile
  dev.Dockerfile
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/constants.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
Labels: feature

#3660 [td] Don’t show empty images
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
Labels: bug

#3653 [td] Show the interactions rendered in the code block
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/constants.ts
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/components/PipelineInteractions/index.style.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/components/Sidekick/Header.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
  mage_ai/frontend/oracle/styles/themes/dark.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/server/utils/output_display.py
Labels: feature

#3662 [td] Use variables from interactions when running block
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItem.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/server/utils/output_display.py
  mage_ai/server/websocket_server.py
Labels: feature

#3663 [td] Improve helper hints for interactions
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/LayoutItem.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/components/PipelineInteractions/PermissionRow/index.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/interfaces/InteractionType.ts
  mage_ai/presenters/interactions/constants.py
  mage_ai/presenters/interactions/models.py
Labels: enhancement

#3664 [td] Fix API policies for pipeline interactions
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/presenters/PipelineInteractionPresenter.py
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
Labels: bug

#3665 [td] Create triggers page with interactions
  mage_ai/api/policies/PipelineInteractionPolicy.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/resources/PipelineInteractionResource.py
  mage_ai/data_preparation/models/pipelines/interactions.py
  mage_ai/frontend/components/Dashboard/Subheader.tsx
  mage_ai/frontend/components/Dashboard/index.style.tsx
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/PipelineDetailPage/index.tsx
  mage_ai/frontend/components/Triggers/Edit/TriggerInteractions.tsx
  mage_ai/frontend/components/Triggers/Edit/constants.ts
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: feature

#3667 [td] Update API policy to use async and API base operation and add API parsers
  mage_ai/api/constants.py
  mage_ai/api/oauth_scope.py
  mage_ai/api/operations/base.py
  mage_ai/api/operations/constants.py
  mage_ai/api/parsers/BaseParser.py
  mage_ai/api/parsers/PipelineScheduleParser.py
  mage_ai/api/parsers/__init__.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/policies/utils.py
  mage_ai/api/presenters/BasePresenter.py
  mage_ai/api/resources/PipelineInteractionResource.py
  mage_ai/data_preparation/models/pipelines/interactions.py
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
Labels: enhancement

#3669 [td] Create page models to help client determine what components to show
  mage_ai/presenters/pages/__init__.py
  mage_ai/presenters/pages/constants.py
  mage_ai/presenters/pages/models/__init__.py
  mage_ai/presenters/pages/models/base.py
  mage_ai/presenters/pages/models/pipeline_schedules.py
Labels: feature

#3670 Propagate tags of ECS task definition to task executors
  mage_ai/services/aws/ecs/config.py
Labels: enhancement

#3672 [jk] Also search pipeline run event_variables
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
Labels: enhancement

#3673 [td] Add await to authorize in base operation
  mage_ai/api/operations/base.py
Labels: bug

#3668 Fixed typo and simplified text for empty dashboard
  mage_ai/frontend/components/BlockLayout/index.tsx
Labels: enhancement

#3675 [td] Added query params to client pages API
  mage_ai/api/policies/ClientPagePolicy.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/presenters/ClientPagePresenter.py
  mage_ai/api/resources/ClientPageResource.py
  mage_ai/presenters/pages/loaders/__init__.py
  mage_ai/presenters/pages/loaders/base.py
  mage_ai/presenters/pages/loaders/pipeline_schedules.py
  mage_ai/presenters/pages/loaders/pipelines.py
  mage_ai/presenters/pages/loaders/utils.py
  mage_ai/presenters/pages/models/base.py
  mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
  mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
Labels: enhancement

#3678 [jk] YAML block language display
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
Labels: bug

#3679 [td] Update page models
  mage_ai/api/policies/ClientPagePolicy.py
  mage_ai/api/presenters/BasePresenter.py
  mage_ai/api/presenters/ClientPagePresenter.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/interfaces/ClientPageType.ts
  mage_ai/frontend/interfaces/PageComponentType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/presenters/pages/models/base.py
  mage_ai/presenters/pages/models/client_pages/pipeline_schedules.py
  mage_ai/presenters/pages/models/constants.py
  mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
  mage_ai/shared/hash.py
Labels: enhancement

#3682 [td] Add new columns to Roles and Permissions table
  mage_ai/orchestration/db/migrations/README.md
  mage_ai/orchestration/db/migrations/versions/526c4523d5d5_add_user_id_to_roles_and_more_entity_.py
  mage_ai/orchestration/db/models/oauth.py
Labels: enhancement

#3680 [tc] Update overview.mdx
  docs/streaming/overview.mdx
Labels: documentation

#3684 [td] Create role permission table
  mage_ai/orchestration/db/migrations/versions/9f3b46404196_create_rolepermission_table.py
  mage_ai/orchestration/db/models/oauth.py
Labels: enhancement

#3686 [td] Add role permissions API
  mage_ai/api/policies/RolePermissionPolicy.py
  mage_ai/api/presenters/PermissionPresenter.py
  mage_ai/api/presenters/RolePermissionPresenter.py
  mage_ai/api/presenters/RolePresenter.py
  mage_ai/api/resources/RolePermissionResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/orchestration/db/migrations/README.md
  mage_ai/orchestration/db/models/oauth.py
Labels: enhancement

#3677 [dy] Add None for block check
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#3630 [dy] Raise exception if there are serialization errors
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/storage/base_storage.py
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/storage/s3_storage.py
  mage_ai/data_preparation/variable_manager.py
Labels: bug

#3690 Fixed twitter ads imports
  mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/__init__.py
  mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/discover.py
  mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/schema.py
  mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/streams.py
  mage_integrations/mage_integrations/sources/twitter_ads/tap_twitter_ads/sync.py
Labels: bug, python, data integration

#3607 Usage of mage secrets as a secondary to when there are no aws key or …
  docs/production/deploying-to-cloud/secrets/AWS.mdx
  mage_ai/cluster_manager/aws/ecs_task_manager.py
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/services/aws/__init__.py
  mage_ai/services/aws/ecs/ecs.py
  mage_ai/services/aws/emr/emr.py
  mage_ai/services/aws/events/events.py
  mage_ai/services/aws/secrets_manager/secrets_manager.py
Labels: enhancement

#3693 [dy] Fix git config preserve when .preferences.yaml file doesn't exist
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/tests/data_preparation/sync/__init__.py
  mage_ai/tests/data_preparation/sync/test_git_sync.py
Labels: bug

#3694 [td] Allow writing of interaction UUID on create
  mage_ai/api/policies/InteractionPolicy.py
Labels: bug

#3697 [xy] Speed up io mssql export method
  docs/integrations/databases/MicrosoftSQLServer.mdx
  mage_ai/io/druid.py
  mage_ai/io/mssql.py
  mage_ai/io/postgres.py
  mage_ai/io/sql.py
Labels: enhancement

#3687 [td] Add optional requirement for requiring user permissions when authenticating API endpoints
  docker-compose.yml
  mage_ai/api/constants.py
  mage_ai/api/mixins/result_set.py
  mage_ai/api/operations/base.py
  mage_ai/api/operations/constants.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/mixins/__init__.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/api/resources/BaseResource.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/Resource.py
  mage_ai/api/result_set.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/settings/__init__.py
  mage_ai/tests/api/operations/test_operations.py
  mage_ai/usage_statistics/logger.py
  scripts/dev.sh
Labels: feature

#3700 [td] Only create 4 default permissions
  mage_ai/orchestration/db/models/oauth.py
Labels: bug

#3705 [xy] Support UPDATE command in raw sql command.
  docs/guides/blocks/sql-blocks.mdx
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py
Labels: enhancement

#3706 [td] Parse out unauthorized variable keys from payload if pipeline has interactions
  mage_ai/api/errors.py
  mage_ai/api/parsers/BaseParser.py
  mage_ai/api/parsers/PipelineScheduleParser.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/policies/utils.py
  mage_ai/data_preparation/models/pipelines/interactions.py
Labels: enhancement

#3707 [td] Bug bash interactions
  .pre-commit-config.yaml
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/ErrorPopup/index.tsx
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
  mage_ai/frontend/components/Interactions/InteractionLayoutContainer/index.tsx
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/interfaces/InteractionType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/utils/models/interaction.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/presenters/interactions/constants.py
  mage_ai/tests/api/operations/test_pipeline_schedules.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: bug

#3709 [xy] Fix MySQL source int comparison.
  mage_integrations/mage_integrations/sources/mysql/__init__.py
Labels: bug

#3710 [td] Update session and status resource to allow with permissions
  mage_ai/api/policies/SessionPolicy.py
  mage_ai/api/policies/StatusPolicy.py
  mage_ai/api/policies/mixins/user_permissions.py
Labels: enhancement

#3711 [td] Update users list page
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/frontend/components/VerticalSectionLinks/index.tsx
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/interfaces/UserType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/settings/workspace/users/index.tsx
Labels: enhancement

#3712 [td] User edit and detail view
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/frontend/components/settings/Dashboard/index.tsx
  mage_ai/frontend/components/shared/index.style.tsx
  mage_ai/frontend/components/users/edit/Form/index.tsx
  mage_ai/frontend/interfaces/UserType.ts
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
  mage_ai/frontend/pages/settings/workspace/users/index.tsx
  mage_ai/orchestration/db/models/oauth.py
Labels: enhancement

#3713 [xy] Allow customizing batch fetch limit for data integration pipeline.
  mage_ai/data_integrations/utils/config.py
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/integration/__init__.py
  mage_integrations/mage_integrations/sources/constants.py
  mage_integrations/mage_integrations/sources/sql/base.py
  mage_integrations/mage_integrations/tests/sources/sql/test_base.py
Labels: enhancement

#3714 [td] Add roles list page
  mage_ai/api/presenters/RolePresenter.py
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/frontend/api/utils/use.ts
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/components/settings/Dashboard/index.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/RoleType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
  mage_ai/frontend/pages/settings/workspace/users/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/hash.ts
Labels: feature

#3715 [td] Roles detail page
  mage_ai/api/policies/PermissionPolicy.py
  mage_ai/api/presenters/PermissionPresenter.py
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/interfaces/PermissionType.ts
  mage_ai/frontend/interfaces/RoleType.ts
  mage_ai/frontend/pages/settings/workspace/roles/[...slug].tsx
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
  mage_ai/frontend/utils/models/user.ts
Labels: feature

#3717 [td] Permissions list page
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/interfaces/PermissionType.ts
  mage_ai/frontend/pages/settings/workspace/permissions/index.tsx
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/frontend/utils/models/permission.ts
Labels: feature

#3720 [td] Add permissions and users to role
  mage_ai/api/policies/RolePermissionPolicy.py
  mage_ai/api/policies/RolePolicy.py
  mage_ai/api/presenters/RolePresenter.py
  mage_ai/api/presenters/StatusPresenter.py
  mage_ai/api/resources/DatabaseResource.py
  mage_ai/api/resources/PermissionResource.py
  mage_ai/api/resources/RolePermissionResource.py
  mage_ai/api/resources/RoleResource.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/components/settings/Dashboard/index.tsx
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/pages/settings/workspace/roles/[...slug].tsx
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/frontend/utils/session.ts
Labels: feature

#3704 [dy] Suppress secret logs for aws secrets
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/services/aws/__init__.py
Labels: bug

#3719 Added Opensearch Destination
  mage_ai/data_integrations/destinations/constants.py
  mage_integrations/mage_integrations/destinations/opensearch/README.md
  mage_integrations/mage_integrations/destinations/opensearch/__init__.py
  mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/__init__.py
  mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/common.py
  mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/sinks.py
  mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/target.py
  mage_integrations/mage_integrations/destinations/opensearch/templates/config.json
  mage_integrations/requirements.txt
Labels: python, data integration

#3723 [jk] Update Backfill policy
  mage_ai/api/policies/BackfillPolicy.py
Labels: bug

#3708 [dy] Add activity to status endpoint when requested
  mage_ai/api/middleware.py
  mage_ai/api/policies/StatusPolicy.py
  mage_ai/api/presenters/StatusPresenter.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/server/api/base.py
  mage_ai/server/api/v1.py
  mage_ai/server/server.py
Labels: python

#3724 [td] Fix block tests not getting output
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/presenters/pages/loaders/pipeline_schedules.py
Labels: bug

#3725 [xy] Support using custom spark session.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/templates/repo/metadata.yaml
  mage_ai/services/spark/config.py
  mage_ai/services/spark/spark.py
Labels: enhancement

#3726 [td] Remove the requirement for schedule type
  mage_ai/api/resources/RoleResource.py
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#3729 [jk] Check for empty column headers
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/DataTable/index.tsx
Labels: bug

#3731 [td] Fix permissions list
  mage_ai/api/operations/base.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/frontend/components/Permissions/PermissionDetail.tsx
  mage_ai/frontend/pages/settings/workspace/permissions/index.tsx
Labels: bug

#3733 [td] 0.9.34
  mage_ai/api/mixins/__init__.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/server/constants.py
  setup.py
Labels: bug

#3734 [td] Make it less easy to uncheck a role, permission, etc in a table
  mage_ai/frontend/components/Permissions/PermissionDetail.tsx
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/users/UserDetail.tsx
Labels: enhancement

#3735 [td] Add permissions with special conditions
  mage_ai/api/policies/PermissionPolicy.py
  mage_ai/api/policies/UserPolicy.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/api/presenters/PermissionPresenter.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/frontend/components/Permissions/PermissionDetail.tsx
  mage_ai/frontend/interfaces/PermissionType.ts
  mage_ai/orchestration/db/models/oauth.py
Labels: enhancement

#3674 [dy] Update api trigger request
  mage_ai/api/middleware.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/orchestration/triggers/utils.py
  mage_ai/server/api/triggers.py
  mage_ai/server/server.py
  mage_ai/shared/requests.py
Labels: security

#3740 Fixed imports and removed flake8 check for taps/targets
  .pre-commit-config.yaml
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/utils/validation.py
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/__init__.py
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/discover.py
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/sync.py
  mage_integrations/mage_integrations/sources/linkedin_ads/tap_linkedin_ads/__init__.py
  mage_integrations/mage_integrations/sources/linkedin_ads/tap_linkedin_ads/discover.py
  mage_integrations/mage_integrations/sources/linkedin_ads/tap_linkedin_ads/sync.py
  mage_integrations/mage_integrations/sources/outreach/tap_outreach/__init__.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/cli.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/activity_types.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/currencies.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/deal_products.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/dealflow.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/filters.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/notes.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/pipelines.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/__init__.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/__init__.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/activities.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/deals.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/notes.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/organizations.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/persons.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/dynamic_typing/products.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/files.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/recents/users.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/streams/stages.py
  mage_integrations/mage_integrations/sources/pipedrive/tap_pipedrive/tap.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/__init__.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/cleaners.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/discover.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/postmark.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/sync.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/tap.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/client.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/discover.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/singer_encodings/csv_handler.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/singer_encodings/json_schema.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/sync.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/tap.py
Labels: bug, python, data integration

#3737 [td] Seed permissions based off policies
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/policies/SeedPolicy.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/api/presenters/BasePresenter.py
  mage_ai/api/presenters/SeedPresenter.py
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/api/resources/RoleResource.py
  mage_ai/api/resources/SeedResource.py
  mage_ai/api/resources/UserResource.py
  mage_ai/api/resources/shared/collective_loaders.py
  mage_ai/api/utils.py
  mage_ai/authentication/permissions/seed.py
  mage_ai/authentication/permissions/seed_script.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/pages/settings/workspace/permissions/index.tsx
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/settings/__init__.py
Labels: enhancement

#3743 [td] Fix fetching roles new for User
  mage_ai/orchestration/db/models/oauth.py
Labels: bug

#3745 [td] Speed up API
  mage_ai/api/mixins/result_set.py
  mage_ai/api/operations/base.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/api/presenters/UserPresenter.py
  mage_ai/api/resources/UserResource.py
  mage_ai/authentication/oauth/utils.py
  mage_ai/frontend/components/users/UserDetail.tsx
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/cache.py
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/server/server.py
Labels: enhancement

#3746 [td] Test API base resource classes
  mage_ai/api/resources/BaseResource.py
  mage_ai/api/resources/DatabaseResource.py
  mage_ai/tests/api/resources/__init__.py
  mage_ai/tests/api/resources/test_base_resource.py
  mage_ai/tests/api/resources/test_database_resource.py
  mage_ai/tests/api/resources/test_generic_resource.py
  mage_ai/tests/api/resources/test_resource.py
Labels: enhancement

#3747 [td] Unit test BasePresenter
  .pre-commit-config.yaml
  mage_ai/tests/api/mixins.py
  mage_ai/tests/api/presenters/__init__.py
  mage_ai/tests/api/presenters/test_base_presenter.py
  mage_ai/tests/api/presenters/test_mixins.py
  mage_ai/tests/api/resources/test_database_resource.py
  mage_ai/tests/api/utils.py
Labels: enhancement

#3691 [mp] Update ETL demo and remove Postgres requirement
  docs/guides/load-api-data.mdx
Labels: documentation

#3659 [jk] Project-wide pipeline run filters
  mage_ai/api/policies/PipelineRunPolicy.py
  mage_ai/api/presenters/PipelineRunPresenter.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/cache/tag.py
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/interfaces/PipelineRunType.ts
  mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
  mage_ai/frontend/pages/pipeline-runs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/utils/routing.ts
  mage_ai/orchestration/db/models/schedules.py
Labels: enhancement

#3749 [xy] Fix extracting update statement from sql.
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py
Labels: bug

#3750 [td] Add unit tests for BasePolicy
  mage_ai/api/policies/BasePolicy.py
  mage_ai/tests/api/policies/__init__.py
  mage_ai/tests/api/policies/test_base_policy.py
Labels: enhancement

#3696 [jk] Cron expression syntax err display for triggers in code
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: enhancement

#3752 [td] Test BasePolicy with permissions
  mage_ai/api/policies/BasePolicy.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/tests/api/policies/permissions/__init__.py
  mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py
Labels: enhancement

#3753 [td] Add more test cases for permissions
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py
Labels: enhancement

#3757 [xy] Update docs for Spark pipelines and data integration sources
  docs/integrations/spark-pyspark.mdx
  mage_integrations/mage_integrations/sources/mssql/README.md
  mage_integrations/mage_integrations/sources/mysql/README.md
  mage_integrations/mage_integrations/sources/oracledb/README.md
  mage_integrations/mage_integrations/sources/postgresql/README.md
  mage_integrations/mage_integrations/sources/redshift/README.md
  mage_integrations/mage_integrations/sources/snowflake/README.md
Labels: documentation

#3721 [dy] Update workspace resource for auto termination
  mage_ai/api/policies/WorkspacePolicy.py
  mage_ai/api/presenters/WorkspacePresenter.py
  mage_ai/api/resources/ClusterResource.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/cluster_manager/config.py
  mage_ai/cluster_manager/constants.py
  mage_ai/cluster_manager/errors.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/cluster_manager/manage.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/frontend/pages/manage/index.tsx
  mage_ai/server/api/clusters.py
  mage_ai/server/server.py
Labels: feature

#3759 [jk] Flyout menu overflow
  mage_ai/frontend/components/CodeEditor/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
Labels: enhancement

#3758 [td] Add tests for base operation
  docs/contributing/backend/testing/overview.mdx
  docs/mint.json
  mage_ai/api/operations/base.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/views.py
  mage_ai/tests/api/mixins.py
  mage_ai/tests/api/operations/base/__init__.py
  mage_ai/tests/api/operations/base/mixins.py
  mage_ai/tests/api/operations/base/test_base.py
  mage_ai/tests/api/operations/base/test_base_with_user_authentication.py
  mage_ai/tests/api/operations/base/test_base_with_user_permissions.py
  mage_ai/tests/api/operations/test_operations.py
  mage_ai/tests/api/operations/test_users.py
  mage_ai/tests/api/policies/test_base_policy.py
  mage_ai/tests/api/presenters/test_base_presenter.py
Labels: enhancement

#3763 [td] Test API views
  mage_ai/api/views.py
  mage_ai/tests/api/test_views.py
Labels: enhancement

#3764 [td] Test specific API endpoints
  mage_ai/api/policies/PermissionPolicy.py
  mage_ai/api/policies/UserPolicy.py
  mage_ai/api/resources/BlockRunResource.py
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/shared/strings.py
  mage_ai/tests/api/endpoints/__init__.py
  mage_ai/tests/api/endpoints/mixins.py
  mage_ai/tests/api/endpoints/test_block_outputs.py
  mage_ai/tests/api/endpoints/test_block_runs.py
  mage_ai/tests/api/endpoints/test_blocks.py
  mage_ai/tests/api/endpoints/test_file_contents.py
  mage_ai/tests/api/endpoints/test_files.py
  mage_ai/tests/api/endpoints/test_folders.py
  mage_ai/tests/api/endpoints/test_kernels.py
  mage_ai/tests/api/endpoints/test_logs.py
  mage_ai/tests/api/endpoints/test_monitor_stats.py
  mage_ai/tests/api/endpoints/test_permissions.py
  mage_ai/tests/api/endpoints/test_pipeline_runs.py
  mage_ai/tests/api/endpoints/test_pipelines.py
  mage_ai/tests/api/mixins.py
  mage_ai/tests/api/operations/test_sessions.py
  mage_ai/tests/shared/test_io.py
Labels: enhancement

#3765 [td] Test more API endpoints
  mage_ai/api/operations/base.py
  mage_ai/api/policies/RolePolicy.py
  mage_ai/api/presenters/PipelineTriggerPresenter.py
  mage_ai/api/resources/DatabaseResource.py
  mage_ai/api/resources/PermissionResource.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/api/resources/RoleResource.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/tests/api/endpoints/mixins.py
  mage_ai/tests/api/endpoints/test_permissions.py
  mage_ai/tests/api/endpoints/test_pipeline_schedules.py
  mage_ai/tests/api/endpoints/test_pipeline_triggers.py
  mage_ai/tests/api/endpoints/test_projects.py
  mage_ai/tests/api/endpoints/test_role_permissions.py
  mage_ai/tests/api/endpoints/test_roles.py
  mage_ai/tests/api/endpoints/test_schedulers.py
  mage_ai/tests/api/endpoints/test_secrets.py
  mage_ai/tests/api/endpoints/test_statuses.py
  mage_ai/tests/api/endpoints/test_user_roles.py
  mage_ai/tests/api/endpoints/test_variables.py
  mage_ai/tests/base_test.py
Labels: enhancement

#3766 [td] Validate permissions for specific entity IDs
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/frontend/components/Permissions/PermissionDetail.tsx
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/users/UserDetail.tsx
  mage_ai/tests/api/endpoints/test_variables.py
  mage_ai/tests/api/policies/permissions/mixins.py
  mage_ai/tests/api/policies/permissions/test_base_policy_with_permissions.py
  mage_ai/tests/api/policies/permissions/test_permissions_with_entity_id.py
Labels: enhancement

#3767 [td] Spark UI API endpoints
  mage_ai/api/policies/SparkApplicationPolicy.py
  mage_ai/api/presenters/SparkApplicationPresenter.py
  mage_ai/api/resources/SparkApplicationResource.py
  mage_ai/services/spark/api/__init__.py
  mage_ai/services/spark/api/base.py
  mage_ai/services/spark/api/local.py
  mage_ai/services/spark/api/test.py
  mage_ai/services/spark/models.py
Labels: feature

#3768 [td] Add API for spark jobs
  mage_ai/api/policies/SparkJobPolicy.py
  mage_ai/api/policies/SparkStageAttemptPolicy.py
  mage_ai/api/policies/SparkStagePolicy.py
  mage_ai/api/presenters/SparkApplicationPresenter.py
  mage_ai/api/presenters/SparkJobPresenter.py
  mage_ai/api/presenters/SparkStageAttemptPresenter.py
  mage_ai/api/presenters/SparkStagePresenter.py
  mage_ai/api/resources/SparkApplicationResource.py
  mage_ai/api/resources/SparkJobResource.py
  mage_ai/api/resources/SparkStageAttemptResource.py
  mage_ai/api/resources/SparkStageResource.py
  mage_ai/services/spark/api/base.py
  mage_ai/services/spark/api/local.py
  mage_ai/services/spark/api/test.py
  mage_ai/services/spark/models.py
  mage_ai/services/spark/models/__init__.py
  mage_ai/services/spark/models/applications.py
  mage_ai/services/spark/models/base.py
  mage_ai/services/spark/models/jobs.py
  mage_ai/services/spark/models/stages.py
Labels: enhancement

#3761 [xy] Convert schema name to uppercase when disable_double_quotes.
  Dockerfile
  dev.Dockerfile
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/bigquery/templates/config.json
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
  mage_integrations/mage_integrations/sources/bigquery/README.md
Labels: bug

#3770 [td] Support multiple conditions for the same action or attribute
  dev.Dockerfile
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/StatusPolicy.py
  mage_ai/api/policies/mixins/user_permissions.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/utils/models/project.ts
  mage_ai/tests/api/mixins.py
  mage_ai/tests/api/operations/test_base.py
  mage_ai/tests/api/policies/test_base_policy.py
  mage_ai/tests/api/resources/test_database_resource.py
Labels: enhancement

#3771 [td] Compute management connection
  mage_ai/api/presenters/ProjectPresenter.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/templates/repo/metadata.yaml
  mage_ai/frontend/components/ComputeManagement/ConnectionSettings.tsx
  mage_ai/frontend/components/ComputeManagement/constants.tsx
  mage_ai/frontend/components/ComputeManagement/index.style.tsx
  mage_ai/frontend/components/ComputeManagement/index.tsx
  mage_ai/frontend/components/ComputeManagement/utils.ts
  mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
  mage_ai/frontend/components/shared/index.style.tsx
  mage_ai/frontend/components/users/UserDetail.tsx
  mage_ai/frontend/context/Project/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/oracle/icons/custom/AmazonWebServicesEMR.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/compute/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: feature

#3716 MongoDB CDC is added
  mage_ai/data_preparation/templates/data_loaders/streaming/mongodb.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/interfaces/DataSourceType.ts
  mage_ai/streaming/constants.py
  mage_ai/streaming/sources/mongodb.py
  mage_ai/streaming/sources/source_factory.py
  mage_ai/tests/streaming/sources/test_mongodb.py
  scripts/init.sh
Labels: feature

#3773 [xy] Fix loading data integration sources.
  mage_ai/data_preparation/templates/data_integrations/utils.py
  mage_ai/shared/strings.py
  mage_integrations/mage_integrations/sources/twitter_ads/__init__.py
Labels: bug

#3774 [xy] Support upsert in MongoDB streaming sink.
  docs/streaming/destinations/mongodb.mdx
  mage_ai/data_preparation/templates/data_loaders/streaming/mongodb.yaml
  mage_ai/streaming/sinks/base.py
  mage_ai/streaming/sinks/mongodb.py
Labels: enhancement

#3772 [td] Resources view for compute management
  mage_ai/frontend/components/ComputeManagement/ConnectionSettings.tsx
  mage_ai/frontend/components/ComputeManagement/ResourceManagement.tsx
  mage_ai/frontend/components/ComputeManagement/index.tsx
  mage_ai/frontend/components/ComputeManagement/shared/KeyValueConfigurationSection.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
Labels: feature

#3776 [td] Document and fix bugs for data integration blocks
  docs/data-integrations/batch-pipelines.mdx
  docs/mint.json
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/CodeBlock/BlockExtras/index.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/Credentials/InputsTable.tsx
  mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamOverviewEditor.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamSettingsEditorTable.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/index.style.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddonBlocks/AddonBlock.tsx
  mage_ai/frontend/components/PipelineDetail/Extensions/constants.ts
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/utils/models/block.ts
Labels: bug, documentation, data integration

#3777 [td] Add missing docs
  docs/data-integrations/batch-pipelines.mdx
Labels: documentation

#3779 [td] Add docs and fixes for interactions
  docs/data-integrations/batch-pipelines.mdx
  docs/interactions/overview.mdx
  docs/mint.json
  mage_ai/frontend/components/Interactions/InteractionDisplay.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/oracle/components/Accordion/AccordionPanel.tsx
  mage_ai/frontend/oracle/components/Accordion/index.tsx
Labels: documentation

#3780 [td] Add docs for permissions and show avatar
  docs/authentication/permissions/overview.mdx
  docs/authentication/permissions/permissions.mdx
  docs/authentication/permissions/roles.mdx
  docs/interactions/overview.mdx
  docs/mint.json
  mage_ai/api/policies/SessionPolicy.py
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/Permissions/PermissionDetail.tsx
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/settings/Dashboard/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
Labels: documentation

#3751 [dy] Add auto termination frontend
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/components/workspaces/Dashboard/index.tsx
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/manage/index.tsx
  mage_ai/frontend/yarn.lock
Labels: enhancement

#3760 [dy] Add dbt-dremio dependency
  docs/dbt/overview.mdx
  requirements.txt
  setup.py
Labels: feature

#3783 [dy] Fix aws secrets circular dependency
  mage_ai/orchestration/db/setup.py
  mage_ai/services/aws/__init__.py
Labels: bug

#3786 [xy] Fix adding dbt block with mage_secret_var.
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
Labels: bug

#3788 [xy] Fix botocore library pickle error in pipeline scheduler.
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#3791 [td] Incorrect method call on PostgreSQL close connection
  mage_integrations/mage_integrations/sources/postgresql/__init__.py
Labels: bug

#3790 [xy] Allow specifying credentials info in bigquery source and dest.
  mage_integrations/mage_integrations/connections/bigquery/__init__.py
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/sources/bigquery/README.md
  mage_integrations/mage_integrations/sources/bigquery/__init__.py
Labels: enhancement

#3797 [jk] Update block policy
  mage_ai/api/policies/BlockPolicy.py
Labels: bug

#3796 [dy] Fix DISABLE_NOTEBOOK_EDIT_ACCESS variable
  mage_ai/api/policies/BasePolicy.py
  mage_ai/settings/__init__.py
  mage_ai/tests/api/policies/test_base_policy.py
Labels: bug

#3789 [td] Show compute info
  mage_ai/api/policies/SparkSqlPolicy.py
  mage_ai/api/policies/SparkStagePolicy.py
  mage_ai/api/presenters/SparkSqlPresenter.py
  mage_ai/api/presenters/SparkStagePresenter.py
  mage_ai/api/resources/SparkSqlResource.py
  mage_ai/api/resources/SparkStageResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/spark/__init__.py
  mage_ai/data_preparation/models/block/spark/mixins.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/ComputeManagement/Jobs/JobsTable.tsx
  mage_ai/frontend/components/ComputeManagement/Monitoring.tsx
  mage_ai/frontend/components/ComputeManagement/SparkGraph/GraphNode.tsx
  mage_ai/frontend/components/ComputeManagement/SparkGraph/index.style.tsx
  mage_ai/frontend/components/ComputeManagement/SparkGraph/index.tsx
  mage_ai/frontend/components/ComputeManagement/SparkGraph/utils.ts
  mage_ai/frontend/components/ComputeManagement/SparkJobSqls.tsx
  mage_ai/frontend/components/ComputeManagement/System.tsx
  mage_ai/frontend/components/ComputeManagement/TasksWaterfallChart/constants.ts
  mage_ai/frontend/components/ComputeManagement/TasksWaterfallChart/index.style.tsx
  mage_ai/frontend/components/ComputeManagement/TasksWaterfallChart/index.tsx
  mage_ai/frontend/components/ComputeManagement/constants.tsx
  mage_ai/frontend/components/ComputeManagement/index.tsx
  mage_ai/frontend/components/ComputeManagement/shared/mocks.ts
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/DependencyGraph/constants.ts
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/shared/Table/index.style.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/SparkType.ts
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
  mage_ai/frontend/utils/date.ts
  mage_ai/frontend/utils/string.ts
  mage_ai/services/spark/api/base.py
  mage_ai/services/spark/api/local.py
  mage_ai/services/spark/api/service.py
  mage_ai/services/spark/constants.py
  mage_ai/services/spark/models/jobs.py
  mage_ai/services/spark/models/sqls.py
  mage_ai/services/spark/models/stages.py
  mage_ai/services/spark/utils.py
Labels: feature

#3782 [dy] Add prestart script support
  .pre-commit-config.yaml
  mage_ai/api/policies/WorkspacePolicy.py
  mage_ai/api/presenters/WorkspacePresenter.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/cluster_manager/config.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/cluster_manager/manage.py
  mage_ai/tests/cluster_manager/__init__.py
  mage_ai/tests/cluster_manager/kubernetes/__init__.py
  mage_ai/tests/cluster_manager/kubernetes/test_workload_manager.py
  scripts/pre-start/create_pre_start.py
  scripts/pre-start/kubernetes_pre_start_template.py
  scripts/pre-start/pre-start.Dockerfile
  scripts/pre-start/pre-start.sh
Labels: feature

#3806 [dy] Hide mage-repo remote
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitCustomBranchResource.py
Labels: enhancement

#3808 [xy] Two small bug fixes
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/server/api/triggers.py
Labels: bug

#3812 Added Custom Spark Cluster
  integrations/custom_spark/Dockerfile
  integrations/custom_spark/README.md
  integrations/custom_spark/hive-site.xml
  integrations/custom_spark/spark.yaml
Labels: enhancement

#3814 Redshift: Use TIMESTAMPTZ column type for datetimes
  mage_integrations/mage_integrations/destinations/redshift/utils.py
Labels: bug

#3821 [xy] Serialize np.ndarray before exporting to postgres.
  mage_ai/io/mssql.py
  mage_ai/io/mysql.py
  mage_ai/io/postgres.py
  mage_ai/io/trino.py
Labels: bug

#3823 [xy] Support Redshift Serverless
  docs/integrations/databases/Redshift.mdx
  mage_integrations/mage_integrations/destinations/redshift/__init__.py
Labels: bug

#3778 Improved Slack notification design
  mage_ai/orchestration/notification/sender.py
  mage_ai/services/slack/slack.py
  mage_ai/tests/orchestration/notification/test_sender.py
Labels: enhancement

#3817 [dy] Support Github Enterprise authentication
  mage_ai/api/resources/OauthResource.py
  mage_ai/authentication/oauth/constants.py
  mage_ai/authentication/oauth/utils.py
  mage_ai/data_preparation/git/api.py
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/interfaces/OauthType.ts
  mage_ai/frontend/pages/oauth.tsx
  mage_ai/frontend/storage/localStorage.ts
  mage_ai/server/server.py
Labels: feature

#3685 Case sensitive column names in DI SQL destinations
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/destinations/mssql/README.md
  mage_integrations/mage_integrations/destinations/mssql/__init__.py
  mage_integrations/mage_integrations/destinations/mssql/utils.py
  mage_integrations/mage_integrations/destinations/mysql/README.md
  mage_integrations/mage_integrations/destinations/mysql/__init__.py
  mage_integrations/mage_integrations/destinations/oracledb/README.md
  mage_integrations/mage_integrations/destinations/oracledb/__init__.py
  mage_integrations/mage_integrations/destinations/oracledb/utils.py
  mage_integrations/mage_integrations/destinations/postgresql/README.md
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/destinations/redshift/README.md
  mage_integrations/mage_integrations/destinations/redshift/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/utils.py
  mage_integrations/mage_integrations/destinations/sql/base.py
  mage_integrations/mage_integrations/destinations/sql/utils.py
  mage_integrations/mage_integrations/tests/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/tests/destinations/bigquery/test_bigquery.py
  mage_integrations/mage_integrations/tests/destinations/mssql/__init__.py
  mage_integrations/mage_integrations/tests/destinations/mssql/test_mssql.py
  mage_integrations/mage_integrations/tests/destinations/mysql/__init__.py
  mage_integrations/mage_integrations/tests/destinations/mysql/test_mysql.py
  mage_integrations/mage_integrations/tests/destinations/oracledb/__init__.py
  mage_integrations/mage_integrations/tests/destinations/oracledb/test_oracledb.py
  mage_integrations/mage_integrations/tests/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/tests/destinations/postgresql/test_postgres.py
  mage_integrations/mage_integrations/tests/destinations/redshift/__init__.py
  mage_integrations/mage_integrations/tests/destinations/redshift/test_redshift.py
  mage_integrations/mage_integrations/tests/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py
Labels: feature, python, data integration

#3811 [dy] Refactor workspace
  mage_ai/api/presenters/WorkspacePresenter.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/cluster_manager/config.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/cluster_manager/manage.py
  mage_ai/cluster_manager/workspace/__init__.py
  mage_ai/cluster_manager/workspace/base.py
  mage_ai/cluster_manager/workspace/cloud_run.py
  mage_ai/cluster_manager/workspace/ecs.py
  mage_ai/cluster_manager/workspace/kubernetes.py
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/oracle/components/Accordion/index.tsx
Labels: bug

#3824 [xy] Initialize db_connection session before interpolating repo config.
  mage_ai/cli/main.py
Labels: bug

#3825 [td] 0.9.37
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/utils/models/project/index.ts
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/server/constants.py
  setup.py
Labels: enhancement

#3826 [td] Refresh page when adding block and split view
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: enhancement

#3830 [td] 0.9.38
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/server/constants.py
  setup.py
Labels: bug

#3832 [td] Fix code block header overflow menu
  mage_ai/frontend/components/CodeBlock/index.style.tsx
Labels: bug

#3837 [td] Allow admin users to read attributes on users list
  mage_ai/api/policies/UserPolicy.py
Labels: bug

#3838 [td] 0.9.39
  mage_ai/server/constants.py
  setup.py
Labels: bug

#3840 [xy] Fix libodbc conflicts in Dockerfile.
  Dockerfile
Labels: bug

#3845 [xy] Fix libodbc conflicts in dev.Dockerfile.
  dev.Dockerfile
Labels: bug

#3847 [td] Fix dynamic children not running and its downstream
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#3827 [td] Dependency graph tree v2
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/policies/FileVersionPolicy.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/FileVersionResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/DependencyGraph/constants.ts
  mage_ai/frontend/components/DependencyGraph/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/DependencyGraph/utils.ts
  mage_ai/frontend/components/FileVersions/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: feature, enhancement

#3851 [td] Only get spark jobs if compute enabled
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/ComputeManagement/SparkGraph/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/DependencyGraph/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/PipelineDetail/ColumnScroller/index.tsx
Labels: bug

#3852 [td] Update header for compute management
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/interfaces/KernelType.ts
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: enhancement

#3856 Expanded our vocabulary
  mage_ai/frontend/utils/samples/adjectives.ts
Labels: enhancement

#3834 [mp] Update Git Sync Docs
  docs/getting-started/setting-up-git.mdx
Labels: documentation

#3859 [xy] Remove pymssql dependency
  Dockerfile
  dev.Dockerfile
  mage_integrations/mage_integrations/connections/mssql/__init__.py
  mage_integrations/mage_integrations/destinations/mssql/README.md
  mage_integrations/mage_integrations/destinations/mssql/__init__.py
  mage_integrations/mage_integrations/sources/mssql/README.md
  mage_integrations/mage_integrations/sources/mssql/__init__.py
  mage_integrations/requirements.txt
Labels: bug

#3857 [kh] Added magical nouns
  mage_ai/frontend/utils/samples/nouns.ts
Labels: enhancement

#3819 [Fix] Reposition file browser context menu
  mage_ai/frontend/components/FileBrowser/index.tsx
Labels: bug

#3849 [ac] Improve app header styling
  mage_ai/frontend/components/ServerTimeDropdown/ServerTimeButton.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
Labels: enhancement

#3816 [jk] Detach block from shared pipelines
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/templates/data_exporters/streaming/default.jinja
  mage_ai/data_preparation/templates/data_loaders/streaming/default.jinja
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/Extensions/constants.ts
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: feature

#3843 [ac] Add `ctrl/cmd + click` keyboard shortcut for selecting pipeline run rows
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/context/shared/utils.ts
Labels: enhancement

#3799 [mp] Simplify Getting Started for Contributors
  README_dev.md
  docs/contributing/development-environment.mdx
  docs/introduction/overview.mdx
Labels: documentation

#3836 [dy] Lifecycle post start script
  mage_ai/cluster_manager/config.py
  mage_ai/cluster_manager/errors.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/frontend/components/FileSelectorPopup/index.tsx
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/components/workspaces/Dashboard/constants.ts
  mage_ai/frontend/components/workspaces/Dashboard/index.tsx
  mage_ai/frontend/interfaces/FileType.ts
  mage_ai/frontend/pages/manage/files/index.tsx
  mage_ai/server/api/clusters.py
  mage_ai/server/server.py
  mage_ai/tests/cluster_manager/kubernetes/test_workload_manager.py
Labels: feature
