Repository mage-ai/mage-ai, pull requests merged in 2023-07, with the labels that each got.

#3008 automate release note generation
  .github/releases.yml
Labels: documentation

#3010 [mp] Add docs for Azure deploy to container
  .github/release.yml
  docs/production/ci-cd/local-cloud/github-actions.mdx
  docs/production/ci-cd/staging-production/github-actions.mdx
  docs/production/observability/alerting-slack.mdx
Labels: documentation

#3000 [dy] Update secrets management backend
  mage_ai/api/policies/AutocompleteItemPolicy.py
  mage_ai/api/policies/BackfillPolicy.py
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/policies/BlockRunPolicy.py
  mage_ai/api/policies/BlockTemplatePolicy.py
  mage_ai/api/policies/ClusterPolicy.py
  mage_ai/api/policies/DataProviderPolicy.py
  mage_ai/api/policies/EventRulePolicy.py
  mage_ai/api/policies/ExtensionOptionPolicy.py
  mage_ai/api/policies/FileVersionPolicy.py
  mage_ai/api/policies/KernelPolicy.py
  mage_ai/api/policies/LogPolicy.py
  mage_ai/api/policies/OutputPolicy.py
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/policies/PipelineRunPolicy.py
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/policies/SecretPolicy.py
  mage_ai/api/policies/SessionPolicy.py
  mage_ai/api/policies/VariablePolicy.py
  mage_ai/api/policies/WidgetPolicy.py
  mage_ai/api/resources/RoleResource.py
  mage_ai/api/resources/SecretResource.py
  mage_ai/api/resources/UserResource.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/api/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/orchestration/constants.py
  mage_ai/orchestration/db/migrations/versions/90d978a8aef8_update_unique_constraint_for_secret.py
  mage_ai/orchestration/db/migrations/versions/e3593cc2191e_add_key_uuid_to_secrets.py
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/secrets.py
  mage_ai/server/terminal_server.py
  mage_ai/server/websocket_server.py
  mage_ai/tests/api/test_utils.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: bug

#3016 [xy] Improve pipeline scheduler and support distributed process queue
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/metrics/pipeline_run.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/queue/config.py
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/orchestration/utils/distributed_lock.py
  mage_ai/settings/__init__.py
  requirements.txt
Labels: enhancement

#3023 [mp] add google oauth2 scopes to bigquery client
  mage_ai/io/bigquery.py
Labels: bug

#3012 [mp] enable backfills `delete` and add documentation
  docs/api-reference/backfills/delete-backfill.mdx
  docs/api-reference/backfills/read-backfills.mdx
  docs/api-reference/backfills/update-backfill.mdx
  docs/api-reference/pipeline-runs/read-pipeline-runs.mdx
  docs/api-reference/pipelines/create-pipeline.mdx
  docs/mint.json
  mage_ai/api/policies/BackfillPolicy.py
  media/pipeline-variables.png
Labels: bug

#3038 [jk] Display error when fetching data providers
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#3041 [jk] Add /files route to backend server and fix TypeError in FileEditor
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/server/server.py
Labels: bug

#3035 [xy] Create dynamic block runs in block executor.
  mage_ai/data_preparation/executors/azure_container_instance_executor.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/executors/ecs_block_executor.py
  mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
  mage_ai/data_preparation/executors/k8s_block_executor.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/executors/test_k8s_block_executor.py
Labels: bug

#3021 [td] Fix block settings not updating after saving
  mage_ai/api/policies/BlockPolicy.py
Labels: bug

#3049 [dy] Fix roles query by entity bug
  mage_ai/api/resources/RoleResource.py
Labels: bug

#3050 [jk] Add "Updated at" column to Pipelines list page
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#3052 [jk] Default error log to Errors tab when opening log detail
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/Logs/Detail/index.tsx
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
Labels: enhancement

#3017 [mp] api quickstart for rapid development
  docs/api-reference/overview.mdx
  media/local-auth.png
Labels: bug

#3054 Update `releases.yml` to account for new tags: `feature` & `enhancement`
  .github/release.yml
Labels: documentation

#3051 [dy] Add timeout for fetching files for git
  mage_ai/api/policies/LlmPolicy.py
  mage_ai/api/presenters/GitCustomBranchPresenter.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/data_preparation/git/__init__.py
Labels: bug

#3040 [mp] fix broken links
  docs/contributing/backend/overview.mdx
  docs/contributing/statistics/overview.mdx
  docs/data-integrations/sources/add-new-source.mdx
  docs/data-integrations/sources/postgresql.mdx
  docs/dbt/connection-profiles.mdx
  docs/guides/streaming/overview.mdx
  docs/introduction/overview.mdx
  docs/production/deploying-to-cloud/aws/setup.mdx
  docs/production/deploying-to-cloud/azure/setup.mdx
Labels: documentation

#3071 [xy] Add doc for scale web server and schedulers.
  docs/production/deploying-to-cloud/architecture.mdx
Labels: documentation

#3053 [mp] simplify GCP terraform docs to use cloud run
  docs/mint.json
  docs/production/deploying-to-cloud/gcp/gcp-artifact-registry.mdx
  docs/production/deploying-to-cloud/gcp/setup.mdx
Labels: documentation

#3005 Adding clickhouse on data integrations destination
  mage_ai/data_integrations/destinations/constants.py
  mage_integrations/mage_integrations/destinations/clickhouse/LICENSE
  mage_integrations/mage_integrations/destinations/clickhouse/__init__.py
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/__init__.py
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/sinks.py
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/target.py
  mage_integrations/mage_integrations/destinations/clickhouse/templates/config.json
  mage_integrations/mage_integrations/destinations/sink.py
  mage_integrations/mage_integrations/destinations/sqlsink.py
  mage_integrations/mage_integrations/destinations/target.py
  mage_integrations/mage_integrations/utils/logger/__init__.py
  mage_integrations/mage_integrations/utils/logger/constants.py
  mage_integrations/requirements.txt
  requirements.txt
  setup.py
Labels: feature

#3029 [xh]Generate block template based on block description
  mage_ai/ai/constants.py
  mage_ai/ai/generator.py
  mage_ai/ai/generator_cmds.py
  mage_ai/ai/llm_pipeline_wizard.py
Labels: feature

#3079 [dy] Render text/html from block output
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/package.json
  mage_ai/frontend/yarn.lock
Labels: enhancement

#3090 [jk] Do not make block outputs API request if after panel hidden
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#3092 [jk] Clear pipeline list filters when clicking Defaults
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
Labels: bug

#3097 [jk] Decrease variables response size
  mage_ai/api/policies/VariablePolicy.py
  mage_ai/api/resources/VariableResource.py
  mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: enhancement

#3099 [jk] Clean up code in VariableResource method
  mage_ai/api/resources/VariableResource.py
Labels: enhancement

#3100 [mp] fetch snowflake role
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
Labels: bug

#3098 [mp] update favicon and add SQLite context
  docs/design/core-abstractions.mdx
  docs/favicon.png
Labels: documentation

#3032 [mp] Add service argument to OracleDB data loader
  mage_ai/io/config.py
  mage_ai/io/oracledb.py
Labels: bug

#3019 [mp] add oracledb source to data loader docs
  docs/design/data-loading.mdx
Labels: documentation

#3072 [mp] pipeline tagging documentation
  docs/design/core-abstractions.mdx
  docs/pipelines/pipeline-tagging.mdx
Labels: documentation

#3125 [jk] Fix positioning of nested flyout menu 4 levels deep
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
Labels: bug

#3133 [jk] Misc UI improvements
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/PipelineExecution/index.tsx
  mage_ai/frontend/components/Sidekick/index.style.ts
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/oracle/components/Badge/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#2896 [hw] Enable batch upload for Snowflake destination through the COPY approach
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
  mage_integrations/mage_integrations/destinations/snowflake/utils.py
Labels: feature

#3139 [xy] Delete logs after log retention period.
  mage_ai/cli/main.py
  mage_ai/data_preparation/logging/__init__.py
  mage_ai/data_preparation/logging/gcs_logger_manager.py
  mage_ai/data_preparation/logging/logger_manager.py
  mage_ai/data_preparation/logging/s3_logger_manager.py
  mage_ai/tests/base_test.py
  mage_ai/tests/data_preparation/logging/__init__.py
  mage_ai/tests/data_preparation/logging/test_logger_manager.py
Labels: feature

#3102 [dy] Batch git sync in pipeline_scheduler
  mage_ai/api/resources/CustomTemplateResource.py
  mage_ai/api/resources/SearchResultResource.py
  mage_ai/api/resources/VariableResource.py
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/orchestration/monitor/monitor_stats.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/triggers/api.py
  mage_ai/orchestration/utils/git.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: bug
