Repository mage-ai/mage-ai, pull requests merged in 2023-08, with the labels that each got.

#3142 [dy] Only try to interpolate variables if they are in the query
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/frontend/pages/settings/workspace/users/index.tsx
  mage_ai/orchestration/triggers/api.py
  mage_ai/server/server.py
Labels: bug

#3134 [mp] aws ecs docs & architecture diagram
  docs/media/architecture/aws-ecs.png
  docs/media/local-auth.png
  docs/mint.json
  docs/production/deploying-to-cloud/aws/aws-ecs-architecture.mdx
  docs/production/deploying-to-cloud/aws/resources.mdx
Labels: documentation

#2772 Salesforce destination
  mage_ai/data_integrations/destinations/constants.py
  mage_integrations/mage_integrations/destinations/salesforce/README.md
  mage_integrations/mage_integrations/destinations/salesforce/__init__.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/__init__.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/session_credentials.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/sinks.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/utils/__init__.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/utils/exceptions.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/utils/transformation.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/utils/validation.py
  mage_integrations/mage_integrations/destinations/salesforce/templates/config.json
  mage_integrations/mage_integrations/utils/logger/__init__.py
  mage_integrations/requirements.txt
Labels: feature

#3101 [mp] fix dbt/postgres tutorials
  docs/tutorials/load-api-data.mdx
  docs/tutorials/setup-dbt.mdx
Labels: documentation

#3150 [xy] Add docs for new features
  docs/design/data-pipeline-management.mdx
  docs/production/configuring-production-settings/compute-resource.mdx
  docs/production/observability/logging.mdx
Labels: documentation

#3151 [mp] document `invalidtoken` error
  docs/development/troubleshooting.mdx
Labels: documentation

#3156 [jk] Add block runtime chart for all blocks
  mage_ai/frontend/components/charts/LineSeries.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/monitors/block-runtime.tsx
Labels: enhancement

#3164 [mp] swap elephantdb for supabase
  docs/tutorials/load-api-data.mdx
  docs/tutorials/setup-dbt.mdx
Labels: documentation

#3075 Use Playwright for web UI test automation
  .github/workflows/build_and_test.yml
  .gitignore
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/package.json
  mage_ai/frontend/playwright.config.ci.ts
  mage_ai/frontend/playwright.config.ts
  mage_ai/frontend/tests/basic.spec.ts
  mage_ai/frontend/yarn.lock
Labels: enhancement

#3170 [jk] Auto-scroll to newest logs
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/frontend/components/Logs/Toolbar/index.tsx
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
  mage_ai/frontend/oracle/elements/Divider/index.tsx
  mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
  mage_ai/frontend/storage/constants.ts
Labels: enhancement

#3180 [mp] add documentation on local hosting w/ different port
  docs/development/troubleshooting.mdx
Labels: documentation

#3168 [dy] Fix circular dependency and repo config issues
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/shared/utils.py
  mage_ai/orchestration/db/utils.py
  mage_ai/tests/data_preparation/test_repo_manager.py
Labels: bug

#3152 [dy] Consolidate aws region variables
  mage_ai/cluster_manager/aws/ecs_task_manager.py
  mage_ai/services/aws/__init__.py
  mage_ai/services/aws/ecs/ecs.py
  mage_ai/services/aws/emr/emr.py
  mage_ai/services/aws/events/events.py
  mage_ai/services/aws/secrets_manager/secrets_manager.py
Labels: enhancement

#3181 [mp] fix table formatting and update template
  docs/production/deploying-to-cloud/aws-without-terraform.mdx
Labels: documentation

#3183 [dy] Fix error logging for replica blocks
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/server/websocket_server.py
Labels: bug

#3200 [dy] Support updating ingress when creating k8s workspace
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/database_manager.py
Labels: enhancement

#3189 [dy] Escape password in db_connection_url
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/database_manager.py
Labels: bug

#3199 [jk] Renaming blocks with shared pipelines
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/BlockSettings/index.style.ts
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/CodeEditor/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/constants.ts
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/PipelineDetailPage/index.style.tsx
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/components/shared/Sticky/PageSectionHeader.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/oracle/components/FlexContainer.tsx
  mage_ai/frontend/oracle/components/Layout/MultiColumn.style.tsx
  mage_ai/frontend/oracle/components/Layout/MultiColumn.tsx
  mage_ai/frontend/oracle/components/Layout/index.tsx
  mage_ai/frontend/oracle/components/RowDataTable/index.style.ts
  mage_ai/frontend/oracle/components/RowDataTable/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/oracle/styles/units/icons.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/stories/ThemeBlock.tsx
  mage_ai/frontend/stories/components/charts/Histogram.stories.tsx
  mage_ai/frontend/stories/components/charts/PieChart.stories.tsx
  mage_ai/frontend/stories/oracle/components/Layout.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Button/Button.stories.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: bug, enhancement

#3213 [jk] Fix infinite rendering loop in SchemaTable
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
Labels: bug

#3216 [jk] Fix log detail metrics object rendering issue
  mage_ai/frontend/components/Logs/Detail/index.tsx
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
Labels: bug

#3219 [jk] Add API endpoint to Trigger detail page
  mage_ai/frontend/api/utils/url.ts
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: enhancement

#3222 [td] Add pipeline schedule tags
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
Labels: feature

#3204 [mp] add custom timeout to kafka streams
  mage_ai/streaming/constants.py
  mage_ai/streaming/sources/kafka.py
Labels: enhancement

#3225 [td] Fix dbt snowflake when password null
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
Labels: bug

#3196 [dy] Update redshift format value
  mage_ai/io/redshift.py
  mage_ai/io/utils.py
Labels: bug

#3226 [td] Add global data product block to add block v1
  mage_ai/frontend/components/GlobalDataProductDetail/SettingsField.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
Labels: bug, enhancement

#3227 [xy] Fix EMR pyspark kernel permission error
  mage_ai/data_preparation/repo_manager.py
Labels: bug

#3224 [dy] Update where the `frontend_dist_base_path` is created
  mage_ai/server/server.py
  mage_ai/tests/server/test_server.py
Labels: bug

#3229 [jk] Block run and pipeline run start/completion times in UTC
  mage_ai/api/resources/BackfillResource.py
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#3235 [jk] Allow adding block from search
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#3237 [xy] Limit the number of rows of sql block output in pipeline run
  docs/guides/sql-blocks.mdx
  mage_ai/data_preparation/models/block/sql/__init__.py
Labels: enhancement

#3236 [jk] Allow canceling of individual running pipeline runs
  mage_ai/api/resources/PipelineResource.py
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/oracle/components/FlyoutMenu/index.style.tsx
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/oracle/elements/Divider/index.style.ts
  mage_ai/frontend/oracle/elements/Divider/index.tsx
  mage_ai/frontend/oracle/elements/Link/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/oracle/styles/themes/dark.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: feature

#3256 [xy] Use greater than operator for unique columns in source sql bookmark comparison.
  mage_integrations/mage_integrations/sources/sql/base.py
Labels: enhancement

#3257 [jk] Update block runs table
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/oracle/elements/Text/index.tsx
Labels: enhancement

#3265 [xy] Not obfuscate data in data integration records.
  mage_ai/data_preparation/models/block/integration/__init__.py
Labels: bug

#3268 [xy] Improve error message for duplicate column name.
  mage_ai/data_preparation/models/variable.py
Labels: enhancement

#3264 [hw] When comparing spark.jars, use the file names and neglect paths
  mage_ai/services/spark/spark.py
  mage_ai/tests/services/spark/__init__.py
  mage_ai/tests/services/spark/test_spark.py
Labels: bug

#3243 [dy] Import decorators when executing block module
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/tests/data_preparation/models/test_block.py
Labels: bug

#3273 [xy] Fix using location in dbt bigquery.
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
  mage_ai/data_preparation/models/variable.py
Labels: bug

#3258 Docker: Optimize build by reordering and grouping some statements
  Dockerfile
  dev.Dockerfile
Labels: enhancement

#3274 [dy] Fix trigger not showing up in block run view
  mage_ai/api/presenters/BlockRunPresenter.py
  mage_ai/api/resources/BlockRunResource.py
Labels: bug

#3276 [jk] Block run count formatting in PipelineRuns table
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/PipelineDetail/Syncs/SyncRowDetail/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
Labels: enhancement

#3272 [mp] Remove WIP sections from documentation
  docs/api-reference/pipeline-schedules/create-pipeline-schedule.mdx
  docs/api-reference/pipeline-schedules/delete-pipeline-schedule.mdx
  docs/data-integrations/destinations/adapt-existing-destination.mdx
  docs/data-integrations/overview.mdx
  docs/data-integrations/sources/adapt-existing-source.mdx
  docs/design/core-abstractions.mdx
  docs/guides/transformer-blocks.mdx
  docs/integrations/spark-pyspark.mdx
Labels: documentation

#3279 base.py: add XML support
  docs/design/data-loading.mdx
  mage_ai/io/base.py
Labels: enhancement

#3278 [mp] blocks api docs
  docs/api-reference/blocks/create-block.mdx
  docs/api-reference/blocks/delete-block.mdx
  docs/api-reference/blocks/overview.mdx
  docs/api-reference/blocks/read-block.mdx
  docs/api-reference/blocks/update-block.mdx
  docs/api-reference/pipelines/create-pipeline.mdx
  docs/api-reference/pipelines/delete-pipeline.mdx
  docs/api-reference/pipelines/overview.mdx
  docs/api-reference/pipelines/read-pipeline.mdx
  docs/api-reference/pipelines/update-pipeline.mdx
  docs/mint.json
Labels: documentation

#3283 [dy] Fix bugs for workspaces
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/orchestration/db/models/base.py
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/server/server.py
  mage_ai/tests/orchestration/db/models/test_oauth.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: bug

#3234 [dy] Update error logging for block runs
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/shared/retry.py
Labels: enhancement

#3294 [xy] Add block templates for MSSQL.
  docs/integrations/databases/MicrosoftSQLServer.mdx
  mage_ai/data_preparation/templates/constants.py
  mage_ai/data_preparation/templates/data_exporters/mssql.py
  mage_ai/data_preparation/templates/data_loaders/mssql.py
  mage_ai/io/mssql.py
Labels: feature

#3300 [jk] Browser-specific dependency graph improvements
  mage_ai/frontend/components/DependencyGraph/index.tsx
Labels: enhancement

#3286 Updated clickhouse destination
  mage_integrations/mage_integrations/destinations/clickhouse/README.md
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/sinks.py
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/target.py
  mage_integrations/mage_integrations/destinations/clickhouse/templates/config.json
Labels: enhancement

#3310 [jk] Make pipeline run count pagination consistent
  mage_ai/api/policies/PipelineRunPolicy.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/shared/Paginate/index.tsx
  mage_ai/frontend/interfaces/PipelineRunType.ts
  mage_ai/frontend/pages/pipeline-runs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
Labels: enhancement

#3289 [dy] Add new base path environment variables
  docs/development/environment-variables.mdx
  docs/getting-started/setup.mdx
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  mage_ai/tests/server/test_server.py
Labels: enhancement

#3311 [dy] Add column identifier for trino
  mage_integrations/mage_integrations/destinations/trino/connectors/base.py
Labels: bug

#3315 [xy] Fix mage run cli command with variables
  docs/production/configuring-production-settings/runtime-variable.mdx
  mage_ai/cli/main.py
  mage_ai/cli/utils.py
Labels: bug

#3313 Fix async_generate_block_with_description upstream_blocks param
  mage_ai/ai/llm_pipeline_wizard.py
Labels: bug

#3317 [jk] Add pipeline "created_at" property
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: enhancement

#3316 [jk] Add pagination to pipeline run block runs page
  mage_ai/api/presenters/PipelineRunPresenter.py
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/interfaces/BlockRunType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
Labels: enhancement

#3319 Adding oracledb lib to mage-ai
  requirements.txt
  setup.py
Labels: dependencies

#3323 [xy] Comment out flaky test of pipeline execution
  mage_ai/tests/data_preparation/executors/test_pipeline_executor.py
Labels: bug

#3321 [hw] Update the user docs for Databricks with some refinements
  docs/integrations/databricks.mdx
Labels: documentation

#3290 [mp] docs for adding a source
  .gitignore
  docs/data-integrations/sources/adapt-existing-source.mdx
  docs/media/adapt-existing-source/new-pipeline.png
  docs/media/adapt-existing-source/select-source.png
  mage_integrations/README.md
Labels: documentation

#3322 Added test connection to google_ads source
  mage_integrations/mage_integrations/sources/google_ads/__init__.py
Labels: feature

#3301 Added all columns as replication key
  mage_integrations/mage_integrations/sources/sql/base.py
  mage_integrations/mage_integrations/tests/sources/bigquery/test_bigquery.py
  mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py
  mage_integrations/mage_integrations/tests/sources/sql/test_base.py
Labels: enhancement

#3287 Removed unused config in Salesforce destination
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/destinations/salesforce/__init__.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py
Labels: bug

#3325 [xy] Fix bigquery bookmark datetime comparison
  mage_integrations/mage_integrations/sources/bigquery/__init__.py
Labels: bug

#3326 [xy] Improve streaming pipeline stability
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/streaming/sinks/amazon_s3.py
  mage_ai/streaming/sinks/base.py
  mage_ai/streaming/sources/amazon_sqs.py
  mage_ai/streaming/sources/base.py
Labels: enhancement

#3309 [dy] Fix secrets bugs
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/tests/data_preparation/shared/test_secrets.py
Labels: bug

#3332 [mp] code of conduct hotfix
  docs/contributing/code-of-conduct.mdx
Labels: documentation

#3327 [jk] Sort pipelines on Pipelines Dashboard
  mage_ai/frontend/components/shared/Table/constants.ts
  mage_ai/frontend/components/shared/Table/index.style.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/oracle/elements/Text/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/storage/pipelines.ts
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: feature

#3335 Elasticsearch as Sink for Streaming
  docs/guides/streaming/destinations/elasticsearch.mdx
  mage_ai/data_preparation/templates/data_exporters/streaming/elasticsearch.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/interfaces/DataSourceType.ts
  mage_ai/streaming/constants.py
  mage_ai/streaming/sinks/elasticsearch.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/tests/streaming/sinks/test_elasticsearch.py
  requirements.txt
Labels: feature

#3342 [xy] Fix MongoDB source
  mage_ai/data_integrations/sources/constants.py
  mage_integrations/mage_integrations/sources/mongodb/README.md
  mage_integrations/mage_integrations/sources/mongodb/__init__.py
  mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/__init__.py
  mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/sync_strategies/full_table.py
  mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/sync_strategies/incremental.py
  mage_integrations/mage_integrations/sources/mongodb/tap_mongodb/sync_strategies/oplog.py
Labels: bug

#3338 [dy] Overwrite existing project_uuid if a project_uuid is set when starting the server
  mage_ai/cli/main.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/server/server.py
  mage_ai/tests/data_preparation/test_repo_manager.py
Labels: bug

#3252 [mp] add github source
  .gitignore
  mage_ai/data_integrations/sources/constants.py
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/sources/github/README.md
  mage_integrations/mage_integrations/sources/github/__init__.py
  mage_integrations/mage_integrations/sources/github/tap_github/__init__.py
  mage_integrations/mage_integrations/sources/github/tap_github/client.py
  mage_integrations/mage_integrations/sources/github/tap_github/discover.py
  mage_integrations/mage_integrations/sources/github/tap_github/schema.py
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/assignees.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/collaborators.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/comments.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/commit_comments.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/commits.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/events.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/issue_events.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/issue_labels.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/issue_milestones.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/issues.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/pr_commits.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/project_cards.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/project_columns.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/projects.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/pull_requests.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/releases.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/review_comments.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/reviews.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/shared/issue_permissions.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/shared/performed_via_github_app.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/shared/pull_permissions.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/shared/reactions.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/shared/user.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/stargazers.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/team_members.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/team_memberships.json
  mage_integrations/mage_integrations/sources/github/tap_github/schemas/teams.json
  mage_integrations/mage_integrations/sources/github/tap_github/streams.py
  mage_integrations/mage_integrations/sources/github/tap_github/sync.py
  mage_integrations/mage_integrations/sources/github/templates/config.json
  mage_integrations/mage_integrations/sources/github/tests/__init__.py
  mage_integrations/mage_integrations/sources/github/tests/base.py
Labels: enhancement

#3345 [dy] Add started_at to pipeline run policy
  mage_ai/api/presenters/PipelineRunPresenter.py
Labels: bug

#3346 [xy] Fix passing variables to run_blocks.
  mage_ai/data_preparation/executors/pipeline_executor.py
Labels: bug

#3347 [td] Add run_pipeline_in_one_process in pipeline settings
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
Labels: enhancement

#3341 [jk] Preview next pipeline run time for triggers
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/presenters/PipelineSchedulePresenter.py
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/utils/date.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: enhancement

#3348 [jk] Explain cron syntax in a human readable way
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/yarn.lock
Labels: bug, enhancement

#3329 Docker: Optimize build by reordering and grouping some statements v2
  Dockerfile
  dev.Dockerfile
Labels: enhancement

#3353 [jk] Integration pipeline column explanations
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
Labels: enhancement

#3355 [xy] Not pass liveness_probe to cloud run jobs.
  mage_ai/services/gcp/cloud_run/cloud_run.py
Labels: bug

#3350 [dy] Update terminal server user token handling
  mage_ai/frontend/components/VersionControl/GitActions.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/terminal/index.tsx
  mage_ai/server/terminal_server.py
Labels: security

#3360 [xy] Fix data integration pipeline column renaming in transformer block.
  mage_ai/data_preparation/models/block/integration/__init__.py
Labels: bug

#3363 [dy] Fix FileContentResource file path check
  mage_ai/api/resources/FileContentResource.py
Labels: bug

#3365 [td] Generate pipeline using AI
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/frontend/components/AI/ControlPanel/index.tsx
  mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
  mage_ai/frontend/components/Dashboard/utils.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/interfaces/LLMType.ts
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#3366 [td] Add docs for using AI
  docs/guides/ai/overview.mdx
  docs/mint.json
Labels: documentation

#3352 [dy] Update api/status endpoint
  mage_ai/api/middleware.py
  mage_ai/server/api/v1.py
  mage_ai/server/server.py
Labels: bug

#3369 Removed unique_constraints from valid_replication_keys definition
  mage_integrations/mage_integrations/sources/sql/base.py
  mage_integrations/mage_integrations/tests/sources/mysql/test_mysql.py
Labels: bug, python

#3371 [xy] Allow using k8s executor config for streaming pipeline.
  mage_ai/data_preparation/executors/k8s_pipeline_executor.py
Labels: enhancement

#3372 [td] Add page block layout class and API
  mage_ai/api/policies/PageBlockLayoutPolicy.py
  mage_ai/api/presenters/PageBlockLayoutPresenter.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/presenters/__init__.py
  mage_ai/presenters/block_layout/__init__.py
  mage_ai/presenters/block_layout/constants.py
  mage_ai/presenters/block_layout/page.py
  mage_ai/presenters/constants.py
Labels: feature

#3374 [xy] Add role to snowflake data integration pipeline.
  mage_integrations/mage_integrations/connections/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/templates/config.json
  mage_integrations/mage_integrations/sources/snowflake/README.md
  mage_integrations/mage_integrations/sources/snowflake/__init__.py
  mage_integrations/mage_integrations/sources/snowflake/templates/config.json
Labels: enhancement

#3376 [xy] Fix dbt command failure due to empty content args
  mage_ai/data_preparation/models/block/dbt/__init__.py
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
Labels: bug

#3354 [dy] Read DB credentials from AWS secret manager
  docs/mint.json
  docs/production/databases/default.mdx
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/orchestration/constants.py
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/setup.py
Labels: enhancement

#3367 [mp] nav fast-follow
  .gitignore
  docs/about/code-of-conduct.mdx
  docs/about/statistics.mdx
  docs/api-reference/overview.mdx
  docs/contributing/overview.mdx
  docs/design/core-abstractions.mdx
  docs/design/core-design-principles.mdx
  docs/design/data-pipeline-management.mdx
  docs/getting-started/setup.mdx
  docs/guides/community-examples.mdx
  docs/guides/overview.mdx
  docs/guides/setup-dbt.mdx
  docs/integrations/databases/trino.mdx
  docs/introduction/overview.mdx
  docs/mint.json
  docs/orchestration/global-data-products/overview.mdx
  docs/production/deploying-to-cloud/architecture.mdx
  docs/production/deploying-to-cloud/secrets/AWS.mdx
  docs/production/deploying-to-cloud/using-helm.mdx
  docs/production/deploying-to-cloud/using-terraform.mdx
Labels: documentation

#3356 [jk] Add sorting to Block Runs table
  mage_ai/api/policies/BlockRunPolicy.py
  mage_ai/api/resources/BlockRunResource.py
  mage_ai/frontend/components/ActionForm/index.tsx
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/ChartBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/frontend/components/Logs/Toolbar/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/RecommendationsWindow/index.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/components/datasets/overview/utils.tsx
  mage_ai/frontend/components/shared/Table/constants.ts
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/BlockRunType.ts
  mage_ai/frontend/oracle/components/Panel/index.tsx
  mage_ai/frontend/oracle/components/Table/BaseTable.tsx
  mage_ai/frontend/pages/manage/users/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/logs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/monitors/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: feature

#3375 [td] Add chart data source base and for block
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/presenters/charts/__init__.py
  mage_ai/presenters/charts/data_sources/__init__.py
  mage_ai/presenters/charts/data_sources/base.py
  mage_ai/presenters/charts/data_sources/block.py
  mage_ai/presenters/charts/data_sources/chart_code.py
  mage_ai/presenters/charts/data_sources/constants.py
  mage_ai/shared/strings.py
Labels: feature

#3383 [mp] hotfix for database icon
  docs/mint.json
  docs/production/databases/default.mdx
Labels: documentation

#3370 [jk] Delete individual run from pipeline runs table
  mage_ai/api/policies/PipelineRunPolicy.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/frontend/components/Orchestration/Sidebar/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/shared/Table/constants.ts
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/orchestration/db/models/schedules.py
Labels: feature

#3387 [td] Block layout item API
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/BlockLayoutItemPolicy.py
  mage_ai/api/presenters/BlockLayoutItemPresenter.py
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/presenters/charts/data_sources/chart_code.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: feature

#3389 [jk] Fix nextjs local build type error
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/package.json
  mage_ai/frontend/yarn.lock
Labels: bug

#3391 [mp] Add reference documentation for AI guides
  docs/development/ai/overview.mdx
  docs/guides/ai/overview.mdx
  docs/guides/setup-dbt.mdx
  docs/media/overview/ai-demo.gif
  docs/mint.json
Labels: documentation

#3390 [mp] update dbt connections/variables docs
  docs/dbt/connection-profiles.mdx
  docs/dbt/variable-interpolation.mdx
  docs/media/connection-profiles/dbt-target.png
  docs/mint.json
Labels: documentation

#3393 [xy] Add healthcheck to sqs streaming source.
  mage_ai/streaming/sources/amazon_sqs.py
  mage_ai/streaming/sources/base.py
Labels: enhancement

#3388 Fixes on MongoDB destination (Data integration)
  mage_integrations/mage_integrations/destinations/mongodb/README.md
  mage_integrations/mage_integrations/destinations/mongodb/__init__.py
  mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/sinks.py
  mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
  mage_integrations/mage_integrations/destinations/mongodb/templates/config.json
Labels: bug, python

#3397 [dy] Fix git commit from version control
  mage_ai/data_preparation/git/__init__.py
  mage_ai/frontend/components/VersionControl/GitFiles/index.tsx
Labels: bug

#3396 Enhancement: token expiry time env
  docs/development/environment-variables.mdx
  docs/production/authentication/overview.mdx
  mage_ai/api/resources/OauthResource.py
  mage_ai/authentication/oauth2.py
  mage_ai/settings/__init__.py
Labels: enhancement
