Repository mage-ai/mage-ai, pull requests merged in 2023-09, with the labels that each got.

#3406 [hw] Change the default search path to the schema given in the connection URL for PostgreSQL
  mage_ai/orchestration/db/__init__.py
Labels: bug

#3385 [dy] Raise exception if a pipeline has duplicate block uuids
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/tests/data_preparation/models/test_global_data_product.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
  mage_ai/tests/orchestration/triggers/test_global_data_product.py
  mage_ai/tests/orchestration/triggers/test_utils.py
Labels: bug

#3395 [jk] Auto-update triggers in code when making changes in UI
  docs/orchestration/triggers/configure-triggers-in-code.mdx
  mage_ai/api/resources/PipelineResource.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/tests/api/operations/test_pipeline_schedules.py
Labels: enhancement

#3407 Feat: Added Missing destination block warning
  mage_ai/data_integrations/utils/scheduler.py
Labels: feature, python

#3419 [xy] Fix creating subfolder when renaming block.
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#3417 Added disable schema creation config
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/mssql/README.md
  mage_integrations/mage_integrations/destinations/mysql/README.md
  mage_integrations/mage_integrations/destinations/postgresql/README.md
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/destinations/sql/base.py
Labels: bug, python

#3399 [dy] Add timeout for block runs and pipeline runs
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/executors/pipeline_executor.py
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/process.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: feature

#3409 [dy] Add fetch and reset to version control app
  mage_ai/api/policies/GitCustomBranchPolicy.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitCustomBranchResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/api.py
  mage_ai/data_preparation/sync/__init__.py
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/components/VersionControl/constants.ts
Labels: enhancement

#3418 [xy] Support ECS pipeline executor
  docs/production/configuring-production-settings/compute-resource.mdx
  mage_ai/data_preparation/executors/ecs_pipeline_executor.py
  mage_ai/data_preparation/executors/executor_factory.py
  mage_ai/data_preparation/executors/k8s_pipeline_executor.py
  mage_ai/data_preparation/executors/pipeline_executor.py
  mage_ai/orchestration/pipeline_scheduler.py
Labels: feature

#3423 [xy] Add Postgres sink to streaming pipeline
  docs/mint.json
  docs/streaming/destinations/postgres.mdx
  docs/streaming/overview.mdx
  mage_ai/data_preparation/templates/data_exporters/streaming/postgres.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/io/postgres.py
  mage_ai/streaming/constants.py
  mage_ai/streaming/sinks/elasticsearch.py
  mage_ai/streaming/sinks/mongodb.py
  mage_ai/streaming/sinks/opensearch.py
  mage_ai/streaming/sinks/postgres.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/tests/streaming/sinks/test_postgres.py
Labels: feature

#3422 [dy] Add support for key properties for postgresql destination
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/destinations/sql/utils.py
Labels: bug

#3412 Fix+Optimize pre-commit hook check-yaml and add check-json
  .pre-commit-config.yaml
  mage_integrations/mage_integrations/sources/commercetools/schemas/orders.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/adcreative.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_age_and_gender.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_country.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_dma.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_platform_and_device.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/ads_insights_region.json
  mage_integrations/mage_integrations/sources/facebook_ads/tap_facebook/schemas/shared/targeting.json
  mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/mailboxes.json
  mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/mailings.json
  mage_integrations/mage_integrations/sources/outreach/tap_outreach/schemas/teams.json
  mage_integrations/mage_integrations/sources/stripe/schemas/shared/charge.json
  mage_integrations/mage_integrations/sources/zendesk/tap_zendesk/schemas/tickets.json
Labels: enhancement

#3429 [td] Block layout app
  mage_ai/api/presenters/BlockLayoutItemPresenter.py
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/data_cleaner/analysis/charts.py
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/data_preparation/models/widget/charts.py
  mage_ai/data_preparation/models/widget/utils.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/BlockLayoutItemDetail/index.tsx
  mage_ai/frontend/components/BlockLayout/ChartConfigurations.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/ChartBlock/ChartController.tsx
  mage_ai/frontend/components/ChartBlock/index.tsx
  mage_ai/frontend/components/DataTable/index.tsx
  mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/interfaces/BlockLayoutItemType.ts
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/interfaces/PageBlockLayoutType.ts
  mage_ai/frontend/oracle/components/FlyoutMenu/FlyoutMenuWrapper.tsx
  mage_ai/frontend/pages/block-layout.tsx
  mage_ai/presenters/charts/data_sources/block.py
  mage_ai/shared/strings.py
Labels: feature

#3432 [mp] relative link hotfix
  docs/introduction/overview.mdx
Labels: documentation

#3427 [mp] consistently format API references
  docs/_snippets/overview-shields.mdx
  docs/api-reference/backfills/create-backfills.mdx
  docs/api-reference/backfills/delete-backfill.mdx
  docs/api-reference/backfills/overview.mdx
  docs/api-reference/backfills/read-backfills.mdx
  docs/api-reference/backfills/update-backfill.mdx
  docs/api-reference/blocks/overview.mdx
  docs/api-reference/logs/overview.mdx
  docs/api-reference/logs/read-logs.mdx
  docs/api-reference/oauth-access-tokens/overview.mdx
  docs/api-reference/pipeline-runs/overview.mdx
  docs/api-reference/pipeline-runs/read-pipeline-runs.mdx
  docs/api-reference/pipeline-runs/trigger-pipeline.mdx
  docs/api-reference/pipeline-schedules/overview.mdx
  docs/api-reference/pipeline-schedules/read-pipeline-schedules.mdx
  docs/api-reference/sessions/create-session.mdx
  docs/api-reference/sessions/overview.mdx
  docs/introduction/overview.mdx
Labels: documentation

#3424 [jk] Update Triggers list page with filters and clean up subheader
  docs/guides/blocks/dynamic-blocks.mdx
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/presenters/PipelineSchedulePresenter.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
  mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
  mage_ai/frontend/oracle/styles/colors/main.ts
  mage_ai/frontend/oracle/styles/themes/dark.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/orchestration/db/migrations/versions/117f8c3b9c42_add_description_to_pipeline_schedule.py
  mage_ai/orchestration/db/models/schedules.py
Labels: feature

#3413 Full Code Quality Check in Github Action Workflow "Build and Test"
  .github/workflows/build_and_test.yml
Labels: enhancement

#3428 [dy] Support custom logging level
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/logging/logger.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
  mage_ai/server/utils/output_display.py
Labels: feature, enhancement

#3437 [xy] Fix command on GCP cloud run.
  mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/services/gcp/cloud_run/cloud_run.py
Labels: bug

#3438 [td] Drag and drop block layout
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
Labels: enhancement

#3439 [td] Add block layout item in between others
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.style.tsx
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/LayoutDivider/index.style.tsx
  mage_ai/frontend/components/BlockLayout/LayoutDivider/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
Labels: enhancement

#3436 [dy] Fix git sync issues
  mage_ai/api/presenters/GitBranchPresenter.py
  mage_ai/api/presenters/GitCustomBranchPresenter.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitCustomBranchResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/preferences.py
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
Labels: bug

#3410 Docker: Lint Image and some best practices
  .github/workflows/lint_docker_image.yml
  Dockerfile
  dev.Dockerfile
Labels: enhancement

#3444 [jk] Remove unnecessary query from block runs request
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
Labels: bug

#3445 [dy] Remove legacy data cleaning code
  mage_ai/__init__.py
  mage_ai/data_cleaner/README.md
  mage_ai/server/app.py
Labels: dependencies

#3448 [dy] Fix aws secrets manager dependency issue
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/orchestration/db/setup.py
Labels: bug

#3440 [td] Add more data sources for block layout content
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/interfaces/BlockLayoutItemType.ts
  mage_ai/presenters/charts/data_sources/block_runs.py
  mage_ai/presenters/charts/data_sources/pipeline_runs.py
  mage_ai/presenters/charts/data_sources/pipeline_schedules.py
  mage_ai/presenters/charts/data_sources/pipelines.py
Labels: feature

#3447 [xy] Some improvements on executors
  docs/production/configuring-production-settings/compute-resource.mdx
  mage_ai/data_preparation/executors/executor_factory.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/services/aws/ecs/config.py
Labels: enhancement

#3411 Not always run Github Action Workflow "Build and Test"
  .github/workflows/build_and_test.yml
Labels: enhancement

#3452 [xy] Fix comparing bookmark value for timestamp col in BigQuery.
  mage_integrations/mage_integrations/sources/bigquery/__init__.py
  mage_integrations/mage_integrations/sources/sql/utils.py
Labels: bug

#3450 [td] Pipeline detail dashboard
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/PipelineDetailPage/constants.ts
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/charts/BarChartHorizontal.tsx
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/interfaces/PageBlockLayoutType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/dashboard.tsx
  mage_ai/presenters/block_layout/page.py
  mage_ai/presenters/charts/data_sources/block_runs.py
  mage_ai/presenters/charts/data_sources/pipeline_runs.py
  mage_ai/presenters/charts/data_sources/pipeline_schedules.py
  mage_ai/presenters/charts/data_sources/pipelines.py
Labels: feature

#3455 [jk] Hide OpenAI api key
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
Labels: enhancement

#3451 [jk] Add and update block variables through UI
  docs/development/variables/block-variables.mdx
  docs/mint.json
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/PipelineVariableType.ts
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: feature

#3457 [xy] Some improvements for streaming pipeline
  docs/streaming/destinations/postgres.mdx
  mage_ai/streaming/sinks/postgres.py
  mage_ai/streaming/sources/amazon_sqs.py
  mage_ai/tests/streaming/sinks/test_postgres.py
Labels: enhancement

#3458 [dy] Fix git issues
  .github/workflows/build_and_test.yml
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
  requirements.txt
Labels: bug

#3400 Added Docs for StrongDM support on Mage
  docs/integrations/strongdm.mdx
  scripts/strongdm/install.sh
Labels: documentation

#3464 [td] Add block layout to overview
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/Dashboard/constants.ts
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/dashboard.tsx
Labels: feature

#3466 [xy] Compare start_time and execution_date in should_schedule.
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: bug

#3468 [xy] Support auto scaling for EMR cluster.
  mage_ai/services/aws/emr/config.py
  mage_ai/services/aws/emr/emr.py
Labels: enhancement

#3456 [dy] Support github auth for different workspaces
  mage_ai/api/policies/OauthPolicy.py
  mage_ai/api/resources/OauthResource.py
  mage_ai/authentication/oauth/utils.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
Labels: enhancement

#3472 [jk] Fix initial ordering of pipeline rows
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#3465 Added Timestamp precision in Trino
  docs/guides/io_config.mdx
  docs/integrations/databases/trino.mdx
  mage_ai/io/trino.py
  mage_ai/shared/utils.py
  mage_ai/tests/io/test_export_utils.py
  mage_ai/tests/shared/test_utils.py
Labels: bug, python

#3476 Update README.md
  README.md
Labels: documentation

#3446 Added the Knowi Source
  docs/data-integrations/overview.mdx
  mage_ai/data_integrations/sources/constants.py
  mage_integrations/mage_integrations/sources/knowi/README.md
  mage_integrations/mage_integrations/sources/knowi/__init__.py
  mage_integrations/mage_integrations/sources/knowi/client.py
  mage_integrations/mage_integrations/sources/knowi/schema.py
  mage_integrations/mage_integrations/sources/knowi/schemas/dashboards.json
  mage_integrations/mage_integrations/sources/knowi/schemas/widgets.json
  mage_integrations/mage_integrations/sources/knowi/streams.py
  mage_integrations/mage_integrations/sources/knowi/templates/config.json
Labels: feature

#3477 [mp] Update pipeline overview screenshot
  README.md
  docs/development/text-editor.mdx
  media/data-pipeline-overview.jpg
  media/data-pipeline-overview.png
Labels: documentation

#3478 [dy] Run git sync on mage run
  mage_ai/cli/main.py
Labels: bug

#3480 [xy] Allow creating EMR with custom bootstrap script.
  mage_ai/cluster_manager/aws/emr_cluster_manager.py
  mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/services/aws/emr/config.py
  mage_ai/services/aws/emr/launcher.py
  mage_ai/services/aws/emr/resource_manager.py
Labels: enhancement

#3485 [dy] Add git sync on executor start env var
  mage_ai/cli/main.py
  mage_ai/data_preparation/preferences.py
  mage_ai/data_preparation/sync/__init__.py
Labels: enhancement

#3483 [mp] move influxdb docs and add to `mint.json`
  docs/mint.json
  docs/streaming/destinations/influxdb.mdx
Labels: documentation

#3484 [dy] Throw exception for ingress
  mage_ai/cluster_manager/kubernetes/workload_manager.py
Labels: bug

#3492 [jk] Only show Execute pipeline action for streaming pipelines
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
Labels: bug

#3503 [jk] Update terminal icon
  mage_ai/frontend/oracle/icons/index.tsx
Labels: enhancement

#3481 [jk] Local timezone setting
  mage_ai/api/resources/ProjectResource.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Edit/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/settings/workspace/utils.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/oracle/components/Calendar/index.tsx
  mage_ai/frontend/oracle/components/Calendar/utils.ts
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipeline-runs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/pages/triggers/index.tsx
  mage_ai/frontend/storage/constants.ts
  mage_ai/frontend/utils/date.ts
  mage_ai/frontend/utils/models/log.ts
Labels: feature

#3505 [jk] Use local time on Block runs page
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
Labels: enhancement

#3507 [dy] Only allow switching to local branches
  mage_ai/frontend/components/VersionControl/Branches/index.tsx
  mage_ai/orchestration/db/migrations/env.py
Labels: enhancement

#3495 [dy] Add checks for cwd in websocket server
  mage_ai/server/terminal_server.py
Labels: security

#3508 [td] Bug bash charts 2.0
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/widget/charts.py
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/ChartBlock/ChartController.tsx
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/presenters/charts/data_sources/block_runs.py
  mage_ai/presenters/charts/data_sources/constants.py
  mage_ai/presenters/charts/data_sources/pipeline_runs.py
  mage_ai/presenters/charts/data_sources/pipeline_schedules.py
  mage_ai/presenters/charts/data_sources/pipelines.py
  mage_ai/usage_statistics/constants.py
  mage_ai/usage_statistics/logger.py
  mage_ai/usage_statistics/utils.py
Labels: bug

#3473 [dy] Support custom logging level v2
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/logging/logger.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
  mage_ai/data_preparation/models/block/integration/__init__.py
  mage_ai/server/utils/output_display.py
Labels: enhancement

#3506 [xh]Update oracle discovery table
  mage_integrations/mage_integrations/sources/oracledb/__init__.py
Labels: bug

#3509 [jk] Show timezone in column header tooltip when displaying local time
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/shared/Table/constants.ts
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/utils/date.ts
  mage_integrations/mage_integrations/tests/sources/api/test_api.py
Labels: enhancement

#3510 Locking Polars version to 0.19.2
  mage_integrations/mage_integrations/tests/sources/api/test_api.py
  requirements.txt
Labels: bug, dependencies, python

#3463 [xh] Integrate DuckDB IO class and SQL block
  docs/integrations/databases/DuckDB.mdx
  mage_ai/api/resources/DataProviderResource.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/duckdb.py
  mage_ai/data_preparation/templates/repo/io_config.yaml
  mage_ai/io/base.py
  mage_ai/io/config.py
  mage_ai/io/duckdb.py
  mage_ai/io/io_config.py
  requirements.txt
  scripts/dev.sh
  setup.py
Labels: feature

#3513 [td] Support custom render function in charts
  docs/visualizations/dashboards.mdx
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/data_preparation/models/widget/__init__.py
  mage_ai/data_preparation/models/widget/constants.py
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/interfaces/BlockLayoutItemType.ts
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#3514 [xy] Fix zmq context destroy issue.
  mage_ai/api/presenters/KernelPresenter.py
Labels: bug

#3520 Fix: S3 path is joined using os.path.join -> Error non posix systems
  mage_ai/data_preparation/executors/pyspark_block_executor.py
  mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
  mage_ai/services/aws/emr/resource_manager.py
  mage_integrations/mage_integrations/destinations/delta_lake_s3/__init__.py
Labels: bug

#3528 [td] Add usage statistics for creating blocks, pipelines, and custom templates
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/CustomTemplateResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/CustomTemplates/PipelineTemplateDetail/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/usage_statistics/constants.py
  mage_ai/usage_statistics/logger.py
Labels: enhancement

#3430 Influxdb data loader
  docs/streaming/sources/influxdb.mdx
  mage_ai/data_preparation/templates/data_loaders/streaming/influxdb.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/constants.py
  mage_ai/streaming/sources/influxdb.py
  mage_ai/streaming/sources/source_factory.py
  mage_ai/tests/streaming/sources/test_influxdb.py
Labels: feature

#3531 [td] Update block catalog via API
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/data_preparation/models/pipeline.py
Labels: feature

#3534 [td] Fix raw SQL alias
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/tests/data_preparation/models/block/sql/__init__.py
  mage_ai/tests/data_preparation/models/block/sql/utils/__init__.py
  mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py
Labels: bug

#3532 [xy] Support multiple kafka topics in kafka source
  docs/streaming/destinations/kafka.mdx
  docs/streaming/sources/kafka.mdx
  mage_ai/streaming/sinks/kafka.py
  mage_ai/streaming/sources/kafka.py
  mage_ai/tests/streaming/sources/test_kafka.py
Labels: enhancement

#3498 [dy] Fix how table name is parsed for sql blocks
  mage_ai/data_preparation/models/block/sql/utils/shared.py
Labels: bug

#3530 Support trailing slash when base path set
  mage_ai/server/server.py
Labels: enhancement

#3522 Fix: dtype int is not always casted as int64
  mage_ai/data_cleaner/column_types/column_type_detector.py
  mage_ai/data_cleaner/shared/utils.py
  mage_ai/data_preparation/models/widget/utils.py
  mage_ai/tests/data_cleaner/statistics/test_calculator.py
  mage_ai/tests/data_cleaner/transformer_actions/test_column.py
  mage_ai/tests/data_cleaner/transformer_actions/test_custom_actions.py
  mage_ai/tests/data_cleaner/transformer_actions/test_row.py
Labels: bug

#3537 [dy] Fix git authentication issue
  mage_ai/api/resources/OauthResource.py
  mage_ai/data_preparation/git/api.py
  mage_ai/tests/data_preparation/git/test_api.py
Labels: bug

#3539 [td] Handle source block execution
  mage_ai/data_integrations/utils/config.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/__init__.py
  mage_ai/data_preparation/models/block/data_integration/constants.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/integration/__init__.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/storage/base_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/api/utils/use.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: feature

#3542 [td] Convert source output data from Singer to DataFrame
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/constants.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
Labels: feature

#3543 [td] Fix overwriting runtime variables for dbt block
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
Labels: bug

#3540 [dy] Update docs
  docs/development/observability/logging.mdx
  docs/production/data-sync/git.mdx
Labels: documentation

#3547 [xy] Not concat pandas dataframes when not reducing dynamic blocks.
  mage_ai/data_preparation/models/block/utils.py
Labels: bug

#3548 [jk] Upgrade Storybook
  .circleci/config.yml
  .github/workflows/build_and_test.yml
  mage_ai/frontend/.eslintrc.js
  mage_ai/frontend/.storybook/main.js
  mage_ai/frontend/package.json
  mage_ai/frontend/yarn.lock
Labels: dependencies

#3549 [xy] Update Mage spark dockerfile.
  integrations/spark/Dockerfile
Labels: bug

#3550 [jk] Display warning on demo site to prevent users from entering private credentials.
  mage_ai/frontend/oracle/components/Banner/index.style.ts
  mage_ai/frontend/oracle/components/Banner/index.tsx
  mage_ai/frontend/oracle/styles/units/borders.ts
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/storage/constants.ts
Labels: enhancement

#3552 [jk] Add doc for local timezone setting
  docs/development/project/local-timezone.mdx
  docs/mint.json
Labels: documentation

#3545 [td] Handle input data from upstream for source block and support custom decorators
  docker-compose.yml
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/utils/code.py
Labels: feature

#3557 [jk] Update wording for empty pipeline template state
  mage_ai/frontend/components/CustomTemplates/BrowseTemplates/index.tsx
Labels: enhancement

#3554 [td] Fan out source block runs
  mage_ai/api/resources/BlockRunResource.py
  mage_ai/api/resources/SearchResultResource.py
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
Labels: feature

#3541 [jk] Reorder upstream blocks
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/tests/data_preparation/models/test_block.py
Labels: enhancement

#3561 [jk] Support local timezone for cron expressions
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/utils/date.ts
Labels: bug

#3562 [xy] Prioritize using remote_variables_dir for variable manager.
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/templates/main/metadata.yaml
  mage_ai/data_preparation/templates/repo/metadata.yaml
Labels: enhancement

#3563 [td] Show dynamic block nodes in tree
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
Labels: feature

#3560 fix: have api middlware set status codes if api key or oauth token error
  mage_ai/api/middleware.py
Labels: bug

#3568 [td] If run in parallel is not on, sequentially run streams
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/BlockRunResource.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
Labels: feature, enhancement

#3569 [mp] Migrate FAQ page off of notion
  README.md
  docs/about/frequently-asked-questions.mdx
  docs/development/git/generate-an-ssh-token.mdx
  docs/development/troubleshooting.mdx
  docs/media/notion-faq.png
  docs/mint.json
Labels: documentation

#3572 [td] Run batches in a single stream sequentially
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/usage_statistics/logger.py
Labels: feature

#3558 [dy] Customize ecs config
  mage_ai/shared/config.py
Labels: enhancement

#3570 [dy] Fix postgres db connection url parsing
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/models/utils.py
  mage_ai/orchestration/db/utils.py
  mage_ai/tests/orchestration/db/test_utils.py
Labels: bug

#3556 [mp] git sync docs + tips & tricks page + update mage page
  docs/about/releases.mdx
  docs/development/git/generate-an-ssh-token.mdx
  docs/development/updating-mage.mdx
  docs/getting-started/file-versions.mdx
  docs/getting-started/setting-up-git.mdx
  docs/getting-started/setup.mdx
  docs/guides/data-integration-pipeline.mdx
  docs/guides/integrate-mage-airflow.mdx
  docs/guides/load-api-data.mdx
  docs/guides/tips-and-tricks.mdx
  docs/introduction/overview.mdx
  docs/media/getting-started/adventure-time.gif
  docs/media/getting-started/git-overview.png
  docs/mint.json
  docs/production/data-sync/git.mdx
  docs/production/data-sync/github.mdx
Labels: documentation

#3553 [xh] Add DuckDB loader and exporter
  docs/design/data-loading.mdx
  mage_ai/data_preparation/templates/constants.py
  mage_ai/data_preparation/templates/data_exporters/duckdb.py
  mage_ai/data_preparation/templates/data_loaders/duckdb.py
  mage_ai/io/duckdb.py
Labels: feature

#3576 [jk] Bookmark values minor improvements
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
Labels: enhancement

#3571 [dy] Fix passing in logger for alternative block execution methods
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/server/utils/output_display.py
Labels: bug

#3497 Streamline DBT block
  .github/workflows/build_and_test.yml
  docs/dbt/docs.mdx
  docs/dbt/sources.mdx
  docs/dbt/variable-interpolation.mdx
  docs/guides/setup-dbt.mdx
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/constants.py
  mage_ai/data_preparation/models/block/dbt/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
  mage_ai/data_preparation/models/block/dbt/dbt_adapter.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  mage_ai/data_preparation/models/block/dbt/profiles.py
  mage_ai/data_preparation/models/block/dbt/project.py
  mage_ai/data_preparation/models/block/dbt/sources.py
  mage_ai/data_preparation/models/block/dbt/utils/__init__.py
  mage_ai/data_preparation/models/block/sql/bigquery.py
  mage_ai/data_preparation/models/block/sql/snowflake.py
  mage_ai/data_preparation/models/block/sql/trino.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/templates/repo/dbt/profiles.yml
  mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/tests/base_test.py
  mage_ai/tests/data_preparation/models/block/dbt/__init__.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_adapter.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_cli.py
  mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py
  mage_ai/tests/data_preparation/models/block/dbt/test_project.py
  mage_ai/tests/data_preparation/models/block/dbt/test_sources.py
  requirements.txt
  setup.py
Labels: feature

#3578 [xy] Fix variables interpolation in dbt target.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
Labels: bug

#3579 [td] Fixed dbt seed requiring variables
  mage_ai/data_preparation/models/block/dbt/block.py
Labels: bug

#3580 [td] Support Python destination blocks
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/schema.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/frontend/components/Logs/Table/index.tsx
  mage_ai/server/websocket_server.py
  mage_ai/shared/environments.py
Labels: feature

#3584 [td] Renaming block will move the catalog.json and all other files
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
Labels: enhancement

#3585 [td] Fix getting catalog from upstream for destination
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
Labels: bug

#3586 [td] Add source blocks
  mage_ai/api/presenters/BlockTemplatePresenter.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/BlockTemplateResource.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/cache/block_action_object/__init__.py
  mage_ai/data_preparation/templates/data_integrations/__init__.py
  mage_ai/data_preparation/templates/data_integrations/constants.py
  mage_ai/data_preparation/templates/data_integrations/destinations/__init__.py
  mage_ai/data_preparation/templates/data_integrations/destinations/base.py
  mage_ai/data_preparation/templates/data_integrations/destinations/base.yaml
  mage_ai/data_preparation/templates/data_integrations/sources/__init__.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.yaml
  mage_ai/data_preparation/templates/data_integrations/utils.py
  mage_ai/data_preparation/templates/template.py
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/interfaces/BlockTemplateType.ts
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/interfaces/DataIntegrationBlockType.ts
  mage_ai/server/api/integration_sources.py
  mage_integrations/mage_integrations/sources/github/tap_github/__init__.py
  mage_integrations/mage_integrations/sources/github/tap_github/discover.py
  mage_integrations/mage_integrations/sources/github/tap_github/schema.py
  mage_integrations/mage_integrations/sources/github/tap_github/sync.py
Labels: feature

#3588 [xy] Fix writing dataframe to s3 storage.
  mage_ai/data_preparation/models/variable.py
Labels: bug

#3590 [xy] Speed up bigquery destination in data integration pipeline.
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/destinations/bigquery/utils.py
  mage_integrations/mage_integrations/destinations/sql/base.py
  mage_integrations/mage_integrations/destinations/sql/utils.py
  mage_integrations/mage_integrations/tests/destinations/test_base.py
Labels: enhancement

#3555 Allow declared cookies to propagate to resources
  mage_ai/api/operations/base.py
  mage_ai/api/operations/constants.py
  mage_ai/api/resources/BaseResource.py
Labels: enhancement

#3358 [xh] Refactor: use generic function to call LLM avoid code duplication
  mage_ai/ai/generator.py
  mage_ai/ai/generator_cmds.py
  mage_ai/ai/llm_pipeline_wizard.py
Labels: enhancement

#3596 [jk] Fix updating of pipelineRowsSorted when clearing search query
  mage_ai/frontend/components/shared/Table/index.style.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#3592 [xy] Allow configuring EMR cluster spark properties
  mage_ai/services/aws/emr/config.py
Labels: enhancement

#3538 [mp] connect a local docker db
  docs/design/abstractions/project-structure.mdx
  docs/development/io_config.mdx
  docs/getting-started/setup.mdx
  docs/guides/docker/connecting-a-database.mdx
  docs/mint.json
Labels: documentation

#3598 [dy] Check yaml serialization before writing variable
  mage_ai/data_preparation/models/errors.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/utils.py
Labels: bug

#3597 WIP: Feat/gcs storage
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/shared/constants.py
  mage_ai/shared/urls.py
  mage_ai/tests/data_preparation/storage/test_gcs_storage.py
Labels: feature

#3593 [dy] Sync git submodules
  mage_ai/api/presenters/SyncPresenter.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/sync/__init__.py
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/frontend/interfaces/SyncType.ts
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
Labels: feature

#3600 [xy] Update docs for variable storage and emr config.
  docs/design/data-pipeline-management.mdx
  docs/integrations/spark-pyspark.mdx
  mage_ai/data_preparation/models/variable.py
Labels: documentation

#3594 [jk] Bulk retry incomplete block runs
  mage_ai/api/resources/PipelineResource.py
  mage_ai/frontend/components/PipelineDetailPage/constants.ts
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/constants.ts
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/orchestration/db/models/schedules.py
Labels: feature

#3601 [xy] Fix mint.json
  docs/mint.json
Labels: documentation

#3602 [dy] Update git docs
  docs/getting-started/setting-up-git.mdx
  docs/mint.json
  docs/production/data-sync/git-integration.mdx
  docs/production/data-sync/git-sync.mdx
  docs/production/data-sync/git.mdx
  mage_ai/frontend/interfaces/SyncType.ts
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
Labels: documentation

#3608 [xy] Lazy import dbt block and library
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/constants.py
  mage_ai/data_preparation/models/pipeline.py
Labels: bug

#3479 Fix invalid keyword argument error when requesting a list from Stripe
  mage_integrations/mage_integrations/sources/stripe/__init__.py
Labels: bug

#3612 [xy] Fix snowflake output column names.
  mage_ai/io/snowflake.py
Labels: bug

#3613 [jk] Add sortable block run columns
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
Labels: enhancement

#3614 [td] Fix charts when trying to change name
  mage_ai/frontend/components/BlockLayout/index.tsx
Labels: bug

#3615 [jk] Clarify components based on UTC time in Overview page
  mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/PipelineRun/shared/constants.ts
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/pages/overview/index.tsx
Labels: enhancement

#3616 [xy] Support interpolating pipeline variables in streaming configs.
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/models/pipeline.py
Labels: enhancement

#3619 [td] Fix export_batch_data not accepting tags as a kwarg
  mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/destinations/delta_lake/base.py
  mage_integrations/mage_integrations/destinations/google_cloud_storage/__init__.py
Labels: bug

#3589 [td] Configure data integration from modal
  mage_ai/api/policies/BlockPolicy.py
  mage_ai/api/policies/IntegrationSourcePolicy.py
  mage_ai/api/policies/OutputPolicy.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/presenters/IntegrationSourcePresenter.py
  mage_ai/api/presenters/OutputPresenter.py
  mage_ai/api/resources/IntegrationSourceResource.py
  mage_ai/api/resources/OutputResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/schema.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/integration/__init__.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/templates/data_integrations/utils.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/Breadcrumbs/index.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/Credentials.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/SampleData.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailSchemaProperties.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/index.style.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamGrid.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamOverviewEditor.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamSchemaPropertiesEditor/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamSettingsEditorTable.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamTableSelector.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/index.style.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/interfaces/ErrorsType.ts
  mage_ai/frontend/interfaces/IntegrationSourceType.ts
  mage_ai/frontend/interfaces/OutputType.ts
  mage_ai/frontend/oracle/components/Chip/index.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/oracle/elements/Circle.tsx
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/oracle/elements/Inputs/Select.tsx
  mage_ai/frontend/oracle/elements/Inputs/TextArea.tsx
  mage_ai/frontend/oracle/elements/Inputs/TextInput.tsx
  mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/test.tsx
  mage_ai/frontend/utils/array.ts
  mage_ai/frontend/utils/models/block.ts
  mage_ai/frontend/utils/string.ts
Labels: feature

#3621 [dy] Handle secret key and uuid whitespace
  mage_ai/data_preparation/shared/secrets.py
  mage_ai/orchestration/db/models/secrets.py
  mage_ai/tests/data_preparation/shared/test_secrets.py
Labels: bug

#3623 [xy] Improve streaming base class and add sink for all io databases
  docs/mint.json
  docs/streaming/destinations/bigquery.mdx
  docs/streaming/destinations/clickhouse.mdx
  docs/streaming/destinations/duckdb.mdx
  docs/streaming/destinations/mssql.mdx
  docs/streaming/destinations/mysql.mdx
  docs/streaming/destinations/redshift.mdx
  docs/streaming/destinations/snowflake.mdx
  docs/streaming/destinations/trino.mdx
  docs/streaming/overview.mdx
  mage_ai/api/operations/base.py
  mage_ai/data_preparation/templates/data_exporters/streaming/bigquery.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/clickhouse.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/duckdb.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/mssql.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/mysql.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/redshift.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/snowflake.yaml
  mage_ai/data_preparation/templates/data_exporters/streaming/trino.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/interfaces/DataSourceType.ts
  mage_ai/io/bigquery.py
  mage_ai/io/clickhouse.py
  mage_ai/io/mysql.py
  mage_ai/io/redshift.py
  mage_ai/io/snowflake.py
  mage_ai/io/sql.py
  mage_ai/io/trino.py
  mage_ai/shared/strings.py
  mage_ai/streaming/constants.py
  mage_ai/streaming/sinks/amazon_s3.py
  mage_ai/streaming/sinks/azure_data_lake.py
  mage_ai/streaming/sinks/base.py
  mage_ai/streaming/sinks/dummy.py
  mage_ai/streaming/sinks/elasticsearch.py
  mage_ai/streaming/sinks/generic_io.py
  mage_ai/streaming/sinks/kinesis.py
  mage_ai/streaming/sinks/mongodb.py
  mage_ai/streaming/sinks/opensearch.py
  mage_ai/streaming/sinks/postgres.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/streaming/sources/base.py
  mage_ai/tests/streaming/sinks/test_generic_io.py
Labels: feature

#3591 Scheduler trigger interval as environment variable setting
  docker-compose.yml
  mage_ai/orchestration/triggers/loop_time_trigger.py
  mage_ai/orchestration/triggers/time_trigger.py
  mage_ai/settings/__init__.py
Labels: enhancement

#3627 [td] Enhance Python data integration block UI
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/constants.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/templates/data_integrations/destinations/base.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/CodeBlock/BlockExtras/index.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/DataIntegrationModal/Credentials/InputsTable.tsx
  mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/SampleData.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/interfaces/ChartBlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/utils/hash.ts
  mage_ai/frontend/utils/models/block.ts
Labels: enhancement

#3626 [dy] Add sync submodules environment variable
  docs/production/data-sync/git-sync.mdx
  mage_ai/data_preparation/preferences.py
Labels: enhancement

#3617 Fix materializing upstream outputs for dbt
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#3629 [jk] Pipeline runs table (for individual pipelines) updates
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/constants.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/interfaces/PipelineRunType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: enhancement

#3511 [mp] New dbt quickstart
  docs/guides/dbt/developing-dbt-in-mage.mdx
  docs/guides/setup-dbt.mdx
  docs/mint.json
Labels: documentation

#3628 [td] Warn user about code overriding catalog
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/templates/data_integrations/destinations/base.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.py
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailSchemaProperties.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamGrid.tsx
  mage_ai/frontend/components/DataIntegrationModal/constants.ts
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/utils/models/block.ts
Labels: enhancement

#3632 [td] Fix bugs from bug bash
  mage_ai/api/presenters/BlockTemplatePresenter.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/templates/data_integrations/utils.py
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/interfaces/BlockTemplateType.ts
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#3633 [td] Show recently viewed pipelines
  mage_ai/api/operations/constants.py
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/authentication/operation_history/__init__.py
  mage_ai/authentication/operation_history/constants.py
  mage_ai/authentication/operation_history/models.py
  mage_ai/authentication/operation_history/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/data_preparation/storage/base_storage.py
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/storage/s3_storage.py
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/storage/pipelines.ts
  mage_ai/shared/io.py
Labels: feature
