Repository mage-ai/mage-ai, pull requests merged in 2023-11, with the labels that each got.

#3880 [xy] Allow sending emails without TLS
  mage_ai/services/email/config.py
  mage_ai/services/email/email.py
  mage_ai/tests/services/email/__init__.py
  mage_ai/tests/services/email/test_email.py
Labels: enhancement

#3535 Customize k8s executor
  docs/production/configuring-production-settings/compute-resource.mdx
  mage_ai/services/k8s/config.py
  mage_ai/services/k8s/constants.py
  mage_ai/services/k8s/job_manager.py
  mage_ai/shared/config.py
  mage_ai/shared/hash.py
  mage_ai/tests/services/k8s/test_config.py
  mage_ai/tests/services/k8s/test_job_manager.py
Labels: enhancement

#3881 [xy] Fix memory leak and warning.
  mage_ai/data_preparation/logging/logger_manager.py
  mage_ai/orchestration/db/migrations/versions/90d978a8aef8_update_unique_constraint_for_secret.py
  mage_ai/orchestration/utils/resources.py
Labels: bug

#3887 [Documentation] Add correct types of blocks in core-abstractions.mdx
  docs/design/core-abstractions.mdx
Labels: documentation

#3870 [jk] Revert pipeline type when error occurs switching type
  mage_ai/api/resources/PipelineResource.py
Labels: bug

#3867 [jk] Add "No tags" filtering option for pipelines
  mage_ai/api/resources/PipelineResource.py
  mage_ai/cache/tag.py
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#3892 [Bugfix] Update druid.py to have correct method name
  mage_ai/data_preparation/templates/data_loaders/druid.py
Labels: bug

#3897 [td] Address PR comments on Tree v2 PR
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/DependencyGraph/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/DependencyGraph/utils.ts
Labels: enhancement

#3818 [xh]Add test functions for AI class
  .github/workflows/build_and_test.yml
  mage_ai/ai/llm_pipeline_wizard.py
  mage_ai/tests/ai/__init__.py
  mage_ai/tests/ai/test_ai_functions.py
  requirements.txt
  setup.py
Labels: feature

#3889 [ac] Add keyboard shortcuts for inserting new scratchpad cell
  mage_ai/frontend/components/CodeEditor/index.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/context/shared/utils.ts
Labels: enhancement

#3828 [mp] Add Google Sheets IO Class
  mage_ai/data_preparation/templates/constants.py
  mage_ai/data_preparation/templates/data_exporters/google_sheets.py
  mage_ai/data_preparation/templates/data_loaders/google_sheets.py
  mage_ai/data_preparation/templates/repo/data_loaders/load_titanic.py
  mage_ai/frontend/interfaces/DataSourceType.ts
  mage_ai/io/base.py
  mage_ai/io/google_sheets.py
  requirements.txt
  setup.py
Labels: feature

#3901 [dy] Fix sftp client side exception
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/utils/models/block.ts
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/client.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/singer_encodings/json_schema.py
Labels: bug

#3894 [xy] Fix EMR Spark pipeline issues.
  mage_ai/api/presenters/KernelPresenter.py
  mage_ai/cluster_manager/aws/emr_cluster_manager.py
  mage_ai/data_preparation/executors/pyspark_block_executor.py
  mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/templates/pipeline_execution/spark_script.jinja
  mage_ai/services/aws/emr/config.py
  mage_ai/services/aws/emr/emr.py
  setup.py
Labels: bug

#3903 [xy] Fix pipeline LIST API performance.
  mage_ai/data_preparation/models/block/integration/__init__.py
Labels: bug

#3907 [Doc] Improvements to development environment doc
  docs/contributing/development-environment.mdx
Labels: documentation

#3908 [td] Fix JSON serializing Timestamp when exporting to BigQuery
  mage_ai/data_preparation/models/block/data_integration/data.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/index.style.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
Labels: bug

#3909 [xy] Speed up Pipeline UPDATE API.
  mage_ai/data_preparation/models/pipeline.py
Labels: enhancement

#3902 [mp] Update SSH Key link
  docs/production/data-sync/git-integration.mdx
Labels: documentation

#3912 [xy] Restrict the version of openai.
  requirements.txt
  setup.py
Labels: bug

#3850 [xh] HuggingFace AI Client
  docker-compose.yml
  mage_ai/ai/ai_client.py
  mage_ai/ai/hugging_face_client.py
  mage_ai/ai/llm_pipeline_wizard.py
  mage_ai/ai/openai_client.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/orchestration/ai/__init__.py
  mage_ai/orchestration/ai/config.py
  mage_ai/tests/ai/test_ai_functions.py
  scripts/dev.sh
Labels: feature

#3925 [xy] Remove libkrb5-dev from build_and_test.yml
  .github/workflows/build_and_test.yml
Labels: bug

#3922 [xy] Support pipeline level emr config.
  mage_ai/api/resources/PipelineResource.py
  mage_ai/cluster_manager/aws/emr_cluster_manager.py
  mage_ai/data_preparation/executors/pyspark_block_executor.py
  mage_ai/data_preparation/executors/pyspark_pipeline_executor.py
  mage_ai/server/active_kernel.py
  mage_ai/services/aws/emr/emr.py
  mage_ai/services/aws/emr/launcher.py
Labels: enhancement

#3923 Bump Releases
  docs/about/releases.mdx
Labels: documentation

#3917 [td] Inject global and pipeline variables in the keyword arguments for extension blocks
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/extension/block.py
  mage_ai/data_preparation/models/block/extension/utils.py
Labels: bug

#3835 Fixed stripe INCREMENTAL run and updated tap
  mage_integrations/mage_integrations/sources/stripe/__init__.py
  mage_integrations/mage_integrations/sources/stripe/schemas/invoices.json
  mage_integrations/mage_integrations/sources/stripe/schemas/payment_intents.json
  mage_integrations/mage_integrations/sources/stripe/schemas/shared/charge.json
  mage_integrations/requirements.txt
Labels: bug, python, data integration

#3926 [ac] Add keyboard shortcuts for inserting new scratchpad cell
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/context/shared/utils.ts
Labels: feature

#3904 [Feat] Add colour code for pipeline backfills
  mage_ai/frontend/components/Backfills/Table/index.tsx
Labels: enhancement

#3933 [jk] Break while loop when not raising error on failure for pipeline triggered by code
  mage_ai/orchestration/triggers/utils.py
Labels: bug

#3899 [ac] Show dependency graph zoom options
  mage_ai/frontend/components/DependencyGraph/ZoomControls/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/ZoomControls/index.tsx
  mage_ai/frontend/components/DependencyGraph/constants.ts
  mage_ai/frontend/components/DependencyGraph/index.style.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/Logs/Toolbar/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/ServerTimeDropdown/ServerTimeButton.tsx
  mage_ai/frontend/components/Sidekick/Header.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/manage/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: enhancement

#3872 [dy] Update how global data products are run
  mage_ai/orchestration/triggers/global_data_product.py
  mage_ai/tests/orchestration/triggers/test_global_data_product.py
Labels: enhancement

#3940 [jk] Consistent run status colors across tables
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/shared/Table/constants.ts
Labels: enhancement

#3941 [td] Make 2nd argument of lambda function optional
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/presenters/interactions/utils.py
Labels: bug

#3935 [dy] Update git settings permissions
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
Labels: bug

#3931 [dy] Misc workspace changes
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/frontend/components/workspaces/Dashboard/constants.ts
Labels: bug

#3944 [xy] Fix MongoDB destination and add unit test
  mage_integrations/mage_integrations/destinations/base.py
  mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
  mage_integrations/mage_integrations/tests/destinations/mongodb/__init__.py
  mage_integrations/mage_integrations/tests/destinations/mongodb/test_mongodb.py
  mage_integrations/mage_integrations/tests/destinations/test_base.py
Labels: bug

#3910 observability: add prometheus metrics
  docker-compose.yml
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  requirements.txt
  scripts/dev.sh
Labels: feature

#3949 [xy] Allow getting instance type from environment variable.
  mage_ai/cli/main.py
  mage_ai/server/server.py
  mage_ai/shared/constants.py
Labels: enhancement

#3951 [xy] Fix sql destination reserved words.
  mage_integrations/mage_integrations/destinations/sql/base.py
Labels: bug

#3945 [td] Interpolate variables and upstream block output in dbt commands
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
Labels: enhancement

#3955 [td] Fix notebook block ordering for upstream blocks
  mage_ai/frontend/components/CodeBlock/constants.ts
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/Interactions/BlockInteractionController.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/utils/array.ts
Labels: bug

#3956 [td] Document how to interpolate data into dbt generic command
  docs/dbt/run-selected-model.mdx
Labels: documentation

#3961 [xy] Fix unit tests warnings and errors
  mage_ai/tests/base_test.py
  mage_ai/tests/data_preparation/test_repo_manager.py
Labels: bug

#3968 [xy] Clean column name when using batch load in Snowflake destination.
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/tests/sources/api/test_api.py
Labels: bug

#3959 [dy] Update duckdb version
  mage_ai/io/duckdb.py
  requirements.txt
  setup.py
Labels: enhancement

#3963 [jk] Update backfill variables
  mage_ai/api/resources/BackfillResource.py
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Edit/index.tsx
  mage_ai/frontend/components/Sidekick/utils.ts
  mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
  mage_ai/frontend/components/Triggers/RunPipelinePopup/index.style.ts
  mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/utils/hash.ts
Labels: enhancement

#3965 [xh]Fix doc link reference
  docs/guides/ai/ai-client.mdx
Labels: bug

#3921 [dy] Add sso/oauth providers
  mage_ai/api/policies/OauthPolicy.py
  mage_ai/api/presenters/OauthPresenter.py
  mage_ai/api/resources/OauthResource.py
  mage_ai/api/resources/SessionResource.py
  mage_ai/authentication/oauth/constants.py
  mage_ai/authentication/providers/__init__.py
  mage_ai/authentication/providers/constants.py
  mage_ai/authentication/providers/ghe.py
  mage_ai/authentication/providers/google.py
  mage_ai/authentication/providers/oauth.py
  mage_ai/authentication/providers/okta.py
  mage_ai/authentication/providers/sso.py
  mage_ai/authentication/providers/utils.py
  mage_ai/frontend/components/Sessions/GoogleSignIn.tsx
  mage_ai/frontend/components/Sessions/OktaSignIn.tsx
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/interfaces/OauthType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/pages/oauth.tsx
  mage_ai/settings/__init__.py
  mage_ai/settings/sso.py
Labels: feature

#3969 [xy] Serialize Snowflake dataframe dict column to json if column type is string
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
Labels: bug

#3932 Added Delta Lake ( Azure ) Destination
  docs/data-integrations/overview.mdx
  mage_ai/data_integrations/destinations/constants.py
  mage_integrations/mage_integrations/destinations/delta_lake_azure/README.md
  mage_integrations/mage_integrations/destinations/delta_lake_azure/__init__.py
  mage_integrations/mage_integrations/destinations/delta_lake_azure/templates/config.json
Labels: python, data integration

#3973 [jk] Always show "Overwrite global variables" setting when editing a trigger
  .github/pull_request_template.md
  mage_ai/frontend/components/Triggers/Edit/index.tsx
Labels: enhancement

#3868 [dy] Add pipeline run limit for a pipeline
  mage_ai/orchestration/concurrency.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/triggers/utils.py
  mage_ai/server/api/triggers.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: enhancement

#3953 [xy] Move dbt seed logic to downstream block.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/utils.py
Labels: bug

#3950 [mp] update tips & tricks
  docs/guides/tips-and-tricks.mdx
Labels: documentation

#3974 [dy] Use personal access token if available
  mage_ai/api/policies/GitCustomBranchPolicy.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitCustomBranchResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/api.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/interfaces/GitBranchType.ts
Labels: enhancement

#3952 [dy] Add exception failure message in callbacks
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/templates/callbacks/base.jinja
  mage_ai/shared/hash.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
Labels: enhancement

#3927 [mp] update/clean-up git instructions
  README.md
  docs/_snippets/configure-git-sync.mdx
  docs/_snippets/test-connection.mdx
  docs/about/frequently-asked-questions.mdx
  docs/contributing/data-integrations/adapt-existing-source.mdx
  docs/contributing/data-integrations/add-new-source.mdx
  docs/development/git/configure.mdx
  docs/development/git/generate-an-ssh-token.mdx
  docs/getting-started/setting-up-git.mdx
  docs/mint.json
  docs/production/ci-cd/staging-production/github-actions.mdx
  docs/production/configuring-production-settings/overview.mdx
  docs/production/data-sync/git-integration.mdx
  docs/production/data-sync/git-sync.mdx
  docs/production/data-sync/github.mdx
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
  mage_ai/server/frontend_dist/_next/static/chunks/pages/settings/workspace/sync-data-88d41c33b8fcb300.js
  mage_ai/server/frontend_dist_base_path_template/_next/static/chunks/pages/settings/workspace/sync-data-88d41c33b8fcb300.js
  mage_integrations/README.md
  mage_integrations/mage_integrations/connections/google_analytics/README.md
  mage_integrations/mage_integrations/sources/github/README.md
Labels: documentation

#3980 [jk] Fix project dashboard overview count formatting
  mage_ai/frontend/components/PipelineRun/MetricsSummary/index.style.ts
  mage_ai/frontend/components/PipelineRun/MetricsSummary/index.tsx
  mage_ai/frontend/components/charts/BarStack.tsx
  mage_ai/frontend/components/charts/utils/label.ts
  mage_ai/frontend/components/shared/Grid/Col.tsx
  mage_ai/frontend/components/shared/Grid/Row.tsx
  mage_ai/frontend/pages/overview/index.tsx
Labels: bug

#3981 [dy] Fix pipeline scheduler for integration pipelines
  .github/workflows/build_and_test.yml
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
  mage_ai/tests/test_data_integration_catalog.json
Labels: bug

#3982 [dy] Fix roles getting overwritten when updating profile
  mage_ai/api/policies/RolePolicy.py
  mage_ai/api/resources/UserResource.py
Labels: bug

#3911 [mp] Contributing IO Class / Google Sheets Docs
  docs/_snippets/contribution-process.mdx
  docs/_snippets/debugging-backend.mdx
  docs/_snippets/google-auth.mdx
  docs/contributing/backend/io/adding-a-class.mdx
  docs/contributing/backend/overview.mdx
  docs/contributing/development-environment.mdx
  docs/contributing/documentation/overview.mdx
  docs/contributing/overview.mdx
  docs/design/data-loading.mdx
  docs/integrations/databases/BigQuery.mdx
  docs/integrations/databases/GoogleSheets.mdx
  docs/mint.json
Labels: documentation

#3986 [td] Fix tree for data integration pipeline
  mage_ai/api/resources/BlockResource.py
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/DependencyGraph/utils.ts
Labels: bug

#3993 [xy] Add pyarrow-hotfix to requirements.txt
  requirements.txt
Labels: bug

#3990 Added application/gzip support to API source
  mage_integrations/mage_integrations/sources/api/__init__.py
Labels: feature, python, data integration

#3992 [dy] Fix workspace user management fetching
  mage_ai/api/presenters/WorkspacePresenter.py
  mage_ai/cluster_manager/workspace/base.py
  mage_ai/tests/api/endpoints/test_workspaces.py
Labels: bug

#3995 [dy] Add sso docs
  docs/mint.json
  docs/production/authentication/google.mdx
  docs/production/authentication/okta.mdx
Labels: documentation

#3996 [xy] Re-enqueue the job if queue is empty.
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/tests/orchestration/queue/test_process_queue.py
Labels: enhancement

#3813 Download functionality for files and pipelines
  docs/development/variables/environment-variables.mdx
  mage_ai/api/constants.py
  mage_ai/api/policies/DownloadPolicy.py
  mage_ai/api/presenters/DownloadPresenter.py
  mage_ai/api/resources/DownloadResource.py
  mage_ai/authentication/oauth2.py
  mage_ai/data_preparation/models/download/__init__.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/utils/downloads.ts
  mage_ai/server/api/downloads.py
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  mage_ai/settings/secret_generation.py
Labels: feature

#3991 prometheus: add documentation
  docs/integrations/observability/prometheus.mdx
  docs/mint.json
Labels: documentation

#4005 [td] Handle hidden block positions when split view
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlocksInPipeline/index.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
  mage_ai/frontend/components/PipelineDetail/constants.ts
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4004 [td] Add unit test to test user list response for admins
  mage_ai/tests/api/operations/test_base.py
  mage_ai/tests/api/operations/test_users.py
Labels: security

#4006 [td] Don’t show SSH tunnel option unless kernel is PySpark
  mage_ai/frontend/components/PipelineDetail/KernelStatus.tsx
Labels: bug

#4008 [xy] Some updates on the docs
  docs/getting-started/setup.mdx
  docs/integrations/spark-pyspark.mdx
  docs/production/configuring-production-settings/compute-resource.mdx
Labels: documentation

#4009 [td] Automatically save triggers in code setting
  mage_ai/api/policies/ProjectPolicy.py
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/api/presenters/ProjectPresenter.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/pipelines/models.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/models.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/components/shared/SetupSection/index.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/[...slug].tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/tests/api/endpoints/test_projects.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
  mage_ai/tests/data_preparation/test_repo_manager.py
Labels: feature

#4010 [td] Global hooks backend
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/data_preparation/models/global_hooks/__init__.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/services/compute/aws/models.py
  mage_ai/services/compute/models.py
  mage_ai/services/spark/models/applications.py
  mage_ai/shared/models.py
Labels: feature

#4012 [dy] Fix monoco editor for base path
  mage_ai/frontend/api/utils/url.ts
  mage_ai/frontend/components/CodeEditor/index.tsx
Labels: bug

#4003 [dy] Fix flaky tests
  mage_ai/tests/api/endpoints/test_workspaces.py
  mage_ai/tests/api/operations/test_syncs.py
  mage_integrations/mage_integrations/tests/sources/api/test_api.py
Labels: bug

#4016 [xy] Add better error message for API source.
  mage_integrations/mage_integrations/sources/api/__init__.py
Labels: enhancement

#4011 [td] Attach global hook to resource operation
  mage_ai/api/operations/base.py
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/shared/models.py
  mage_ai/tests/api/operations/test_operations.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
Labels: feature

#4022 [td] Run hook and associated pipeline
  mage_ai/api/operations/base.py
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/orchestration/triggers/api.py
  mage_ai/orchestration/triggers/constants.py
  mage_ai/shared/hash.py
  mage_ai/shared/models.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/shared/test_hash.py
Labels: feature

#4023 [td] Hook predicates
  mage_ai/api/operations/base.py
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/factory.py
Labels: feature

#4024 [td] Add hook operation for running when block is updated in a pipeline
  mage_ai/api/operations/base.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
Labels: feature

#4025 [td] Additional global hook unit tests
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/orchestration/triggers/api.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/__init__.py
  mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/factory.py
  mage_ai/tests/shared/mixins.py
Labels: enhancement

#4026 [td] Add tests for API operations with hooks
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/factory.py
  mage_ai/tests/shared/mixins.py
Labels: enhancement

#4031 [xy] Pass envFrom to job pod.
  mage_ai/services/k8s/job_manager.py
  mage_ai/tests/services/k8s/test_job_manager.py
Labels: enhancement

#4030 [td] UI/UX to create and manage global hooks
  mage_ai/api/policies/BasePolicy.py
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/api/resources/AsyncBaseResource.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.style.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/components/shared/SetupSection/index.tsx
  mage_ai/frontend/interfaces/GlobalHookType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/oracle/elements/Inputs/Select.tsx
  mage_ai/frontend/pages/global-hooks/[...slug].tsx
  mage_ai/frontend/pages/global-hooks/index.tsx
Labels: feature

#4032 [td] Delete hooks
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/oracle/elements/Button/index.tsx
  mage_ai/frontend/pages/global-hooks/index.tsx
Labels: enhancement

#3985 [Feature] ✨ Add support for NATS JetStream message broker
  docs/mint.json
  docs/streaming/sources/nats.mdx
  mage_ai/data_preparation/templates/data_loaders/streaming/nats.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/frontend/interfaces/DataSourceType.ts
  mage_ai/streaming/constants.py
  mage_ai/streaming/sources/nats_js.py
  mage_ai/streaming/sources/source_factory.py
  mage_ai/tests/streaming/sources/test_nats_js.py
  mage_ai/tests/streaming/sources/test_source_factory.py
  requirements.txt
  setup.py
Labels: feature

#4029 [sm] Added data loader templates for Druid and Pinot in the doc
  docs/development/blocks/data_loaders/templates.mdx
Labels: documentation

#4036 [jk] Clarification when applying bookmark to all streams
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
  mage_ai/frontend/oracle/components/Tooltip/TooltipWrapper.tsx
Labels: bug, enhancement

#4037 [td] Enable API operation tests with hooks and add more
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/global_hooks/utils.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/data_preparation/models/global_hooks/test_utils.py
  mage_ai/tests/shared/mixins.py
Labels: enhancement

#3976 Added kafka destination for data integration pipelines
  docs/data-integrations/overview.mdx
  mage_ai/data_integrations/destinations/constants.py
  mage_integrations/mage_integrations/destinations/kafka/README.md
  mage_integrations/mage_integrations/destinations/kafka/__init__.py
  mage_integrations/mage_integrations/destinations/kafka/templates/config.json
  mage_integrations/requirements.txt
Labels: feature, python, data integration

#4038 [td] Add metadata to hook for tracking
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/api/resources/GlobalHookResource.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/frontend/components/Dashboard/index.style.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHooksList/index.tsx
  mage_ai/frontend/components/Roles/RoleDetail.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/interfaces/GlobalHookType.ts
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/global-hooks/[...slug].tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/tests/ai/test_ai_functions.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/shared/mixins.py
Labels: feature

#4045 [td] Hide global hooks feature flag
  mage_ai/data_preparation/models/project/__init__.py
Labels: enhancement

#4046 [xy] Allow using block configuration when run_pipeline_in_one_process is true
  mage_ai/data_preparation/executors/pipeline_executor.py
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4049 [jk] Update logic for valid replication keys in integration pipelines
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/SchemaTable.tsx
Labels: bug

#4050 [jk] Only show Backfills in vertical nav for standard (python) pipelines
  mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
Labels: bug

#4051 [td] Fix files not being selected in notebook
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#3994 [jk] Update backfill statuses
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/tests/factory.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: bug

#4039 [td] Add more complex predicates to hooks
  mage_ai/api/operations/base.py
  mage_ai/api/policies/GlobalHookPolicy.py
  mage_ai/api/presenters/GlobalHookPresenter.py
  mage_ai/data_preparation/models/global_hooks/constants.py
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/data_preparation/models/global_hooks/predicates.py
  mage_ai/shared/models.py
  mage_ai/tests/api/operations/test_operations_with_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_global_hooks.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/data_preparation/models/global_hooks/test_predicates.py
  mage_ai/tests/data_preparation/models/global_hooks/test_utils.py
  mage_ai/tests/shared/mixins.py
Labels: enhancement

#4062 Add asynchronous to global hooks run
  mage_ai/data_preparation/models/global_hooks/models.py
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/interfaces/GlobalHookType.ts
Labels: feature

#4066 [td] Global hooks predicates UI
  mage_ai/data_preparation/models/global_hooks/predicates.py
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/GlobalHooks/PredicateBuilder/LeftRightForm.tsx
  mage_ai/frontend/components/GlobalHooks/PredicateBuilder/PredicateGroup.tsx
  mage_ai/frontend/components/GlobalHooks/PredicateBuilder/index.style.tsx
  mage_ai/frontend/components/GlobalHooks/PredicateBuilder/index.tsx
  mage_ai/frontend/components/GlobalHooks/utils.tsx
  mage_ai/frontend/interfaces/GlobalHookType.ts
  mage_ai/frontend/oracle/components/FlexContainer.tsx
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/tests/data_preparation/models/global_hooks/test_predicates.py
Labels: feature

#4067 [td] Reduce block at any level UI
  mage_ai/frontend/components/CodeBlock/utils.ts
Labels: bug

#4068 [td] Support incremental replication method for data integrations in batch pipelines
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/constants.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/frontend/components/CodeBlock/DataIntegrationBlock/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamOverviewEditor.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamsOverview/index.tsx
  mage_ai/frontend/interfaces/IntegrationSourceType.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/shared/files.py
  mage_integrations/mage_integrations/sources/utils.py
Labels: feature

#4070 [td] Backend API for getting information about bookmarks
  mage_ai/api/policies/IntegrationSourcePolicy.py
  mage_ai/api/presenters/IntegrationSourcePresenter.py
  mage_ai/api/presenters/PipelineRunPresenter.py
  mage_ai/api/presenters/PipelineSchedulePresenter.py
  mage_ai/api/resources/IntegrationSourceResource.py
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/orchestration/db/models/schedules.py
Labels: feature

#4041 [sm] Add RabbitMQ as streaming data sink
  docs/mint.json
  docs/streaming/destinations/rabbitmq.mdx
  mage_ai/data_preparation/templates/data_exporters/streaming/rabbitmq.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/constants.py
  mage_ai/streaming/sinks/rabbitmq.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/tests/streaming/sinks/test_rabbitmq.py
Labels: feature

#4071 [td] Add any runtime variables
  mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
  mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
  mage_ai/frontend/oracle/components/Panel/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: enhancement

#4073 [td] Override bookmark values when creating trigger
  mage_ai/api/policies/IntegrationSourcePolicy.py
  mage_ai/api/presenters/IntegrationSourcePresenter.py
  mage_ai/api/resources/IntegrationSourceResource.py
  mage_ai/data_integrations/utils/scheduler.py
  mage_ai/data_preparation/models/block/data_integration/constants.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/frontend/api/index.ts
  mage_ai/frontend/components/Triggers/BookmarkValues/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/OverwriteVariables/index.tsx
  mage_ai/frontend/components/Triggers/RunPipelinePopup/constants.ts
  mage_ai/frontend/components/Triggers/RunPipelinePopup/index.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/components/shared/SetupSection/index.tsx
  mage_ai/frontend/interfaces/IntegrationSourceType.ts
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/utils/models/pipeline.ts
Labels: feature

#4075 [td] Support different operators when comparing bookmark properties
  mage_ai/data_integrations/sources/constants.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailOverview.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/IntegrationSourceType.ts
  mage_integrations/mage_integrations/sources/catalog.py
  mage_integrations/mage_integrations/sources/sql/base.py
  mage_integrations/mage_integrations/sources/sql/constants.py
  mage_integrations/mage_integrations/sources/sql/utils.py
Labels: feature

#4076 [td] Support interpolating environment variables in SQL blocks
  mage_ai/data_preparation/models/block/sql/utils/shared.py
Labels: feature

#4083 [xy] Catch execption of empty integration streams in pipeline scheduler.
  mage_ai/orchestration/pipeline_scheduler.py
Labels: bug

#4084 [td] Remove accidental print statement
  mage_ai/api/presenters/PipelineSchedulePresenter.py
Labels: bug

#3972 [Fix] Backfill's date-picker date value mismatch
  mage_ai/frontend/components/Triggers/utils.ts
  mage_ai/frontend/utils/date.ts
Labels: bug

#4085 [xy] Include message_events_json in Postmark messages_outbound stream
  mage_integrations/mage_integrations/sources/postmark/__init__.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/postmark.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/schemas/messages_outbound.json
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/streams.py
  mage_integrations/mage_integrations/sources/postmark/tap_postmark/sync.py
Labels: enhancement

#4086 [td] Gracefully access dictionaries in the Oauth Policy
  mage_ai/api/policies/OauthPolicy.py
  mage_ai/tests/api/policies/test_oauth_policy.py
Labels: bug

#4089 [xy] Pass tolerations to job pod.
  mage_ai/services/k8s/job_manager.py
  mage_ai/tests/services/k8s/test_job_manager.py
Labels: bug

#4090 [dy] Update Github docs for GHE
  docs/production/data-sync/github.mdx
Labels: documentation

#4034 [dy] Fix load sample data for integration pipelines
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipelines/integration_pipeline.py
  mage_ai/tests/data_preparation/models/test_block.py
Labels: bug

#4094 [mp] add user guide and update tutorial to explain blocks
  docs/_snippets/whats-a-block.mdx
  docs/data-integrations/destinations/overview.mdx
  docs/data-integrations/sources/overview.mdx
  docs/getting-started/setup.mdx
  docs/guides/community-examples.mdx
  docs/mint.json
Labels: documentation

#4096 [jk] Hide "Unique" and "Key" columns for certain data integration destination blocks
  mage_ai/frontend/components/DataIntegrationModal/StreamDetail/StreamDetailSchemaProperties.tsx
  mage_ai/frontend/components/DataIntegrationModal/StreamSchemaPropertiesEditor/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/IntegrationSourceType.ts
Labels: enhancement

#4098 [jk] Add top padding to file code editor
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeEditor/index.style.tsx
  mage_ai/frontend/components/CodeEditor/index.tsx
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/FileVersions/index.tsx
Labels: enhancement

#4088 [dy] Default to using environment variables for git and workspace settings
  mage_ai/data_preparation/preferences.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/sync/__init__.py
  mage_ai/server/server.py
  mage_ai/settings/repo.py
Labels: bug

#4101 [dy] Update opentelemetry-exporter-prometheus package version
  requirements.txt
  setup.py
Labels: python
