Repository mage-ai/mage-ai, pull requests merged in 2024-03, with the labels that each got.

#4688 [xy] Fix list index out of range for dynamic blocks.
  mage_ai/data_preparation/models/block/dynamic/variables.py
Labels: bug

#4689 [xy] Set default domain for salesforce source
  mage_integrations/mage_integrations/sources/salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/credentials.py
Labels: bug

#4693 [jk] Limit block output for dynamic blocks in UI
  mage_ai/data_preparation/models/block/__init__.py
Labels: enhancement

#4698 [xy] Add auto clean name flag to io classes.
  mage_ai/io/base.py
  mage_ai/io/export_utils.py
  mage_ai/io/mssql.py
  mage_ai/io/mysql.py
  mage_ai/io/postgres.py
  mage_ai/io/sql.py
  mage_ai/io/trino.py
Labels: enhancement

#4696 [dy] Handle JSON reading errors for elasticsearch
  mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/target.py
  mage_integrations/mage_integrations/destinations/target.py
Labels: bug

#4683 [dy] Add try/except
  mage_ai/server/utils/output_display.py
Labels: bug

#4706 [jk] Update backfill policy to allow update on settings
  mage_ai/api/policies/BackfillPolicy.py
Labels: bug

#4699 [dy] Add interval variables for cron based schedules
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: enhancement

#4709 [dy] Fix logging for elasticsearch destination
  mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/target.py
Labels: bug

#4711 [xy] Add upstream_dbt_blocks method back to DBTBlockSQL.
  mage_ai/data_preparation/models/block/dbt/block_sql.py
Labels: bug

#4710 [jk] Bugfix for pipeline interactions
  mage_ai/frontend/api/utils/useDelayFetch.ts
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4717 [xy] Catch sync schedules exception.
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: bug

#4718 [xy] Fix pipeline metadata encoding issue.
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/shared/io.py
Labels: bug

#4714 [jk] Fix buggy pipeline dashboard
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/DataTable/index.tsx
Labels: bug

#4697 [dy] Add error stack trace to the message for pipeline run failure
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/services/slack/slack.py
Labels: enhancement

#4695 Bugfix: Fix migration crash when using MSSQL as mage database
  mage_ai/orchestration/db/migrations/versions/90d978a8aef8_update_unique_constraint_for_secret.py
Labels: bug

#4719 [xy] Set repo_path when syncing trigger configs.
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#4722 [xy] Add docs for trigger and pipeline run queries.
  docs/mint.json
  docs/orchestration/pipeline-runs/database-query.mdx
  docs/orchestration/triggers/database-query.mdx
Labels: documentation

#4726 [jk] Delete backfills
  docs/api-reference/backfills/overview.mdx
  docs/api-reference/backfills/update-backfill.mdx
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Edit/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/shared/Table/useDeleteConfirmDialogue.tsx
  mage_ai/frontend/interfaces/BackfillType.ts
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
Labels: feature

#4674 [dy] Support reading authentication settings from AWS secrets manager
  docs/mint.json
  docs/production/configuring-production-settings/settings-backend.mdx
  mage_ai/api/monitors/BaseMonitor.py
  mage_ai/api/resources/SessionResource.py
  mage_ai/authentication/ldap.py
  mage_ai/authentication/oauth/constants.py
  mage_ai/authentication/providers/active_directory.py
  mage_ai/authentication/providers/bitbucket.py
  mage_ai/authentication/providers/ghe.py
  mage_ai/authentication/providers/gitlab.py
  mage_ai/authentication/providers/google.py
  mage_ai/authentication/providers/oidc.py
  mage_ai/authentication/providers/okta.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/data_preparation/preferences.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/server/file_observer.py
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  mage_ai/settings/backends.py
  mage_ai/settings/keys/__init__.py
  mage_ai/settings/keys/auth.py
  mage_ai/settings/server.py
  mage_ai/settings/sso.py
  mage_ai/tests/api/endpoints/test_oauths.py
  mage_ai/tests/api/operations/test_operations.py
  mage_ai/tests/api/operations/test_sessions.py
  mage_ai/tests/authentication/providers/test_active_directory.py
  requirements.txt
Labels: enhancement

#4712 [dy] Add unique_conflict_method for mssql
  docs/integrations/databases/MicrosoftSQLServer.mdx
  mage_ai/io/mssql.py
  mage_ai/io/sql.py
Labels: enhancement

#4728 [jk] Allow file to be opened in Pipeline Editor without Command Center enabled
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4732 [jk] Scrollbar polish
  mage_ai/frontend/components/IntegrationPipeline/SchemaSettings/index.tsx
  mage_ai/frontend/components/RuntimeVariables/index.style.tsx
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.style.ts
  mage_ai/frontend/oracle/components/Tabs/ButtonTabs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: enhancement

#4733 [jk] Bugfix dock overlay
  mage_ai/frontend/components/ApplicationManager/index.style.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4735 [xy] Remove Redshift stl insert query.
  mage_integrations/mage_integrations/destinations/redshift/__init__.py
Labels: enhancement

#4734 [dy] Display error on oauth
  mage_ai/authentication/providers/oidc.py
  mage_ai/frontend/pages/oauth.tsx
Labels: bug

#4736 [xy] Run status endpoint in scheduler.
  mage_ai/server/server.py
Labels: enhancement

#4744 [jk] Avoid client error when making request before interactions are done loading
  mage_ai/frontend/components/Interactions/InteractionSettings.tsx
  mage_ai/frontend/components/PipelineInteractions/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4739 Trino temp table location fix - Fixes issue https://github.com/mage-ai/mage-ai/issues/4738
  mage_integrations/README.md
  mage_integrations/mage_integrations/destinations/trino/README.md
  mage_integrations/mage_integrations/destinations/trino/connectors/base.py
  mage_integrations/mage_integrations/destinations/trino/templates/config.json
Labels: bug

#4750 [xy] Fix alter Snowflake table with lower_case=false
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
Labels: bug

#4751 [jk] Fix block run sorting
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
Labels: bug

#4753 [dy] Fix sign in issue
  mage_ai/frontend/pages/index.tsx
Labels: bug

#4755 [jk] Add check to avoid rendering of invalid JSX element
  mage_ai/frontend/components/Logs/Detail/index.tsx
Labels: bug

#4746 [dy] Add documentation on mocking IO libraries in unit tests
  docs/development/testing/unit-tests.mdx
Labels: documentation

#4760 [dy] Fix GitLab auth issues
  mage_ai/data_preparation/git/api.py
  mage_ai/data_preparation/git/clients/gitlab.py
Labels: bug

#4763 [xy] Support custom python source in Streaming pipeline
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/templates/data_loaders/streaming/generic_python.py
  mage_ai/data_preparation/templates/template.py
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/sources/base_python.py
  mage_ai/streaming/sources/source_factory.py
Labels: feature

#4758 [jk] Limit number of block output files read and included in pipeline response
  docs/design/data-pipeline-management.mdx
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/storage/s3_storage.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/services/aws/s3/s3.py
Labels: enhancement

#4768 [jk] Increase visibility of code block context menu
  mage_ai/frontend/components/CodeEditor/index.style.tsx
Labels: bug

#4772 [fa] Server logging format template overriding
  README_dev.md
  docker-compose.yml
  docs/contributing/development-environment.mdx
  docs/development/observability/logging.mdx
  mage_ai/settings/server.py
  mage_ai/shared/logger.py
Labels: enhancement

#4782 [dy] Check status response for REQUIRE_USER_AUTHENTICATION
  mage_ai/frontend/pages/index.tsx
Labels: bug

#4783 [xy] Fix exporting dataframe to bigquery.
  mage_ai/io/bigquery.py
Labels: bug

#4784 [xy] Catch job manager init error.
  mage_ai/orchestration/job_manager.py
Labels: bug

#4701 [xh] Oracle add thick mode support in standard pipeline
  mage_ai/io/oracledb.py
Labels: feature

#4747 [dy] Add all parent block variables to the add on block
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/PipelineDetail/AddonBlocks/AddonBlock.tsx
  mage_ai/frontend/components/PipelineDetail/AddonBlocks/index.tsx
  mage_ai/tests/data_preparation/models/test_block.py
Labels: bug

#4789 [xy] Only show sql logs in debug environment.
  mage_ai/orchestration/db/__init__.py
Labels: enhancement

#4792 [xy] Interpolate global vars in k8s executor namespace
  mage_ai/data_preparation/executors/k8s_block_executor.py
  mage_ai/data_preparation/executors/k8s_pipeline_executor.py
  mage_ai/services/k8s/job_manager.py
Labels: enhancement

#4793 [enhancement] mongodb stream full_document config option
  docs/mint.json
  docs/streaming/sources/mongodb.mdx
  mage_ai/streaming/sources/mongodb.py
Labels: enhancement

#4788 [dy] Fix clickhouse destination
  mage_ai/frontend/components/DataIntegrationModal/Credentials/index.tsx
  mage_ai/frontend/components/IntegrationPipeline/SourceConfig.tsx
  mage_integrations/requirements.txt
Labels: bug

#4797 [jk] Bugfixes - table render / rename destination block
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/integration/__init__.py
  mage_ai/frontend/components/CodeBlockV2/Output/index.tsx
Labels: bug

#4790 [jk] Update pipeline name before pipeline creation
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/CommandCenter/ItemRow/constants.tsx
  mage_ai/frontend/components/CustomTemplates/BrowseTemplates/constants.tsx
  mage_ai/frontend/components/Dashboard/utils.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigurePipeline/index.tsx
  mage_ai/frontend/components/PipelineDetail/Settings/index.tsx
  mage_ai/frontend/components/VersionControlFileDiffs/FileNavigation.tsx
  mage_ai/frontend/components/VersionControlFileDiffs/index.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/oracle/elements/Inputs/InputModal.tsx
  mage_ai/frontend/oracle/elements/Inputs/InputWrapper.tsx
  mage_ai/frontend/oracle/icons/custom/StreamingPipeline.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/tests/pipelines.spec.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts
Labels: enhancement

#4806 [dy] Load pipeline tags from config
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#4807 [xy] Improve the performance of loading dbt blocks.
  mage_ai/api/resources/BlockLayoutItemResource.py
  mage_ai/api/resources/BlockResource.py
  mage_ai/api/resources/CacheItemResource.py
  mage_ai/api/resources/PageBlockLayoutResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/block_factory.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/global_data_product/__init__.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/shared/path_fixer.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/tests/settings/models/test_configuration_option.py
Labels: enhancement

#4812 [jk] Avoid N dbt config option requests for N blocks on Pipeline Editor
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlockV2/constants.ts
  mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
  mage_ai/frontend/components/CodeBlockV2/dbt/useCodeBlockProps.tsx
  mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
Labels: enhancement

#4815 [xy] Speed up backend requests.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/services/spark/spark.py
  mage_ai/settings/models/configuration_option.py
  mage_ai/shared/files.py
Labels: enhancement

#4822 [jk] Fix unclickable dbt sql file in dbt v1 model select
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileSelectorPopup/index.style.tsx
  mage_ai/frontend/components/FileSelectorPopup/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4825 [xy] Raise ImportError when spark is not supported.
  mage_ai/services/spark/spark.py
Labels: bug

#4833 [xy] Fix mongodb source typo.
  mage_ai/streaming/sources/mongodb.py
Labels: bug

#4832 [xy] Test kafka connection when initializing the consumer.
  mage_ai/streaming/sources/base.py
  mage_ai/streaming/sources/kafka.py
Labels: enhancement

#4834 [jk] Configure dbt v2 yaml block and other dbt code block improvements
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
  mage_ai/frontend/components/CodeBlockV2/dbt/constants.tsx
  mage_ai/frontend/components/CodeBlockV2/useCodeBlockComponents.tsx
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/tests/base.ts
  mage_ai/frontend/tsconfig.json
  mage_ai/frontend/utils/array.ts
Labels: bug

#4837 [xy] Make path_to_credential optional in GCS logger.
  docs/development/observability/logging.mdx
  mage_ai/data_preparation/logging/gcs_logger_manager.py
Labels: enhancement

#4839 [xy] Fix writing polars dataframe to gcs storage.
  mage_ai/data_preparation/storage/gcs_storage.py
Labels: bug

#4802 [xy] Create snowflake temp table like original table.
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  requirements.txt
  setup.py
Labels: bug

#4841 [jk] Bugfix pipeline tag cache
  mage_ai/cache/tag.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#4785 [xh]Oracledb add export
  mage_ai/data_preparation/templates/constants.py
  mage_ai/io/export_utils.py
  mage_ai/io/oracledb.py
  mage_ai/io/sql.py
Labels: feature

#4816 [xh] Oracle fix issue: incremental datetime bookmark fetch fails
  mage_integrations/mage_integrations/sources/oracledb/__init__.py
Labels: bug

#4844 [jk] Clear block_uuid query param when selecting new block
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4838 [dy] Catch JSON decode errors in mage targets
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/target.py
  mage_integrations/mage_integrations/destinations/elasticsearch/target_elasticsearch/sinks.py
  mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
  mage_integrations/mage_integrations/destinations/opensearch/target_opensearch/target.py
  mage_integrations/mage_integrations/destinations/sink.py
Labels: bug

#4846 [dy] Fix permission seed
  mage_ai/api/resources/SeedResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/authentication/permissions/seed.py
  mage_ai/data_preparation/shared/utils.py
  mage_ai/tests/api/endpoints/mixins.py
  mage_ai/tests/api/endpoints/test_seeds.py
Labels: bug

#4848 [jk] Replace blue font with cyan in terminal
  mage_ai/frontend/components/Terminal/index.tsx
  mage_ai/frontend/components/Terminal/useTerminal/index.tsx
Labels: enhancement

#4850 [jk] Replace Block reference with BlockFactory
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4851 [xy] Kill all jobs on scheduler crash.
  mage_ai/orchestration/job_manager.py
  mage_ai/orchestration/queue/celery_queue.py
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/orchestration/queue/queue.py
  mage_ai/server/scheduler_manager.py
  mage_ai/tests/orchestration/queue/test_process_queue.py
Labels: enhancement

#4855 [jk] Fix block search add block error
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4856 [xy] Fix spark dataframe read error.
  mage_ai/data_preparation/models/variable.py
Labels: bug

#4859 [jk] Fix filters from being reset when items fetched
  mage_ai/frontend/pages/pipeline-runs/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: bug

#4860 [td] Update GX and other libraries to support higher versions of Pydantic
  requirements.txt
  setup.py
Labels: enhancement
