Repository mage-ai/mage-ai, pull requests merged in 2024-07, with the labels that each got.

#5239 [xy] Pipeline execution for execution framework
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frameworks/execution/constants.py
  mage_ai/frameworks/execution/models/pipeline/base.py
Labels: enhancement

#5243 [cf]-data-exporter-docs-update
  docs/design/blocks/data-exporter.mdx
Labels: documentation

#5252 [xy] Interpolate the sql profile.
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/data_preparation/models/utils.py
Labels: enhancement

#5254 [xy] Don't force cast type to int or float.
  mage_ai/data_preparation/models/widget/utils.py
Labels: bug

#5250 [CF]-Azure-Event-Hub-Doc-Update
  docs/streaming/sources/azure-event-hub.mdx
Labels: documentation

#5256 [jk] Add back yarn.lock file
  .circleci/config.yml
  .gitignore
  mage_ai/frontend/styles/scss/main.scss
  mage_ai/frontend/yarn.lock
  package.json
  yarn.lock
Labels: dependencies

#5263 [xy] Add trigger pipeline overview back to nav
  docs/mint.json
  docs/orchestration/triggers/triggering-pipelines.mdx
Labels: documentation

#5265 [xy] Some fixes for using requests base path.
  mage_ai/authentication/providers/utils.py
  mage_ai/server/server.py
Labels: bug

#5267 [xy] Update the file content API implementation.
  mage_ai/server/server.py
Labels: bug

#5275 [jk] Default command center item
  mage_ai/frontend/components/CommandCenter/ItemRow/constants.tsx
  mage_ai/frontend/components/CommandCenter/ItemRow/index.tsx
Labels: bug

#5279 [xy] Allow optional block groups.
  mage_ai/frameworks/execution/models/pipeline/base.py
Labels: enhancement

#5286 [jk] Include base path when loading favicon
  mage_ai/frontend/oracle/elements/Head/index.tsx
Labels: bug

#5284 [jk] V2 Canvas entry points
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/cache/utils.py
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#5289 [jk] Cookie session updates
  mage_ai/frontend/api/cleaner/utils/token.ts
  mage_ai/frontend/api/utils/AuthToken.ts
  mage_ai/frontend/api/utils/token.ts
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/mana/themes/utils.ts
  mage_ai/frontend/oracle/styles/themes/utils.ts
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/pages/_document.tsx
  mage_ai/frontend/utils/cookies/constants.ts
  mage_ai/frontend/utils/cookies/utils.ts
  mage_ai/frontend/utils/session.ts
  mage_ai/frontend/yarn.lock
Labels: enhancement

#5283 [xh]Update openai version to >= 1.0.0
  mage_ai/ai/openai_client.py
  requirements.txt
  setup.py
Labels: feature

#5290 [xy] Add all upstream dbt blocks when adding a dbt block
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
Labels: enhancement

#5300 [xy] Only run memory usage failure check when executor type is local python
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: bug

#5301 [xy] Fix kernel interruption.
  mage_ai/server/utils/execute_custom_code.py
  mage_ai/server/utils/frontend_renderer.py
  mage_ai/server/utils/output_display.py
  requirements.txt
Labels: bug

#5302 [xy] Support getting Azure db conn url from key vault.
  mage_ai/orchestration/constants.py
  mage_ai/orchestration/db/setup.py
Labels: feature

#5304 [xy] Support customizing node selector in k8s config.
  mage_ai/services/k8s/config.py
  mage_ai/services/k8s/job_manager.py
Labels: enhancement

#5294 [jk] Differentiate current_user local storage
  mage_ai/frontend/api/utils/AuthToken.ts
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/GlobalHooks/GlobalHookDetail/index.tsx
  mage_ai/frontend/components/Orchestration/CreateSchedule/index.tsx
  mage_ai/frontend/components/PipelineDetail/Extensions/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/Sessions/SignForm/index.tsx
  mage_ai/frontend/components/Terminal/useTerminal/index.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/components/VersionControl/GitActions.tsx
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/components/settings/Dashboard/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/components/users/UserDetail.tsx
  mage_ai/frontend/components/users/edit/Form/index.tsx
  mage_ai/frontend/components/workspaces/Dashboard/index.tsx
  mage_ai/frontend/interfaces/UserPropertiesType.ts
  mage_ai/frontend/oracle/elements/Head/index.tsx
  mage_ai/frontend/pages/manage/users/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/settings/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/pages/settings/account/profile.tsx
  mage_ai/frontend/pages/settings/workspace/users/index.tsx
  mage_ai/frontend/utils/hooks/useGetUser.ts
  mage_ai/frontend/utils/routing.ts
  mage_ai/frontend/utils/session.ts
Labels: bug

#5307 [td] Fix blocks waiting and when fetching upstream w/ no output
  mage_ai/data_preparation/models/block/dynamic/counter.py
  mage_ai/data_preparation/models/block/dynamic/data.py
  mage_ai/data_preparation/models/block/dynamic/factory.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/models/block/settings/dynamic/constants.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/presenters/blocks/graph.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_variables.py
Labels: bug
