Repository mage-ai/mage-ai, pull requests merged in 2024-02, with the labels that each got.

#4505 [td] Fix some minor bugs
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/models/widget/utils.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/pages/overview/index.tsx
Labels: bug

#4506 [td] Remove table name helper
  mage_ai/data_preparation/models/block/sql/bigquery.py
  mage_ai/io/bigquery.py
Labels: bug

#4499 MSSQL data integration source - add support for DATETIMEOFFSET type
  mage_integrations/mage_integrations/connections/mssql/__init__.py
Labels: enhancement

#4493 Fix alter table column names cleaning (postgresql integration exporter)
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
Labels: bug

#4357 fix: handle unprivileged user for postgres
  mage_ai/io/postgres.py
Labels: enhancement

#4402 Fixed Oauth connection on Salesforce Source
  mage_integrations/mage_integrations/sources/salesforce/README.md
  mage_integrations/mage_integrations/sources/salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/credentials.py
Labels: bug, python, data integration

#4514 [xy] Update doc for Redshift skip_schema_creation.
  mage_integrations/mage_integrations/destinations/redshift/README.md
Labels: documentation

#4512 [jk] Fix unclickable vertical scrollbar and jumping before panel
  mage_ai/frontend/components/ComputeManagement/index.tsx
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/Files/index.style.tsx
  mage_ai/frontend/components/PipelineLayout/index.tsx
  mage_ai/frontend/components/ScheduleLayout/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4188 [dy] Optimize pipeline schedule queries
  mage_ai/orchestration/db/models/schedules.py
Labels: enhancement

#4504 [dy] Add docs
  docs/production/authentication/microsoft.mdx
  docs/production/developing-in-the-cloud/workspaces/kubernetes.mdx
Labels: documentation

#4520 [xy] Update Kafka doc about SASL authentication.
  docs/streaming/sources/kafka.mdx
Labels: documentation

#4521 [jk] Remove pipeline's updated_at attribute
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/cache/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/tests/cache/example_pipeline.json
  mage_ai/tests/cache/pipeline_details_mapping_template
  mage_ai/tests/cache/test_pipeline_cache.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: enhancement

#4524 [xy] Upgrade snowflake library version and fix datetime column type.
  mage_ai/io/snowflake.py
  mage_integrations/requirements.txt
  requirements.txt
  setup.py
Labels: bug

#4509 [dy] Only show files with correct prefix
  mage_ai/frontend/components/Files/useFileComponents.tsx
Labels: bug

#4523 [dy] Update connection url
  mage_ai/io/mssql.py
Labels: bug

#4446 pipeline env vars
  docs/getting-started/runtime-variable.mdx
Labels: documentation

#4406 [mp] Update Pipelines API
  docs/api-reference/pipelines/create-pipeline.mdx
Labels: documentation

#4533 [xy] Support MotherDuck.
  mage_ai/io/config.py
  mage_ai/io/duckdb.py
  requirements.txt
  setup.py
Labels: feature

#4536 [jk] Update how the stale pipeline message modal is displayed
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug, enhancement

#4421 [xh] Add Oracle dockerfile to support thick mode
  docs/design/data-loading.mdx
  integrations/oracle/Dockerfile
  mage_ai/io/config.py
  mage_ai/io/oracledb.py
  mage_integrations/mage_integrations/connections/oracledb/__init__.py
  mage_integrations/mage_integrations/destinations/oracledb/README.md
  mage_integrations/mage_integrations/destinations/oracledb/__init__.py
  mage_integrations/mage_integrations/destinations/oracledb/templates/config.json
  mage_integrations/mage_integrations/sources/oracledb/README.md
  mage_integrations/mage_integrations/sources/oracledb/__init__.py
  mage_integrations/mage_integrations/tests/destinations/oracledb/test_oracledb.py
Labels: feature

#4453 [rp] Import functionality for pipeline zips
  mage_ai/api/policies/FilePolicy.py
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/data_preparation/models/errors.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/api/utils/fetcher.ts
  mage_ai/frontend/components/Dashboard/utils.tsx
  mage_ai/frontend/components/FileUploader/index.tsx
  mage_ai/frontend/components/PipelineDetail/UploadPipeline/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
Labels: feature

#4513 [dy] Create and view workspaces in different namespaces
  mage_ai/api/policies/WorkspacePolicy.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/cluster_manager/manage.py
  mage_ai/cluster_manager/workspace/kubernetes.py
  mage_ai/frontend/components/shared/Table/Toolbar/index.tsx
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
  mage_ai/frontend/interfaces/WorkspaceType.ts
  mage_ai/frontend/pages/manage/index.tsx
  mage_ai/frontend/storage/workspaces.ts
  mage_ai/server/server.py
Labels: enhancement

#4543 [xy] Fix running dynamic blocks with k8s executor.
  mage_ai/cli/main.py
Labels: bug

#4545 [jk] Widget policy update
  mage_ai/api/policies/WidgetPolicy.py
  mage_ai/cache/block.py
  mage_ai/frontend/components/ChartBlock/index.tsx
Labels: bug

#4548 [xy] Catch exception of building cache key for block cache.
  mage_ai/cache/block.py
Labels: bug

#4550 [jk] Add docs for used/unused block files in file browser
  docs/developer-ux/file-browser.mdx
Labels: documentation

#4544 [dy] Update docs
  docs/development/observability/logging.mdx
  docs/production/developing-in-the-cloud/workspaces/kubernetes.mdx
Labels: documentation

#4554 [xy] Use utc time as the default time for monitor_stats.
  mage_ai/orchestration/monitor/monitor_stats.py
Labels: bug

#4555 [jk] Add docs for importing pipelines
  docs/guides/pipelines/importing-pipelines.mdx
  docs/mint.json
Labels: documentation

#4561 [xy] Improve google sheets source.
  mage_integrations/mage_integrations/connections/google_sheets/__init__.py
  mage_integrations/mage_integrations/sources/base.py
  mage_integrations/mage_integrations/sources/google_sheets/__init__.py
Labels: enhancement

#4476 [Feature] ✨ adding BACKEND support for OpenTelemetry (OTEL)
  docker-compose.yml
  docs/integrations/observability/opentelemetry.mdx
  docs/mint.json
  mage_ai/orchestration/db/__init__.py
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  requirements.txt
  scripts/dev.sh
  setup.py
Labels: feature

#4562 [jk] Reuse callback and conditional blocks
  mage_ai/api/resources/SearchResultResource.py
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/FileEditor/utils.ts
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/FileType.ts
Labels: enhancement

#4564 [xy] Show pandas datetime in iso format in notebook.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/server/utils/output_display.py
Labels: enhancement

#4565 Fix Google Ads Catalog to Data Integration Block
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/streams.py
Labels: bug, python, data integration

#4142 Added reserved words settings to PostgreSQL
  mage_integrations/mage_integrations/destinations/postgresql/README.md
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/destinations/sql/base.py
  mage_integrations/mage_integrations/destinations/sql/utils.py
Labels: feature, python, data integration

#4569 [xy] Add case_sensitive param to the sql export method.
  mage_ai/io/base.py
  mage_ai/io/export_utils.py
  mage_ai/io/postgres.py
  mage_ai/io/sql.py
  mage_ai/shared/utils.py
Labels: enhancement

#4574 [jk] Load custom design logo
  mage_ai/frontend/api/utils/useDelayFetch.ts
  mage_ai/frontend/utils/models/customDesign/useCustomDesign.ts
Labels: bug

#4552 [dy] Adjust alembic logger initialization
  mage_ai/orchestration/db/database_manager.py
  mage_ai/orchestration/db/migrations/env.py
  mage_ai/tests/base_test.py
Labels: bug

#4568 [dy] Add support for AWS codecommit
  docs/_snippets/configure-git-sync.mdx
  docs/development/git/configure.mdx
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/SyncResource.py
  mage_ai/cli/main.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/sync/git_sync.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
  mage_ai/orchestration/utils/git.py
  mage_ai/server/server.py
Labels: bug

#4573 [dy] Fix frontend crashing issues
  mage_ai/api/presenters/IntegrationSourceStreamPresenter.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/discover.py
  mage_integrations/mage_integrations/sources/sftp/tap_sftp/tap.py
Labels: bug

#4576 [xy] Set max width for yaml file to inf.
  mage_ai/data_preparation/repo_manager.py
Labels: bug

#4577 [dy] Fix DBT logging
  mage_ai/data_preparation/logging/logger.py
  mage_ai/data_preparation/models/block/dbt/constants.py
  mage_ai/data_preparation/models/block/dbt/dbt_cli.py
  mage_ai/frontend/components/Logs/Table/index.tsx
Labels: bug

#4575 [dy] Show the load balancer ingress host if there is no host in the ingress rules
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/shared/hash.py
  mage_ai/tests/shared/test_hash.py
Labels: bug

#4578 [xy] Create TEMP Snowflake table in data integration destination
  mage_integrations/mage_integrations/connections/sql/base.py
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py
  requirements.txt
  setup.py
Labels: enhancement

#4583 [dy] Misc workspace/git improvements
  docs/production/deploying-to-cloud/aws/setup.mdx
  mage_ai/api/presenters/GitBranchPresenter.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/frontend/components/VersionControl/Branches/index.tsx
  mage_ai/frontend/pages/manage/index.tsx
Labels: enhancement

#4588 [xy] Match postgres logical replication records with stream name.
  mage_integrations/mage_integrations/sources/postgresql/__init__.py
Labels: bug

#4590 Luthfir/discord notification
  docs/integrations/observability/alerting-discord.mdx
  mage_ai/orchestration/notification/sender.py
  mage_ai/services/discord/discord.py
Labels: bug

#4593 [dy] Update docs 2/16
  docs/production/authentication/oidc.mdx
  docs/production/data-sync/github.mdx
  mage_ai/authentication/providers/gitlab.py
Labels: documentation

#4604 [xy] Support filtering google sheets by sheet names
  mage_integrations/mage_integrations/sources/google_sheets/README.md
  mage_integrations/mage_integrations/sources/google_sheets/__init__.py
  mage_integrations/mage_integrations/sources/google_sheets/templates/config.json
Labels: enhancement

#4605 [xy] Support exporting to mysql with selected columns.
  mage_ai/io/clickhouse.py
  mage_ai/io/mysql.py
  mage_ai/io/sql.py
  mage_ai/io/trino.py
Labels: bug

#4606 [xy] Update the port check to use specified host.
  mage_ai/server/server.py
  mage_ai/shared/utils.py
Labels: bug

#4610 [xy] Set default host when checking port.
  mage_ai/shared/utils.py
Labels: bug

#4611 [dy] Refactor duplicate git code
  mage_ai/api/resources/SyncResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/data_preparation/preferences.py
  mage_ai/data_preparation/sync/git_sync.py
Labels: bug

#4613 [jk] Fix unclickable minimized windows
  mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4614 [xy] Combine schedulers.
  mage_ai/orchestration/pipeline_scheduler.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/tests/orchestration/test_pipeline_scheduler_project_platform.py
Labels: enhancement

#4620 [dy] Attempt to resolve network issues
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
Labels: bug

#4612 [dy] Update EKS docs
  docs/production/deploying-to-cloud/aws/setup.mdx
Labels: documentation

#4621 [xy] Separate scheduler logs and pipeline logs.
  mage_ai/api/resources/LogResource.py
  mage_ai/data_preparation/logging/logger_manager.py
  mage_ai/data_preparation/models/file.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
Labels: enhancement

#4628 [dy] Fix typo in AD documentation
  docs/production/authentication/microsoft.mdx
Labels: documentation

#4627 [jk] Update tag and block cache when cloning pipeline
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: bug

#4631 [jk] Various bugfixes for pipeline search and filter
  mage_ai/api/resources/PipelineResource.py
  mage_ai/frontend/oracle/components/ToggleMenu/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: bug

#4634 [xy] Use milliseconds in parquet by default.
  mage_ai/io/base.py
  mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
  mage_integrations/mage_integrations/destinations/google_cloud_storage/__init__.py
Labels: bug

#4642 Fixed random input inside singer destinations
  mage_integrations/mage_integrations/destinations/mongodb/target_mongodb/target.py
  mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py
Labels: bug, python, data integration

#4643 [jk] Fix double scrollbars and draggable height
  mage_ai/frontend/components/ComputeManagement/index.tsx
  mage_ai/frontend/components/PipelineLayout/index.tsx
  mage_ai/frontend/components/PipelineRun/shared/buildTableSidekick.tsx
  mage_ai/frontend/components/RuntimeVariables/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/components/VersionControl/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
Labels: bug

#4644 [jk] UI bugfixes on Version Control page
  mage_ai/frontend/components/VersionControl/Branches/index.tsx
  mage_ai/frontend/components/VersionControl/index.tsx
Labels: bug

#4630 [dy] Fix unit test logging
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/database_manager.py
Labels: bug

#4629 [dy] Add DB locking
  mage_ai/orchestration/db/database_manager.py
Labels: bug

#4618 [dy] Improve backfills
  mage_ai/api/presenters/BackfillPresenter.py
  mage_ai/api/resources/BackfillResource.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Edit/index.tsx
  mage_ai/frontend/interfaces/BackfillType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/backfills/[...slug].tsx
  mage_ai/orchestration/backfills/service.py
  mage_ai/orchestration/db/migrations/versions/b9a2d6d0a2c7_add_settings_to_backfill.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: enhancement

#4657 [dy] Update docs link
  docs/production/data-sync/github.mdx
Labels: documentation

#4659 [jk] Bugfixes for Overview Dashboard
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/BlockLayout/index.tsx
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/GlobalDataProductDetail/index.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/pages/overview/index.tsx
Labels: bug

#4662 [jk] Redirect to login page immediately
  mage_ai/frontend/pages/index.tsx
Labels: enhancement

#4665 [jk] Clean up chart block widths in Pipeline Editor
  mage_ai/frontend/components/ChartBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/CommandButtons/AddChartMenu.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/oracle/components/LabelWithValueClicker.tsx
  mage_ai/frontend/utils/string.ts
Labels: enhancement

#4667 [jk] Bugfix for save block shortcut
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4640 Fixed postgreSQL reserved words
  mage_integrations/mage_integrations/destinations/postgresql/__init__.py
  mage_integrations/mage_integrations/destinations/sql/utils.py
Labels: bug, python, data integration

#4668 [xy] Support extra connection arguments in mysql source and destination.
  mage_integrations/mage_integrations/connections/mysql/__init__.py
  mage_integrations/mage_integrations/destinations/mysql/README.md
  mage_integrations/mage_integrations/destinations/mysql/__init__.py
  mage_integrations/mage_integrations/sources/mysql/README.md
  mage_integrations/mage_integrations/sources/mysql/__init__.py
  mage_integrations/mage_integrations/tests/destinations/mysql/test_mysql.py
Labels: enhancement

#4658 [dy] Minor workspace fixes
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/settings/__init__.py
Labels: bug

#4444 [xy] Bump up more versions to resolve vulnerabilities.
  requirements.txt
Labels: security

#4671 [xy] Fix image build
  docs/integrations/databases/Chroma.mdx
  requirements.txt
  setup.py
Labels: enhancement

#4672 [jk] Sync block contents for replica block when minimizing
  mage_ai/frontend/components/CodeBlock/index.tsx
Labels: bug

#4429 [edw] e2e test: load pages no errors
  docs/contributing/frontend/testing.mdx
  mage_ai/frontend/.gitignore
  mage_ai/frontend/components/Dashboard/VerticalNavigation.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/playwright.config.ci.ts
  mage_ai/frontend/playwright.config.ts
  mage_ai/frontend/tests/base.ts
  mage_ai/frontend/tests/pages.spec.ts
  mage_ai/frontend/tests/pipelines.spec.ts
  mage_ai/frontend/utils/testing/index.ts
Labels: testing

#4686 [jk] Fix "filter is not a function" type error in schema props
  mage_ai/frontend/utils/models/block.ts
Labels: bug
