Repository mage-ai/mage-ai, pull requests merged in 2024-11, with the labels that each got.

#5485 [jk] Allow user to set number of lines displayed for block output sample preview
  docs/development/variables/environment-variables.mdx
  mage_ai/data_preparation/models/constants.py
  mage_ai/frontend/components/BlockSettings/index.tsx
Labels: enhancement

#5523 [xh] Update python version to fix vulnerabilities
  requirements.txt
Labels: feature

#5478 [jk] Revert name of test environment
  mage_ai/orchestration/db/__init__.py
  mage_ai/shared/constants.py
  mage_ai/shared/environments.py
  mage_ai/tests/data_preparation/models/block/hook/test_hook_block.py
Labels: bug

#5588 [jk] Environment-specific config override docs
  docs/_snippets/contribution-process.mdx
  docs/contributing/development-environment.mdx
  docs/extensibility/env-config/pipeline.mdx
  docs/extensibility/env-config/project.mdx
  docs/mint.json
Labels: documentation
