Repository mage-ai/mage-ai, pull requests merged in 2024-12, with the labels that each got.

#5611 [cf]-fixed-links-to-streaming-docs
  docs/mint.json
Labels: bug, documentation

#5601 Update the version for the google-ads module
  mage_integrations/requirements.txt
  requirements.txt
  setup.py
Labels: enhancement

#5615 [cf]-added-destinations-back
  docs/mint.json
Labels: bug, documentation

#5625 [xy] Support hiding and rotating API trigger token.
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/presenters/PipelineSchedulePresenter.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/settings/server.py
Labels: enhancement, security
