Repository mage-ai/mage-ai, pull requests merged in 2024-08, with the labels that each got.

#5311 [jk] Workspace monitoring
  mage_ai/api/policies/PipelineRunPolicy.py
  mage_ai/api/presenters/PipelineRunPresenter.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/PipelineRun/Widget/index.tsx
  mage_ai/frontend/components/PipelineRun/shared/utils.ts
  mage_ai/frontend/components/workspaces/Dashboard/constants.ts
  mage_ai/frontend/interfaces/PipelineRunType.ts
  mage_ai/frontend/interfaces/WorkspaceType.ts
  mage_ai/frontend/pages/manage/overview/index.tsx
  mage_ai/frontend/pages/manage/pipeline-runs/index.tsx
  mage_ai/frontend/pages/settings/workspace/preferences.tsx
  mage_ai/orchestration/db/models/schedules.py
Labels: feature

#5319 [cf]-requirements-documentation-updates
  docs/development/dependencies/requirements.mdx
Labels: documentation

#5327 [jk] Update condition for cookie secure property
  mage_ai/frontend/utils/cookies/constants.ts
  mage_ai/frontend/utils/environment.ts
Labels: bug

#5329 [xy] Fix NoneType in trigger settings.
  mage_ai/data_preparation/models/triggers/__init__.py
Labels: bug

#5331 [xy] Reduce CPU usage in scheduler.
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: enhancement

#5332 [xy] Fix dbt block delete request with nginx.
  mage_ai/server/server.py
Labels: bug

#5338 [xy] Fix API for file versions.
  mage_ai/server/server.py
Labels: bug

#5341 ActiveMQ update commit
  docs/streaming/sources/activemq.mdx
Labels: documentation

#5344 [xy] Pass main pod labels to workspaces.
  mage_ai/cluster_manager/kubernetes/workload_manager.py
Labels: enhancement

#5366 [xy] Fix schema creation when schema name is wrapped with double quotes.
  mage_ai/io/postgres.py
Labels: bug

#5352 [CF]-Azure-gove
  docs/production/authentication/microsoft.mdx
Labels: documentation
