Repository mage-ai/mage-ai, pull requests merged in 2024-06, with the labels that each got.

#5152 [td] Fix Dockerfile to install faster fifo from source
  Dockerfile
  dev.Dockerfile
Labels: bug

#5151 [xy] Fix import and add user to verify_project.
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/data_preparation/models/block/dynamic/models.py
Labels: bug

#5160 [td] Standalone Monaco editor
  docker-compose.yml
  mage_ai/frontend/.eslintrc.js
  mage_ai/frontend/components/v2/IDE/autocomplete/index.tsx
  mage_ai/frontend/components/v2/IDE/configurations/base.ts
  mage_ai/frontend/components/v2/IDE/index.style.tsx
  mage_ai/frontend/components/v2/IDE/index.tsx
  mage_ai/frontend/components/v2/IDE/languages/constants.ts
  mage_ai/frontend/components/v2/IDE/languages/python/configuration.ts
  mage_ai/frontend/components/v2/IDE/languages/python/index.ts
  mage_ai/frontend/components/v2/IDE/languages/python/provider.ts
  mage_ai/frontend/components/v2/IDE/mocks/code.ts
  mage_ai/frontend/components/v2/IDE/shortcuts/index.ts
  mage_ai/frontend/components/v2/IDE/themes/base.ts
  mage_ai/frontend/components/v2/IDE/themes/index.ts
  mage_ai/frontend/components/v2/IDE/themes/interfaces.ts
  mage_ai/frontend/components/v2/IDE/themes/setup.ts
  mage_ai/frontend/components/v2/Layout/index.tsx
  mage_ai/frontend/mana/styles/mixins.ts
  mage_ai/frontend/mana/styles/typography.ts
  mage_ai/frontend/mana/themes/fonts.ts
  mage_ai/frontend/mana/themes/interfaces.ts
  mage_ai/frontend/next.common.config.js
  mage_ai/frontend/next.config.js
  mage_ai/frontend/next_base_path.config.js
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/pages/v2/editor.tsx
  mage_ai/frontend/public/fonts/codicon/codicon.ttf
  mage_ai/frontend/scripts/install_and_run.sh
  mage_ai/frontend/styles/globals.css
  mage_ai/server/data/models.py
  mage_ai/server/server.py
  mage_ai/server/static/__init__.py
  mage_ai/server/static/files.py
  scripts/test.sh
Labels: enhancement

#5161 [xy] Fix auto_clean_name param.
  mage_ai/io/base.py
Labels: bug

#5162 [xy] Bump the version of dbt-sqlserver to 1.7.4
  requirements.txt
  setup.py
Labels: bug

#5165 [xy] Allow configuring custom owner credentials.
  docs/production/authentication/overview.mdx
  mage_ai/server/server.py
  mage_ai/settings/server.py
  mage_ai/tests/server/test_server.py
Labels: enhancement

#5167 [xy] Fix api trigger token comparison.
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#5166 [xy] Allow configuring AZURE_HOST for authentication.
  mage_ai/authentication/providers/active_directory.py
  mage_ai/settings/keys/auth.py
Labels: enhancement

#5171 [cf] added link to backfill guide
  docs/orchestration/backfills/guides.mdx
Labels: documentation

#5173 [td] Update Snowflake timeout to network_timeout
  mage_ai/io/snowflake.py
Labels: bug

#5175 [xy] Fix executor type when not specified.
  mage_ai/data_preparation/executors/executor_factory.py
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#5176 [xy] Upgrade polars package version
  mage_integrations/mage_integrations/sources/api/__init__.py
  requirements.txt
Labels: enhancement

#5168 [td] Grid layout v2
  mage_ai/frontend/components/v2/AppContainer/Cell/index.tsx
  mage_ai/frontend/components/v2/AppContainer/index.tsx
  mage_ai/frontend/components/v2/AppContainer/interfaces.ts
  mage_ai/frontend/components/v2/AppLayout/index.style.tsx
  mage_ai/frontend/components/v2/AppLayout/index.tsx
  mage_ai/frontend/components/v2/Apps/Editor/index.tsx
  mage_ai/frontend/components/v2/Route.tsx
  mage_ai/frontend/mana/components/Container/Col/index.tsx
  mage_ai/frontend/mana/components/Container/Row/index.style.tsx
  mage_ai/frontend/mana/components/Container/Row/index.tsx
  mage_ai/frontend/mana/components/Container/index.tsx
  mage_ai/frontend/mana/components/Grid/Cell/index.tsx
  mage_ai/frontend/mana/components/Grid/Col/index.tsx
  mage_ai/frontend/mana/components/Grid/Row/index.tsx
  mage_ai/frontend/mana/components/Grid/index.style.tsx
  mage_ai/frontend/mana/components/Grid/index.tsx
  mage_ai/frontend/mana/components/Tag/index.tsx
  mage_ai/frontend/mana/elements/Button/Group.tsx
  mage_ai/frontend/mana/elements/Button/index.tsx
  mage_ai/frontend/mana/elements/Input/TextInput/index.tsx
  mage_ai/frontend/mana/elements/Section/index.tsx
  mage_ai/frontend/mana/hooks/useWithLogging.tsx
  mage_ai/frontend/mana/icons/index.tsx
  mage_ai/frontend/mana/styles/borders.ts
  mage_ai/frontend/mana/styles/buttons.ts
  mage_ai/frontend/mana/styles/inputs.ts
  mage_ai/frontend/mana/styles/mixins.ts
  mage_ai/frontend/mana/styles/typography.ts
  mage_ai/frontend/mana/themes/borders.ts
  mage_ai/frontend/mana/themes/build.ts
  mage_ai/frontend/mana/themes/buttons.ts
  mage_ai/frontend/mana/themes/colors.ts
  mage_ai/frontend/mana/themes/fonts.ts
  mage_ai/frontend/mana/themes/gradients.ts
  mage_ai/frontend/mana/themes/grid.ts
  mage_ai/frontend/mana/themes/helpers.ts
  mage_ai/frontend/mana/themes/inputs.ts
  mage_ai/frontend/mana/themes/interactive.ts
  mage_ai/frontend/mana/themes/margin.ts
  mage_ai/frontend/mana/themes/utils.ts
  mage_ai/frontend/mana/utils/scrollbar.ts
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/pages/v2/grid.tsx
  mage_ai/frontend/pages/v2/index.tsx
  mage_ai/frontend/utils/elements.ts
Labels: enhancement

#5187 [xy] Speed up Pipeline get and list.
  mage_ai/api/resources/PipelineResource.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/cache/mem_lru.py
  mage_ai/cache/ttl.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_combos.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_factory.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/tests/data_preparation/test_variable_manager.py
  requirements.txt
Labels: enhancement

#5188 [xy] Speed up autocomplete endpoint with cache.
  mage_ai/autocomplete/utils.py
Labels: enhancement

#5189 [td] Browser items API
  mage_ai/api/policies/BrowserItemPolicy.py
  mage_ai/api/policies/CodeExecutionPolicy.py
  mage_ai/api/presenters/BrowserItemPresenter.py
  mage_ai/api/resources/BaseResource.py
  mage_ai/api/resources/BrowserItemResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/server/server.py
  mage_ai/shared/files.py
  mage_ai/system/browser/__init__.py
  mage_ai/system/browser/models.py
Labels: enhancement

#5190 [td] Disable playright, never finishes no windows server 3.10
  .github/workflows/build_and_test.yml
Labels: bug

#5193 [td] Canvas V2
  mage_ai/frontend/.eslintrc.js
  mage_ai/frontend/components/v2/Apps/Container/index.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilder/index.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilder/mock.ts
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Connections/ConnectionLine.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Connections/ConnectionLines.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Connections/interfaces.ts
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Connections/utils.ts
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Nodes/Node.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/Nodes/index.style.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/index.style.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/index.tsx
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/utils/blocks.ts
  mage_ai/frontend/components/v2/Apps/PipelineBuilderCanvas/utils/positioning.ts
  mage_ai/frontend/components/v2/Canvas/Draggable/DraggableBlock.tsx
  mage_ai/frontend/components/v2/Canvas/Draggable/DraggablePort.tsx
  mage_ai/frontend/components/v2/Canvas/Draggable/Preview/BlockDragPreview.tsx
  mage_ai/frontend/components/v2/Canvas/Draggable/utils.ts
  mage_ai/frontend/components/v2/Canvas/Layers/DragLayer.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/Block.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/BlockNode.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/types.ts
  mage_ai/frontend/components/v2/Canvas/interfaces.ts
  mage_ai/frontend/components/v2/Canvas/types.ts
  mage_ai/frontend/components/v2/Canvas/utils/snapToGrid.ts
  mage_ai/frontend/components/v2/Canvas/utils/throttle.ts
  mage_ai/frontend/mana/components/Grid/index.style.tsx
  mage_ai/frontend/mana/components/Grid/index.tsx
  mage_ai/frontend/mana/hocs/withStyles.tsx
  mage_ai/frontend/mana/hooks/useZoomPan.tsx
  mage_ai/frontend/mana/shared/types.ts
  mage_ai/frontend/next.common.config.js
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/v2/canvas.tsx
  mage_ai/frontend/styles/scss/base/_typography.scss
  mage_ai/frontend/styles/scss/components/Canvas/Node/Node.module.scss
  mage_ai/frontend/styles/scss/components/Grid/Grid.module.scss
  mage_ai/frontend/styles/scss/components/Text/Text.module.scss
  mage_ai/frontend/styles/scss/layout/Canvas/Nodes/Node.module.scss
  mage_ai/frontend/styles/scss/layout/Canvas/Paths/ConnectionsPath.module.scss
  mage_ai/frontend/styles/scss/layout/Canvas/Pipelines/Builder.module.scss
  mage_ai/frontend/styles/scss/pages/PipelineBuilder/Main.module.scss
  mage_ai/frontend/utils/string.ts
Labels: feature

#5174 Support custom python sink in Streaming pipeline
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/templates/data_exporters/streaming/generic_python.py
  mage_ai/data_preparation/templates/template.py
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/sinks/base.py
  mage_ai/streaming/sinks/base_python.py
  mage_ai/streaming/sinks/sink_factory.py
Labels: feature

#5195 [xy] Custom kubernetes job prefix
  mage_ai/data_preparation/executors/k8s_block_executor.py
  mage_ai/data_preparation/executors/k8s_pipeline_executor.py
  mage_ai/settings/server.py
  mage_ai/tests/data_preparation/models/test_pipeline.py
Labels: enhancement

#5205 [xy] Fix global data product in single project.
  mage_ai/data_preparation/models/global_data_product/__init__.py
Labels: bug

#5203 [cf] Global Hooks Docs
  docs/mint.json
  docs/orchestration/global-hooks/guides.mdx
  docs/orchestration/global-hooks/overview.mdx
Labels: documentation

#5206 [xy] Try using xlarge in circleci.
  .circleci/config.yml
Labels: enhancement

#5207 [td] Revert Next _app back before breaking change
  .github/workflows/build_and_test.yml
  mage_ai/frontend/pages/_app.tsx
Labels: bug

#5209 [CF] AWS Secrets Manager Docs Update
  docs/production/deploying-to-cloud/secrets/AWS.mdx
Labels: documentation

#5210 [xy] Some small fixes on the docs.
  docs/development/observability/logging.mdx
  docs/integrations/observability/alerting-discord.mdx
  docs/integrations/observability/alerting-email.mdx
  docs/integrations/observability/alerting-slack.mdx
  docs/integrations/observability/alerting-telegram.mdx
Labels: documentation

#5222 [td] Fix editor v2 page
  mage_ai/frontend/components/NextAppV1/index.tsx
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/styles/scss/base/_grid.scss
Labels: bug

#5227 [td] Menus and more
  mage_ai/frontend/components/NextAppV2/index.tsx
  mage_ai/frontend/components/v2/Apps/Browser/System/index.tsx
  mage_ai/frontend/components/v2/Apps/Manager.tsx
  mage_ai/frontend/components/v2/Apps/PipelineCanvas/index.tsx
  mage_ai/frontend/components/v2/Apps/PipelineCanvas/utils/nodes.ts
  mage_ai/frontend/components/v2/Canvas/Connections/ConnectionLines.tsx
  mage_ai/frontend/components/v2/Canvas/Connections/utils.ts
  mage_ai/frontend/components/v2/Canvas/Draggable/BlockNode.tsx
  mage_ai/frontend/components/v2/Canvas/Draggable/DraggablePort.tsx
  mage_ai/frontend/components/v2/Canvas/Draggable/Preview/BlockDragPreview.tsx
  mage_ai/frontend/components/v2/Canvas/Layers/DragLayer.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/BlockNode.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/BlockNodeWrapper.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/Blocks/Aside.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/Blocks/Connection.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/NodeWrapper.tsx
  mage_ai/frontend/components/v2/Canvas/Nodes/types.ts
  mage_ai/frontend/components/v2/Canvas/utils/rect.ts
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/PipelineExecutionFramework/rag/dataPreparation.ts
  mage_ai/frontend/mana/components/Menu/index.style.tsx
  mage_ai/frontend/mana/components/Menu/index.tsx
  mage_ai/frontend/mana/components/Menu/interfaces.ts
  mage_ai/frontend/mana/components/Menu/types.ts
  mage_ai/frontend/mana/elements/Button/index.tsx
  mage_ai/frontend/mana/elements/PanelRows.tsx
  mage_ai/frontend/mana/elements/Path.tsx
  mage_ai/frontend/mana/hooks/shortcuts/interfaces.ts
  mage_ai/frontend/mana/hooks/shortcuts/types.ts
  mage_ai/frontend/mana/hooks/shortcuts/useKeyboardShortcuts.tsx
  mage_ai/frontend/mana/hooks/useContextMenu.tsx
  mage_ai/frontend/mana/hooks/useZoomPan.tsx
  mage_ai/frontend/mana/shared/enums.ts
  mage_ai/frontend/mana/shared/interfaces.ts
  mage_ai/frontend/mana/styles/buttons.ts
  mage_ai/frontend/mana/styles/mixins.ts
  mage_ai/frontend/mana/themes/menus.ts
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/styles/scss/apps/Canvas/Pipelines/Builder.module.scss
  mage_ai/frontend/styles/scss/base/_grid.scss
  mage_ai/frontend/styles/scss/components/Canvas/Nodes/BlockNode.module.scss
Labels: enhancement

#5230 Models and API for execution framework
  mage_ai/api/policies/ExecutionFrameworkPolicy.py
  mage_ai/api/presenters/ExecutionFrameworkPresenter.py
  mage_ai/api/resources/ExecutionFrameworkResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/frameworks/__init__.py
  mage_ai/frameworks/execution/__init__.py
  mage_ai/frameworks/execution/constants.py
  mage_ai/frameworks/execution/llm/__init__.py
  mage_ai/frameworks/execution/llm/rag/__init__.py
  mage_ai/frameworks/execution/llm/rag/base.py
  mage_ai/frameworks/execution/llm/rag/blocks/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/export/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/index/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/templates/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/templates/ingest/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/templates/ingest/configurations.yaml
  mage_ai/frameworks/execution/llm/rag/blocks/query_processing/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/response_generation/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/retrieval/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/embed/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/embed/configurations.yaml
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/tokenization/__init__.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/tokenization/configurations.yaml
  mage_ai/frameworks/execution/llm/rag/mocks/__init__.py
  mage_ai/frameworks/execution/llm/rag/mocks/pipeline.json
  mage_ai/frameworks/execution/llm/rag/mocks/pipelines.json
  mage_ai/frameworks/execution/llm/rag/pipelines/__init__.py
  mage_ai/frameworks/execution/llm/rag/pipelines/data_preparation.py
  mage_ai/frameworks/execution/llm/rag/pipelines/inference.py
  mage_ai/frameworks/execution/models/__init__.py
  mage_ai/frameworks/execution/models/base.py
  mage_ai/frameworks/execution/models/block/__init__.py
  mage_ai/frameworks/execution/models/block/adapter.py
  mage_ai/frameworks/execution/models/block/base.py
  mage_ai/frameworks/execution/models/block/models.py
  mage_ai/frameworks/execution/models/enums.py
  mage_ai/frameworks/execution/models/pipeline/__init__.py
  mage_ai/frameworks/execution/models/pipeline/adapter.py
  mage_ai/frameworks/execution/models/pipeline/base.py
  mage_ai/frameworks/execution/models/pipeline/constants.py
  mage_ai/frontend/components/v2/Apps/PipelineCanvas/index.tsx
  mage_ai/shared/models.py
Labels: enhancement

#5231 [td] Pipeline execution framework CRUD API
  mage_ai/api/operations/base.py
  mage_ai/api/policies/ExecutionFrameworkPolicy.py
  mage_ai/api/policies/PipelineExecutionFrameworkPolicy.py
  mage_ai/api/presenters/BasePresenter.py
  mage_ai/api/presenters/ExecutionFrameworkPresenter.py
  mage_ai/api/presenters/PipelineExecutionFrameworkPresenter.py
  mage_ai/api/resources/BaseResource.py
  mage_ai/api/resources/ExecutionFrameworkResource.py
  mage_ai/api/resources/PipelineExecutionFrameworkResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/cache/utils.py
  mage_ai/data_preparation/models/block/block_factory.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frameworks/execution/llm/rag/blocks/export/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/index/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/load/templates/ingest/configurations.yaml
  mage_ai/frameworks/execution/llm/rag/blocks/query_processing/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/response_generation/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/retrieval/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/groups.py
  mage_ai/frameworks/execution/llm/rag/blocks/transform/templates/tokenization/configurations.yaml
  mage_ai/frameworks/execution/llm/rag/mocks/pipeline.yaml
  mage_ai/frameworks/execution/llm/rag/mocks/pipelines.yaml
  mage_ai/frameworks/execution/models/block/adapter.py
  mage_ai/frameworks/execution/models/block/base.py
  mage_ai/frameworks/execution/models/block/models.py
  mage_ai/frameworks/execution/models/pipeline/adapter.py
  mage_ai/frameworks/execution/models/pipeline/base.py
  mage_ai/presenters/interactions/models.py
  mage_ai/shared/files.py
  mage_ai/shared/models.py
Labels: feature

#5236 [xy] Resolve CVE-2024-35225
  requirements.txt
Labels: security

#5237 [jk] Add specific lodash dependency version
  mage_ai/frontend/package.json
Labels: bug
