Repository mage-ai/mage-ai, pull requests merged in 2024-01, with the labels that each got.

#4270 [td] Add API for projects
  mage_ai/api/policies/VersionControlBranchPolicy.py
  mage_ai/api/policies/VersionControlFilePolicy.py
  mage_ai/api/policies/VersionControlProjectPolicy.py
  mage_ai/api/policies/VersionControlRemotePolicy.py
  mage_ai/api/presenters/VersionControlBranchPresenter.py
  mage_ai/api/presenters/VersionControlFilePresenter.py
  mage_ai/api/presenters/VersionControlProjectPresenter.py
  mage_ai/api/presenters/VersionControlRemotePresenter.py
  mage_ai/api/resources/VersionControlBranchResource.py
  mage_ai/api/resources/VersionControlFileResource.py
  mage_ai/api/resources/VersionControlProjectResource.py
  mage_ai/api/resources/VersionControlRemoteResource.py
  mage_ai/authentication/permissions/constants.py
  mage_ai/version_control/models.py
Labels: feature

#4271 [xy] Save statistics.json in correct execution partition folder.
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4275 [xy] Fix syncing MySQL TIME type
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
  mage_integrations/mage_integrations/utils/parsers.py
Labels: bug

#4277 [xy] Decrease image size by removing qdrant libraries
  docs/integrations/databases/Qdrant.mdx
  mage_ai/data_preparation/templates/data_exporters/qdrant.py
  mage_ai/data_preparation/templates/data_loaders/qdrant.py
  requirements.txt
  setup.py
Labels: enhancement

#4262 [dy] Update git to set username and email when using version control
  mage_ai/api/policies/GitBranchPolicy.py
  mage_ai/api/presenters/GitBranchPresenter.py
  mage_ai/api/presenters/GitCustomBranchPresenter.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/GitCustomBranchResource.py
  mage_ai/api/resources/OauthResource.py
  mage_ai/api/resources/PullRequestResource.py
  mage_ai/authentication/oauth/constants.py
  mage_ai/authentication/providers/active_directory.py
  mage_ai/authentication/providers/bitbucket.py
  mage_ai/authentication/providers/constants.py
  mage_ai/authentication/providers/ghe.py
  mage_ai/authentication/providers/google.py
  mage_ai/authentication/providers/okta.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/api.py
  mage_ai/data_preparation/git/clients/base.py
  mage_ai/data_preparation/git/clients/github.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/frontend/components/VersionControl/Branches/index.tsx
  mage_ai/frontend/components/VersionControl/Commit/index.tsx
  mage_ai/frontend/components/VersionControl/GitActions.tsx
  mage_ai/frontend/components/VersionControl/Remote/Authentication.tsx
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/shared/strings.py
  mage_ai/tests/data_preparation/git/test_api.py
Labels: enhancement

#4278 [td] Fix the way we store pipelines by type in the cache
  mage_ai/cache/pipeline.py
  mage_ai/cache/tag.py
  mage_ai/cache/utils.py
  mage_ai/frontend/components/Dashboard/index.tsx
Labels: bug

#4282 [td] Fix dashboard resizing
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/frontend/components/Dashboard/index.tsx
Labels: bug

#4283 [jk] Use utc date for trigger start date
  mage_ai/frontend/components/Triggers/utils.ts
Labels: bug

#4284 [td] Fix requestIdleCallback not supported on Safari
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/requestIdleCallbackPolyfill.ts
Labels: bug

#4289 Upgraded Google ads version from 14 to 15
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/streams.py
Labels: bug, python, data integration

#4290 [xy] Wrap mssql table name with double quotes in data integration pipeline
  mage_integrations/mage_integrations/sources/mssql/__init__.py
Labels: bug

#4292 [jk] Display correct default start datetime when editing trigger/backfill
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/components/Triggers/utils.ts
Labels: bug

#4293 [dy] Only set the schema in the DB when the server is started
  mage_ai/orchestration/db/__init__.py
  mage_ai/server/server.py
Labels: bug

#4280 [dy] Pass in query_vars as a dict
  mage_ai/io/postgres.py
Labels: bug

#4296 [xy] Wrap block run initialization logic with lock.
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
Labels: bug

#4294 [xy] Escape bigquery project name in sql block.
  mage_ai/io/bigquery.py
Labels: bug

#4279 [mp] Broken Links
  docs/development/variables/referencing-variables.mdx
Labels: documentation

#4297 [xy] Allow building image with feature branch
  .github/workflows/publish_docker_image.yml
  Dockerfile
Labels: enhancement

#4300 [jk] Fix several bugs on Pipelines dashboard
  mage_ai/api/resources/PipelineResource.py
  mage_ai/cache/utils.py
  mage_ai/frontend/components/shared/Table/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/tests/cache/example_pipeline.json
  mage_ai/tests/cache/pipeline_details_mapping_template
  mage_ai/tests/cache/test_pipeline_cache.py
Labels: bug

#4295 [td] Fix dynamic block + dynamic child blocks spawning other blocks
  docker-compose.yml
  mage_ai/api/logging.py
  mage_ai/data_preparation/executors/azure_container_instance_executor.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/executors/ecs_block_executor.py
  mage_ai/data_preparation/executors/executor_factory.py
  mage_ai/data_preparation/executors/gcp_cloud_run_block_executor.py
  mage_ai/data_preparation/executors/k8s_block_executor.py
  mage_ai/data_preparation/executors/pyspark_block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/dbt_adapter.py
  mage_ai/data_preparation/models/block/dbt/profiles.py
  mage_ai/data_preparation/models/block/dynamic/constants.py
  mage_ai/data_preparation/models/block/dynamic/dynamic_child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/pages/_app.tsx
  mage_ai/orchestration/db/__init__.py
  mage_ai/orchestration/db/cache.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
  mage_ai/server/logger.py
  mage_ai/shared/custom_logger.py
  mage_ai/shared/environments.py
  mage_ai/shared/parsers.py
  mage_ai/tests/api/operations/base/test_base_with_user_permissions.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/models/block/dynamic/test.json
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_child_block_factory.py
  mage_ai/tests/data_preparation/models/block/test_utils.py
  mage_ai/tests/orchestration/test_pipeline_scheduler_project_platform.py
  scripts/dev.sh
Labels: bug

#4303 [td] Add execute raw SQL without preprocessing to all loaders
  mage_ai/api/resources/BlockResource.py
  mage_ai/cache/block_action_object/__init__.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/io/base.py
  mage_ai/io/bigquery.py
  mage_ai/io/clickhouse.py
  mage_ai/io/druid.py
  mage_ai/io/pinot.py
  mage_ai/io/snowflake.py
  mage_ai/io/spark.py
  mage_ai/io/sql.py
Labels: enhancement

#4307 [td] Use absolute paths
  mage_ai/api/resources/FileResource.py
  mage_ai/api/resources/FolderResource.py
  mage_ai/cache/block_action_object/__init__.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
  mage_ai/data_preparation/models/block/dbt/profiles.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/data_preparation/models/file.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/CodeBlockV2/Editor/index.tsx
  mage_ai/frontend/components/CodeBlockV2/dbt/Configuration/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileEditor/utils.ts
  mage_ai/frontend/components/FileSelectorPopup/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/settings/platform/__init__.py
  mage_ai/shared/files.py
  mage_ai/shared/path_fixer.py
  mage_ai/tests/api/endpoints/test_blocks.py
  mage_ai/tests/base_test.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_sql.py
  mage_ai/tests/data_preparation/models/block/dbt/test_block_yaml.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_adapter.py
  mage_ai/tests/data_preparation/models/block/dbt/test_dbt_cli.py
  mage_ai/tests/data_preparation/models/block/dbt/test_profiles.py
  mage_ai/tests/data_preparation/models/block/dbt/test_project.py
  mage_ai/tests/data_preparation/models/block/dbt/test_sources.py
  mage_ai/tests/data_preparation/models/block/platform/test_mixins.py
Labels: enhancement

#4310 [xy] Add BigQuery permissions to docs.
  docs/integrations/databases/BigQuery.mdx
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/sources/bigquery/README.md
Labels: bug, documentation

#4309 [td] Improve UI in several areas
  mage_ai/api/resources/SearchResultResource.py
  mage_ai/command_center/blocks/utils.py
  mage_ai/command_center/pipelines/factory.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/FileEditor/index.tsx
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/v2/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
  mage_ai/frontend/oracle/elements/Link/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/frontend/storage/localStorage.ts
  mage_ai/frontend/storage/serverTime.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/useGlobalKeyboardShortcuts.tsx
  mage_ai/frontend/utils/models/blockRun.ts
  mage_ai/services/search/block_action_objects.py
Labels: bug

#4311 [xy] Try preventing creating duplicate pipeline runs in scheduler.
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
Labels: bug

#4312 [td] Fix dragging and dropping file in browser
  mage_ai/frontend/components/FileEditor/utils.ts
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/utils/hooks/keyboardShortcuts/useGlobalKeyboardShortcuts.tsx
Labels: bug

#4315 [td] Fix incremental sync bug with missing arg
  mage_ai/data_preparation/models/block/data_integration/mixins.py
Labels: bug

#4308 [td] Dynamic dynamic child and replicas
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/dynamic_child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/shared/custom_logger.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_helpers.py
Labels: enhancement

#4299 [dy] Use current pod image as the default
  mage_ai/cluster_manager/kubernetes/workload_manager.py
Labels: enhancement

#4316 [dy] Fix git submodule sync
  mage_ai/data_preparation/git/__init__.py
Labels: bug

#4281 [dy] Support serialize Polars dataframe
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/utils.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/storage/base_storage.py
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/storage/s3_storage.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/tests/data_preparation/models/test_variable.py
  requirements.txt
Labels: bug

#4319 [xy] Fix interpolating mage secret in project metadata.yaml
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/settings/repo.py
  mage_ai/tests/data_preparation/models/test_project.py
Labels: bug

#4320 AWS S3 Destination: Added support for IAM role-based authentication.
  mage_integrations/mage_integrations/destinations/amazon_s3/README.md
  mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
Labels: enhancement

#4321 [xy] Speed up pipeline run count query.
  mage_ai/api/resources/PipelineRunResource.py
Labels: enhancement

#4322 [xy] Fix executing data integration block with ecs executor
  mage_ai/data_preparation/executors/ecs_block_executor.py
  mage_ai/services/aws/ecs/config.py
  mage_ai/services/aws/ecs/ecs.py
Labels: bug

#4324 [jk] Remove undefined request
  mage_ai/frontend/components/shared/Header/index.tsx
Labels: bug

#4325 [td] Fix triple layout after width
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
Labels: bug

#4326 [td] Fix reduce output bug
  mage_ai/api/policies/CustomTemplatePolicy.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/frontend/components/Dashboard/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/Triggers/Table.tsx
Labels: bug

#4327 [xy] Fix cannot unpack non-iterable NoneType object
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4329 [td] Add small fixes
  docker-compose.yml
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dbt/block_sql.py
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
  mage_ai/data_preparation/models/block/platform/mixins.py
  mage_ai/frontend/components/CodeBlockV2/Output/index.tsx
  mage_ai/frontend/components/FileEditor/utils.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4332 [td] Add retry info in callbacks and function that’s being retried
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
  mage_ai/shared/retry.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
Labels: enhancement

#4334 [td] If project can’t be found, look directly in the dbt folder
  mage_ai/data_preparation/models/block/dbt/block_yaml.py
Labels: bug

#4165 [mp] Add new tips and tricks
  docs/guides/tips-and-tricks.mdx
Labels: documentation

#4335 [jk] Update file versioning doc
  docs/getting-started/file-versions.mdx
Labels: documentation

#4338 [jk] Fix caching issues with block cache and shared pipelines
  mage_ai/cache/block.py
Labels: bug

#4330 Removing modified google-ads lib
  Dockerfile
  dev.Dockerfile
  dev.spark.Dockerfile
  mage_integrations/mage_integrations/sources/google_ads/tap_google_ads/report_definitions.py
  mage_integrations/requirements.txt
Labels: dependencies, python, data integration

#4341 [td] Fix SQL blocks
  mage_ai/data_preparation/models/block/content.py
Labels: bug

#4340 [xy] Add google cloud storage sink to streaming pipeline.
  docs/mint.json
  docs/streaming/destinations/google-cloud-storage.mdx
  mage_ai/data_preparation/templates/data_exporters/streaming/google_cloud_storage.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/sinks/amazon_s3.py
  mage_ai/streaming/sinks/base_object_storage.py
  mage_ai/streaming/sinks/google_cloud_storage.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/tests/streaming/sinks/test_google_cloud_storage.py
Labels: feature

#4337 [dy] Add bitbucket docs
  docs/production/data-sync/github.mdx
  mage_ai/api/resources/OauthResource.py
Labels: documentation

#4343 [jk] Prevent error when searching for blocks
  mage_ai/services/search/block_action_objects.py
Labels: bug

#4342 [td] Fix callbacks input data from dynamic child blocks
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
Labels: bug

#4346 [td] Enable command center when user auth not required
  mage_ai/frontend/pages/_app.tsx
Labels: bug

#4348 [jk] Improve command center shortcut wording and example
  mage_ai/frontend/components/CommandCenter/constants.tsx
Labels: enhancement

#4347 [jk] Fix bug when searching for block files
  mage_ai/cache/block_action_object/__init__.py
Labels: bug

#4349 [td] Fix dynamic child block getting input data
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/extension/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/shared/parsers.py
Labels: bug

#4345 [dy] Add mapping for active directory roles
  mage_ai/api/resources/SessionResource.py
  mage_ai/authentication/providers/active_directory.py
  mage_ai/settings/__init__.py
  mage_ai/settings/sso.py
  mage_ai/tests/api/endpoints/test_oauths.py
  mage_ai/tests/authentication/__init__.py
  mage_ai/tests/authentication/providers/__init__.py
  mage_ai/tests/authentication/providers/test_active_directory.py
Labels: enhancement

#4353 [jk] Make block type error more descriptive
  mage_ai/api/resources/PipelineResource.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/interfaces/PipelineType.ts
  mage_ai/frontend/pages/pipelines/index.tsx
Labels: enhancement

#3474 Feat: allow user to overwrite SQL types
  docs/integrations/databases/ClickHouse.mdx
  docs/integrations/databases/MicrosoftSQLServer.mdx
  docs/integrations/databases/MySQL.mdx
  docs/integrations/databases/PostgreSQL.mdx
  docs/integrations/databases/Redshift.mdx
  docs/integrations/databases/trino.mdx
  mage_ai/io/clickhouse.py
  mage_ai/io/export_utils.py
  mage_ai/io/mysql.py
  mage_ai/io/redshift.py
  mage_ai/io/sql.py
  mage_ai/io/trino.py
  mage_ai/tests/io/create_table/__init__.py
  mage_ai/tests/io/create_table/test_mssql.py
  mage_ai/tests/io/create_table/test_mysql.py
  mage_ai/tests/io/create_table/test_postgresql.py
  mage_ai/tests/io/create_table/test_redshift.py
  mage_ai/tests/io/create_table/test_trino.py
Labels: feature, python

#4359 [jk] Fix cron expression conversion when using local midnight time
  mage_ai/frontend/components/Triggers/utils.ts
Labels: bug

#4360 [td] Fix block search
  mage_ai/services/search/block_action_objects.py
Labels: bug

#4361 [td] Fix command center hiding
  mage_ai/command_center/factory.py
  mage_ai/command_center/version_control/factory.py
  mage_ai/frontend/components/CommandCenter/ItemRow/index.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/pages/test.tsx
Labels: bug

#4362 [td] Upgrade app layout behavior
  mage_ai/frontend/components/ApplicationManager/Header/index.tsx
  mage_ai/frontend/components/ApplicationManager/index.style.tsx
  mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
  mage_ai/frontend/components/CommandCenter/index.style.tsx
  mage_ai/frontend/components/FileEditor/Header/index.tsx
  mage_ai/frontend/components/PipelineDetail/StatusFooter/index.tsx
  mage_ai/frontend/components/VersionControlFileDiffs/index.tsx
  mage_ai/frontend/interfaces/ElementType.ts
  mage_ai/frontend/storage/ApplicationManager/cache.ts
  mage_ai/frontend/storage/ApplicationManager/constants.ts
  mage_ai/frontend/utils/elements.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/utils.ts
  mage_ai/frontend/utils/string.ts
  mage_ai/frontend/utils/useDraggableElement.ts
  mage_ai/frontend/utils/useResizeElement.ts
Labels: enhancement

#4363 [td] Fix GDP and add terminal colors
  mage_ai/command_center/files/constants.py
  mage_ai/command_center/pipelines/constants.py
  mage_ai/command_center/triggers/utils.py
  mage_ai/command_center/version_control/branches/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/global_data_product/__init__.py
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/server/terminal_server.py
  mage_ai/server/websockets/terminal.py
  mage_ai/server/websockets/terminal/__init__.py
  mage_ai/server/websockets/terminal/server.py
  mage_ai/server/websockets/terminal/utils.py
  mage_ai/tests/data_preparation/models/test_global_data_product.py
Labels: bug

#4365 [td] Create terminal app
  mage_ai/command_center/applications/factory.py
  mage_ai/command_center/applications/utils.py
  mage_ai/command_center/constants.py
  mage_ai/frontend/components/ApplicationManager/index.style.tsx
  mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
  mage_ai/frontend/components/Applications/PortalTerminal/index.tsx
  mage_ai/frontend/components/CommandCenter/ItemRow/constants.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
  mage_ai/frontend/components/Terminal/index.style.tsx
  mage_ai/frontend/components/Terminal/index.tsx
  mage_ai/frontend/components/Terminal/useTerminal/constants.ts
  mage_ai/frontend/components/Terminal/useTerminal/index.tsx
  mage_ai/frontend/components/Terminal/useTerminal/storage.ts
  mage_ai/frontend/interfaces/CommandCenterType.ts
  mage_ai/frontend/interfaces/KernelOutputType.ts
  mage_ai/frontend/pages/terminal/index.tsx
  mage_ai/frontend/utils/events/constants.ts
  mage_ai/frontend/utils/hooks/keyboardShortcuts/utils.ts
  mage_ai/server/terminal_server.py
  mage_ai/server/websockets/terminal/utils.py
Labels: feature

#4367 [td] Minor tweaks to existing apps
  mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx
  mage_ai/frontend/components/Terminal/useTerminal/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/utils/events/constants.ts
Labels: bug

#4354 Added 'custom_fields' to freshdesk source
  mage_integrations/mage_integrations/sources/freshdesk/tap_freshdesk/schemas/tickets.json
Labels: bug, python, data integration

#4374 [xy] Support overwriting column types in BigQuery.
  docs/integrations/databases/BigQuery.mdx
  mage_ai/io/bigquery.py
Labels: enhancement

#4375 [xy] Fix creating widget.
  mage_ai/api/resources/WidgetResource.py
Labels: bug

#4376 [dy] Lowercase auth_type enum
  mage_ai/data_preparation/preferences.py
  mage_ai/server/server.py
Labels: bug

#4377 [dy] Update cloud run workspace
  mage_ai/cluster_manager/constants.py
  mage_ai/cluster_manager/gcp/cloud_run_service_manager.py
  mage_ai/cluster_manager/workspace/cloud_run.py
Labels: bug

#4336 [dy] Support JSON logging
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/server/logger.py
  mage_ai/server/scheduler_manager.py
  mage_ai/server/server.py
  mage_ai/settings/__init__.py
  mage_ai/shared/logger.py
Labels: enhancement

#4382 [td] Show multiple outputs and fix downstream dynamic child block inputs and outputs
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/MultiOutput.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.style.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/useCodeOutput.tsx
  mage_ai/frontend/components/PipelineDetail/BlockRuns/buildTableSidekick.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/KernelOutputType.ts
  mage_ai/server/utils/output_display.py
  mage_ai/server/websocket_server.py
  mage_ai/shared/custom_logger.py
Labels: bug, feature

#4384 [xy] Update doc about caching block output in memory and troubleshooting
  docs/design/data-pipeline-management.mdx
  docs/development/troubleshooting.mdx
Labels: documentation

#4389 [dy] Fix terminal
  mage_ai/frontend/components/Terminal/useTerminal/index.tsx
Labels: bug

#4388 [td] Update dynamic block output and input data logic
  mage_ai/api/resources/BlockResource.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/MultiOutput.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/presenters/blocks/__init__.py
  mage_ai/presenters/blocks/graph.py
  mage_ai/server/utils/output_display.py
  mage_ai/shared/custom_logger.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_block_and_dynamic_child_block.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_blocks_and_upstream_dynamic_child_blocks.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_blocks_upstream_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple_level2.json
  mage_ai/tests/data_preparation/models/block/dynamic/dynamic_child_block_multiple_levels.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_level1.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_level1_multiple.json
  mage_ai/tests/data_preparation/models/block/dynamic/multiple_dynamic_reduce_output_multiple_levels.json
  mage_ai/tests/data_preparation/models/block/dynamic/test.json
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_child_block_factory.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_helpers.py
Labels: bug, enhancement

#4392 [td] custom design docs
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/shared/custom_logger.py
Labels: documentation

#4393 [td] Add multi-project
  docker-compose.yml
  docs/dbt/developer-experience.mdx
  docs/mint.json
  docs/platform/designs/setup.mdx
  docs/platform/overview.mdx
  docs/platform/projects/management.mdx
  mage_ai/server/utils/output_display.py
  mage_ai/settings/__init__.py
  mage_ai/settings/platform/__init__.py
  mage_ai/settings/platform/constants.py
  mage_ai/tests/data_preparation/models/global_hooks/test_hook.py
  mage_ai/tests/data_preparation/models/test_project.py
  mage_ai/tests/data_preparation/shared/test_secrets.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/settings/test_platform.py
  scripts/dev.sh
Labels: documentation

#4397 [td] Fix dynamic block conditionals in runs and in notebook
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/orchestration/db/models/schedules.py
Labels: bug

#4398 [td] Remove terminal colors because the commands freeze pip installed Mage
  mage_ai/server/terminal_server.py
  mage_ai/server/websockets/terminal/server.py
  mage_ai/server/websockets/terminal/utils.py
Labels: bug

#4400 [td] Fix reduce output block tests
  mage_ai/data_preparation/executors/pipeline_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/utils/array.ts
  mage_ai/presenters/blocks/graph.py
  mage_ai/server/utils/output_display.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_dynamic_helpers.py
Labels: bug

#4306 [edw] e2e test for `/pipelines`
  docs/contributing/backend/testing/overview.mdx
  docs/contributing/frontend/testing.mdx
  docs/mint.json
  mage_ai/frontend/package.json
  mage_ai/frontend/playwright.config.ci.ts
  mage_ai/frontend/playwright.config.ts
  mage_ai/frontend/tests/base.ts
  mage_ai/frontend/tests/basic.spec.ts
  mage_ai/frontend/tests/pipelines.spec.ts
  mage_ai/frontend/yarn.lock
Labels: testing

#4399 [dy] Fix LDAP unpacking
  mage_ai/api/resources/SessionResource.py
  mage_ai/authentication/ldap.py
Labels: bug

#4408 [td] Speed up monitor stats and reduce calls on overview
  mage_ai/api/policies/ProjectPolicy.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/command_center/applications/constants.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/pipelines/seed.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/project/constants.py
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/pages/overview/index.tsx
  mage_ai/frontend/pages/pipelines/index.tsx
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/orchestration/db/constants.py
  mage_ai/orchestration/db/functions.py
  mage_ai/orchestration/monitor/monitor_stats.py
  mage_ai/usage_statistics/constants.py
  mage_ai/usage_statistics/logger.py
Labels: bug

#4409 [td] Fix reduce output and triple layout saving
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
Labels: bug

#4411 [td] Fix filebrowser bug and git push bug
  docs/developer-ux/avatar.mdx
  docs/developer-ux/file-browser.mdx
  docs/developer-ux/overview.mdx
  docs/mint.json
  mage_ai/data_preparation/git/api.py
  mage_ai/frontend/components/FileVersions/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/users/UserDetail.tsx
  mage_ai/frontend/pages/settings/account/profile.tsx
  mage_ai/frontend/pages/settings/workspace/users/[...slug].tsx
Labels: bug

#4412 [td] Fix serializing list and dict when formatting output
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4413 [td] Code editor features docs
  docs/data-integrations/batch-pipelines.mdx
  docs/developer-ux/avatar.mdx
  docs/developer-ux/block-dependency-tree.mdx
  docs/developer-ux/code-editor.mdx
  docs/mint.json
  mage_ai/ai/generator.py
  mage_ai/ai/llm_pipeline_wizard.py
  mage_ai/frontend/components/CommandCenter/ApplicationItemDetail/index.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/PipelineDetail/BlocksInPipeline/index.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/components/TripleLayout/index.style.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/presenters/design/models.py
  mage_ai/services/search/block_action_objects.py
Labels: documentation

#4414 [td] Sidekick docs
  docs/developer-ux/avatar.mdx
  docs/developer-ux/overview.mdx
  docs/developer-ux/personalize.mdx
  docs/developer-ux/sidekick.mdx
  docs/integrations/databases/MicrosoftSQLServer.mdx
  docs/mint.json
  docs/platform/designs/setup.mdx
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/frontend/components/CommandCenter/index.tsx
Labels: documentation

#4415 [td] Add docs for command center
  docs/developer-ux/code-editor.mdx
  docs/developer-ux/command-center/spellcaster.mdx
  docs/developer-ux/overview.mdx
  docs/development/updating-mage.mdx
  docs/mint.json
  mage_ai/command_center/triggers/utils.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/frontend/components/CommandCenter/constants.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/frontend/utils/hooks/keyboardShortcuts/constants.ts
  mage_ai/presenters/blocks/graph.py
Labels: documentation

#4416 [td] Version Control mode docs
  docs/developer-ux/command-center/modes/version-control.mdx
  docs/mint.json
  mage_ai/command_center/version_control/branches/utils.py
  mage_ai/command_center/version_control/projects/utils.py
  mage_ai/frontend/components/CommandCenter/index.style.tsx
  mage_ai/frontend/components/shared/SetupSection/SetupSectionRow.tsx
  mage_ai/orchestration/monitor/monitor_stats.py
  mage_ai/version_control/models.py
Labels: documentation

#4417 [td] Add docs for applications and debug flags to debug dynamic blocks
  docs/developer-ux/applications/arcane-library.mdx
  docs/developer-ux/applications/overview.mdx
  docs/developer-ux/applications/portal-terminal.mdx
  docs/mint.json
  mage_ai/frontend/components/BlockBrowser/FileBrowserNavigation/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/VersionControl/index.tsx
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/pages/manage/files/index.tsx
  mage_ai/server/utils/output_display.py
Labels: documentation

#4418 [td] Add more docs on apps
  docs/developer-ux/applications/overview.mdx
Labels: documentation

#4419 [td] Complete docs for arcane library
  docs/developer-ux/applications/arcane-library.mdx
  docs/developer-ux/applications/overview.mdx
Labels: documentation

#4407 [xy] Support affinity and tolerations in k8s_executor_config.
  mage_ai/services/k8s/config.py
  mage_ai/services/k8s/job_manager.py
  mage_ai/shared/hash.py
  mage_ai/tests/services/k8s/test_job_manager.py
  mage_ai/tests/shared/test_hash.py
Labels: enhancement

#4426 Update trigger-pipeline.mdx
  docs/orchestration/triggers/trigger-pipeline.mdx
Labels: documentation

#4425 [td] Prevent index out of bounds
  mage_ai/data_preparation/models/block/dynamic/variables.py
Labels: bug

#4427 [td] Remove Couchbase from the dev requirements
  requirements.txt
Labels: dependencies

#4430 [td] Dynamic SQL blocks
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/server/utils/output_display.py
  mage_ai/shared/custom_logger.py
Labels: dynamic block

#4431 [td] Remove test print statements
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/server/utils/output_display.py
Labels: bug

#4424 Removing Draft7 validation from Clickhouse destination
  mage_integrations/mage_integrations/destinations/clickhouse/__init__.py
  mage_integrations/mage_integrations/destinations/clickhouse/target_clickhouse/sinks.py
Labels: bug, python, data integration

#4433 [xy] Bump up dependency versions to resolve vulnerabilities.
  mage_integrations/requirements.txt
  requirements.txt
Labels: enhancement, security

#4435 [xy] Fix global_vars context in pipeline executor.
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/tests/data_preparation/executors/test_block_executor.py
  mage_ai/tests/data_preparation/executors/test_pipeline_executor.py
Labels: bug

#4436 [td] Limit dynamic block output in notebook
  mage_ai/command_center/constants.py
  mage_ai/command_center/pipelines/constants.py
  mage_ai/command_center/pipelines/factory.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/frontend/components/ApplicationManager/Header/index.tsx
  mage_ai/frontend/components/ApplicationManager/index.style.tsx
  mage_ai/frontend/components/Breadcrumbs/index.tsx
  mage_ai/frontend/components/CommandCenter/ApplicationFooter/index.tsx
  mage_ai/frontend/components/CommandCenter/ApplicationForm/index.tsx
  mage_ai/frontend/components/CommandCenter/ItemApplication/constants.ts
  mage_ai/frontend/components/CommandCenter/LaunchKeyboardShortcutText.tsx
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/frontend/components/CommandCenter/useExecuteActions.ts
  mage_ai/frontend/components/CommandCenter/utils.ts
  mage_ai/frontend/components/ServerTimeDropdown/ServerTimeButton.tsx
  mage_ai/frontend/components/shared/Header/index.style.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/interfaces/CommandCenterType.ts
  mage_ai/frontend/oracle/components/Loading/index.tsx
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutButton.tsx
  mage_ai/frontend/oracle/elements/Button/KeyboardShortcutWrapper.tsx
  mage_ai/frontend/oracle/icons/BaseIcon.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/_app.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/events/constants.ts
  mage_ai/frontend/utils/models/project/useProject.ts
  mage_ai/server/utils/output_display.py
Labels: enhancement

#4439 [xy] Update docs for data integration pipelines
  mage_integrations/mage_integrations/destinations/bigquery/README.md
  mage_integrations/mage_integrations/destinations/snowflake/README.md
  mage_integrations/mage_integrations/sources/chargebee/README.md
Labels: documentation

#4440 [td] Fix a few global data product bugs
  mage_ai/api/resources/BlockResource.py
  mage_ai/command_center/constants.py
  mage_ai/data_preparation/models/block/global_data_product/__init__.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/orchestration/triggers/global_data_product.py
  mage_ai/tests/data_preparation/models/block/test_global_data_product.py
  mage_ai/tests/orchestration/triggers/test_global_data_product.py
Labels: bug

#4445 [td] Fix dynamic blocks OOM round 2
  .github/workflows/build_and_test.yml
  Dockerfile
  dev.Dockerfile
  mage_ai/api/resources/DataProviderResource.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/content.py
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/models/block/sql/bigquery.py
  mage_ai/presenters/blocks/graph.py
  mage_ai/shared/memory.py
  mage_ai/tests/shared/test_files.py
  requirements.txt
Labels: bug

#4226 Added kafka streaming source offset and partition options
  docs/streaming/sources/kafka.mdx
  mage_ai/streaming/sources/kafka.py
  mage_ai/tests/streaming/sources/test_kafka.py
Labels: feature, python, streaming

#4447 [td] Improve bigquery name parsing to help fill in full name
  mage_ai/data_preparation/models/block/sql/bigquery.py
  mage_ai/io/bigquery.py
  requirements.txt
Labels: enhancement

#4448 [td] Add error logging
  mage_ai/api/monitors/BaseMonitor.py
  mage_ai/api/operations/base.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/server/api/base.py
  mage_ai/usage_statistics/constants.py
  mage_ai/usage_statistics/logger.py
Labels: enhancement

#4450 [xy] Fix incremental sync in chargebee source
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
  mage_integrations/mage_integrations/sources/chargebee/__init__.py
  mage_integrations/mage_integrations/sources/chargebee/streams/base.py
  mage_integrations/mage_integrations/sources/chargebee/streams/comments.py
  mage_integrations/mage_integrations/sources/chargebee/streams/coupons.py
  mage_integrations/mage_integrations/sources/chargebee/streams/events.py
  mage_integrations/mage_integrations/sources/chargebee/streams/subscriptions.py
Labels: bug

#4454 [td] Don’t count values if is None
  mage_ai/data_preparation/models/block/dynamic/child.py
Labels: bug, dynamic block

#4455 [mp] Add new tips & tricks to docs
  docs/guides/tips-and-tricks.mdx
Labels: documentation

#4452 [mp] update windows command for quickstart
  docs/getting-started/setup.mdx
Labels: documentation

#4456 [td] Fix policy issue updating settings
  mage_ai/api/policies/CommandCenterItemPolicy.py
Labels: bug

#4458 [td] Fix keyboard shortcuts when its empty array
  mage_ai/frontend/components/CommandCenter/index.tsx
  mage_ai/presenters/blocks/graph.py
Labels: bug

#4457 [dy] Run submodule sync
  mage_ai/data_preparation/git/__init__.py
Labels: bug

#4395 Fixing snowflake write_pandas issue
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
Labels: bug

#4460 [xy] Fix writing to Snowflake with mixed int and str types
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/tests/destinations/snowflake/test_snowflake.py
Labels: bug

#4463 0.9.61
  mage_ai/server/constants.py
  setup.py
Labels: feature

#4158 [xh] Weaviate integration with loader and exporter
  docs/integrations/databases/Weaviate.mdx
  docs/mint.json
  mage_ai/data_preparation/templates/constants.py
  mage_ai/data_preparation/templates/data_exporters/weaviate.py
  mage_ai/data_preparation/templates/data_loaders/weaviate.py
  mage_ai/data_preparation/templates/repo/io_config.yaml
  mage_ai/io/base.py
  mage_ai/io/config.py
  mage_ai/io/weaviate.py
Labels: feature

#4198 [xh]Alogia integration
  docs/integrations/databases/Algolia.mdx
  docs/mint.json
  mage_ai/data_preparation/templates/constants.py
  mage_ai/data_preparation/templates/data_exporters/algolia.py
  mage_ai/data_preparation/templates/data_loaders/algolia.py
  mage_ai/data_preparation/templates/repo/io_config.yaml
  mage_ai/io/algolia.py
  mage_ai/io/base.py
  mage_ai/io/config.py
Labels: feature

#4465 [td] Add query decorator for data integration blocks
  mage_ai/data_preparation/decorators.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/data_integration/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/templates/data_integrations/destinations/base.py
  mage_ai/data_preparation/templates/data_integrations/sources/base.py
  mage_ai/io/postgres.py
  mage_ai/io/trino.py
  mage_ai/presenters/blocks/graph.py
  mage_ai/server/utils/output_display.py
Labels: feature

#4449 [jk] Indicate unused and shared block files in file browser and add file search
  mage_ai/api/policies/FilePolicy.py
  mage_ai/api/presenters/FilePresenter.py
  mage_ai/api/resources/FileResource.py
  mage_ai/cache/block.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/file.py
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/FileBrowser/Folder/index.tsx
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/FileBrowser/utils.ts
  mage_ai/frontend/components/Files/index.style.tsx
  mage_ai/frontend/components/Files/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/Files/utils.ts
  mage_ai/frontend/components/PipelineDetail/FileTabs/index.tsx
  mage_ai/frontend/components/Sidekick/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/FileType.ts
  mage_ai/frontend/interfaces/ProjectType.ts
  mage_ai/frontend/oracle/components/FlyoutMenu/index.tsx
  mage_ai/frontend/oracle/elements/Circle.tsx
  mage_ai/frontend/oracle/elements/Text/index.tsx
  mage_ai/frontend/oracle/icons/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/stories/oracle/elements/Icons.stories.tsx
  mage_ai/frontend/utils/string.ts
Labels: feature

#4467 [xy] Scheduler improvements
  mage_ai/orchestration/job_manager.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/orchestration/queue/queue.py
  mage_ai/tests/orchestration/queue/test_process_queue.py
  mage_ai/tests/orchestration/test_job_manager.py
Labels: enhancement

#4468 [td] Fix error logging in pipeline executor
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/executors/pipeline_executor.py
Labels: bug

#4471 [jk] Add doc for reordering blocks
  docs/guides/blocks/reorder-blocks.mdx
  docs/mint.json
Labels: documentation

#4472 [td] When clicking show file versions in arcane library, show right panel
  mage_ai/frontend/components/Applications/ArcaneLibrary/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/TripleLayout/useTripleLayout.ts
Labels: bug

#4479 [td] Catch BigQuery if it fails to fix table names
  mage_ai/frontend/components/charts/BarChartHorizontal.tsx
  mage_ai/io/bigquery.py
Labels: bug

#4485 [jk] Fix pipeline detail prop passed for fetching files
  mage_ai/frontend/components/BlockSettings/index.tsx
  mage_ai/frontend/components/DataIntegrationModal/constants.ts
  mage_ai/frontend/components/FileBrowser/index.tsx
  mage_ai/frontend/components/IntegrationPipeline/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
Labels: bug

#4484 [dy] Always show edit pipeline button
  mage_ai/frontend/components/PipelineDetailPage/utils.ts
Labels: bug

#4483 [xy] Fix app slowness due to project platform check.
  mage_ai/settings/platform/__init__.py
  mage_ai/settings/platform/constants.py
  mage_ai/tests/base_test.py
  mage_ai/tests/settings/test_platform.py
Labels: enhancement

#4486 [td] Revert change to PG IO
  mage_ai/io/postgres.py
Labels: bug

#4487 [xy] Fix io redshift.
  mage_ai/io/redshift.py
Labels: bug

#4490 [xy] Fix multi project flag.
  mage_ai/settings/platform/constants.py
  mage_ai/settings/repo.py
  mage_ai/tests/base_test.py
Labels: bug

#4491 [dy] Add PVC retention policy
  mage_ai/cluster_manager/config.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/constants.ts
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/components/workspaces/Detail/index.tsx
  mage_ai/frontend/components/workspaces/constants.ts
Labels: enhancement

#4492 [xy] Add doc for running Mage as non root users.
  docs/mint.json
  docs/production/custom-docker-image/non-root-user.mdx
Labels: documentation

#4494 [xy] Update doc about maximum batch size.
  docs/data-integrations/destinations/overview.mdx
Labels: documentation

#4291 [jk] Prevent unnecessary initial pipeline run
  docs/api-reference/pipeline-schedules/create-pipeline-schedule.mdx
  docs/api-reference/pipeline-schedules/overview.mdx
  docs/api-reference/pipeline-schedules/read-pipeline-schedules.mdx
  docs/api-reference/pipeline-schedules/update-pipeline-schedule.mdx
  docs/guides/triggering-pipelines.mdx
  docs/orchestration/triggers/configure-triggers-in-code.mdx
  mage_ai/api/policies/PipelineSchedulePolicy.py
  mage_ai/api/presenters/PipelineSchedulePresenter.py
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/api/resources/PipelineTriggerResource.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/components/Triggers/Edit/index.tsx
  mage_ai/frontend/interfaces/PipelineScheduleType.ts
  mage_ai/orchestration/db/migrations/versions/03135dd2b4be_add_last_enabled_at_to_pipeline_schedule.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: bug, enhancement

#4500 [xy] Fix Bigquery clean column name.
  mage_integrations/mage_integrations/destinations/bigquery/__init__.py
Labels: bug

#4501 [xy] Convert datetime type for s3 data integration destination.
  mage_ai/tests/api/endpoints/test_custom_designs.py
  mage_integrations/mage_integrations/destinations/amazon_s3/__init__.py
Labels: bug

#4502 [jk] Prevent add block menu from disappearing
  mage_ai/frontend/components/CommandCenter/index.style.tsx
Labels: bug
