Repository mage-ai/mage-ai, pull requests merged in 2024-04, with the labels that each got.

#4861 [xy] Support cancelling jobs when using multiple replicas.
  mage_ai/orchestration/queue/process_queue.py
Labels: bug

#4864 [xy] Fix updating pipeline content with unicode.
  mage_ai/data_preparation/models/pipeline.py
Labels: bug

#4866 [xy] Fix dangling process when reloading webserver.
  mage_ai/orchestration/queue/process_queue.py
  mage_ai/server/scheduler_manager.py
Labels: bug

#4771 [edw] e2e: ensure example pipeline runs smoothly
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/playwright.config.ts
  mage_ai/frontend/tests/base.ts
  mage_ai/frontend/tests/pipeline_runs.spec.ts
  mage_ai/frontend/tests/utils.ts
Labels: testing

#4875 [xy] Update snowflake destination datetime to use TIMESTAMP type.
  mage_integrations/mage_integrations/destinations/snowflake/utils.py
Labels: enhancement

#4878 [jk] Multi-project platform project settings updates
  docs/_snippets/contribution-process.mdx
  docs/contributing/documentation/overview.mdx
  mage_ai/frontend/components/ServerTimeDropdown/index.tsx
  mage_ai/frontend/components/platform/Settings/index.tsx
  mage_ai/frontend/components/settings/Dashboard/constants.tsx
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/oracle/elements/Inputs/ToggleSwitch.tsx
  mage_ai/frontend/playwright.config.ci.ts
  mage_ai/frontend/playwright.config.ts
  mage_ai/frontend/tests/utils.ts
Labels: bug

#4883 [jk] Block output view option
  .github/pull_request_template.md
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/utils.ts
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/FileHeaderMenuItem.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/storage/constants.ts
Labels: enhancement

#4885 [xy] Refresh block run statuses before fetching crashed block runs.
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: bug

#4888 [jk] Only make specific files request with ArcaneLibrary
  mage_ai/frontend/api/utils/useDelayFetch.ts
  mage_ai/frontend/components/Applications/PortalTerminal/index.tsx
  mage_ai/frontend/components/Files/useFileComponents.tsx
Labels: enhancement

#4769 [dy] Add upsert to MySQL, BQ, and Snowflake
  mage_ai/data_preparation/templates/data_exporters/mysql.py
  mage_ai/io/bigquery.py
  mage_ai/io/mysql.py
  mage_ai/io/snowflake.py
Labels: enhancement

#4889 [dy] Update version control authentication docs
  docs/mint.json
  docs/production/data-sync/version-control.mdx
Labels: documentation

#4887 Caching pipeline_project outside of loop to avoid multple lookups
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/orchestration/db/models/schedules.py
Labels: enhancement

#4890 [jk] Remove pipeline_runs request appearing on different pages
  mage_ai/frontend/pages/index.tsx
Labels: enhancement

#4893 [xy] Add measurement to influxdb source.
  mage_ai/streaming/sources/influxdb.py
Labels: enhancement

#4892 Fix: add template for oracle export
  mage_ai/data_preparation/templates/data_exporters/oracledb.py
Labels: bug

#4894 [jk] Add visibility into project config loading errors
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/utils/models/project/useProject.ts
Labels: enhancement

#4904 [jk] Hide header actions on sign-in page
  mage_ai/frontend/components/ServerTimeDropdown/index.tsx
  mage_ai/frontend/components/shared/Header/index.tsx
  mage_ai/frontend/pages/sign-in.tsx
Labels: enhancement

#4908 [td] Update dynamic blocks docs
  docs/design/blocks/dynamic-blocks.mdx
Labels: documentation

#4902 [xy] Support alerts and limited retries in streaming pipeline.
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
  mage_ai/data_preparation/models/block/extension/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/server/websocket_server.py
Labels: enhancement

#4909 [xy] Update Azure secret doc.
  docs/production/deploying-to-cloud/secrets/Azure.mdx
Labels: documentation

#4911 [xy] Catch pipeline error in scheduler.
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: bug

#4884 [dy] Create metadata.yaml file if it doesn't exist
  mage_ai/data_preparation/repo_manager.py
  mage_ai/server/server.py
Labels: bug

#4913 [xy] Fix dynamic block with great expectation block.
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
Labels: bug

#4914 [jk] Disallow numbers as first character of block names
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/ConfigureBlock/index.tsx
  mage_ai/frontend/utils/string.ts
Labels: enhancement

#4905 [dy] Add setting to update user roles on login
  docs/production/authentication/overview.mdx
  mage_ai/api/resources/SessionResource.py
  mage_ai/authentication/providers/active_directory.py
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
  mage_ai/server/server.py
  mage_ai/settings/keys/auth.py
  mage_ai/tests/api/operations/test_sessions.py
Labels: enhancement

#4916 [dy] Update version control documentation
  docs/production/data-sync/version-control.mdx
Labels: documentation

#4915 [dy] Fix duckdb sql
  mage_ai/data_preparation/models/block/sql/__init__.py
Labels: bug

#4929 [jk] Prevent renamed triggers in code from being duplicated
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/data_preparation/models/triggers/__init__.py
Labels: bug

#4934 [jk] Triggers table UI fixes
  mage_ai/frontend/components/Triggers/Table.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/triggers/index.tsx
  mage_ai/frontend/pages/triggers/index.tsx
Labels: enhancement

#4937 [td] Lots of fixes and enhancements
  docs/developer-ux/applications/arcane-library.mdx
  docs/developer-ux/applications/overview.mdx
  docs/developer-ux/command-center/spellcaster.mdx
  docs/developer-ux/file-browser.mdx
  docs/developer-ux/overview.mdx
  mage_ai/command_center/applications/utils.py
  mage_ai/command_center/presenters/text.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/global_data_product/__init__.py
  mage_ai/data_preparation/models/block/remote/__init__.py
  mage_ai/data_preparation/models/block/remote/models.py
  mage_ai/data_preparation/models/block/utils.py
  mage_ai/data_preparation/models/global_data_product/__init__.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/frontend/components/Applications/ArcaneLibrary/configuration.json
  mage_ai/frontend/components/ChartBlock/index.tsx
  mage_ai/frontend/components/CodeBlock/CommandButtons/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/orchestration/triggers/api.py
  mage_ai/orchestration/triggers/global_data_product.py
  mage_ai/orchestration/triggers/utils.py
  mage_ai/server/api/runs.py
  mage_ai/server/server.py
  mage_ai/server/utils/output_display.py
  mage_ai/shared/parsers.py
  mage_ai/tests/data_preparation/models/block/test_global_data_product.py
  mage_ai/tests/orchestration/triggers/test_global_data_product.py
Labels: bug, enhancement

#4944 [xy] Skip checking memory in Windows.
  mage_ai/orchestration/utils/resources.py
Labels: bug

#4947 [xy] Support interpolating trigger name in k8s job name.
  mage_ai/data_preparation/executors/k8s_block_executor.py
  mage_ai/data_preparation/executors/k8s_pipeline_executor.py
Labels: enhancement

#4948 [xy] Check type key in anyOf array objects.
  mage_integrations/mage_integrations/destinations/base.py
Labels: bug

#4950 [xy] Only send failure notification when pipeline run status is failed.
  mage_ai/orchestration/pipeline_scheduler_original.py
Labels: enhancement

#4949 [dy] Avoid creating duplicate admin user
  mage_ai/orchestration/db/models/oauth.py
  mage_ai/server/server.py
  mage_ai/tests/server/test_server.py
Labels: bug

#4957 [xy] Fix downloading xlsx file.
  mage_ai/server/api/downloads.py
Labels: bug

#4961 [jk] Bugfix - Dependency tree layout
  mage_ai/frontend/components/DependencyGraph/BlockNode/index.tsx
  mage_ai/frontend/components/DependencyGraph/BlockNode/utils.ts
  mage_ai/frontend/components/DependencyGraph/index.tsx
  mage_ai/frontend/components/DependencyGraph/utils.ts
Labels: bug

#4951 [dy] Add workspace update features
  mage_ai/api/policies/WorkspacePolicy.py
  mage_ai/api/resources/WorkspaceResource.py
  mage_ai/cluster_manager/kubernetes/workload_manager.py
  mage_ai/cluster_manager/workspace/base.py
  mage_ai/cluster_manager/workspace/kubernetes.py
  mage_ai/frontend/components/workspaces/ConfigureWorkspace/index.tsx
  mage_ai/frontend/components/workspaces/Detail/index.tsx
  mage_ai/frontend/pages/manage/index.tsx
Labels: feature

#4942 [jk] Backfills table improvements
  mage_ai/api/policies/BackfillPolicy.py
  mage_ai/api/presenters/BackfillPresenter.py
  mage_ai/frontend/components/Backfills/Detail/index.tsx
  mage_ai/frontend/components/Backfills/Table/index.tsx
  mage_ai/frontend/components/PipelineDetail/Runs/Table.tsx
  mage_ai/frontend/components/Triggers/Detail/index.tsx
  mage_ai/frontend/interfaces/BackfillType.ts
  mage_ai/frontend/pages/pipelines/[pipeline]/backfills/index.tsx
  mage_ai/orchestration/db/models/schedules.py
Labels: enhancement

#4962 [xy] Improve the performance of Postgres source metadata query.
  mage_integrations/mage_integrations/sources/postgresql/__init__.py
Labels: enhancement

#4963 [xy] Fix logging tags for streaming pipeline run.
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
Labels: bug

#4964 [xy] Catch notification send exceptions.
  mage_ai/orchestration/notification/sender.py
Labels: bug

#4959 [dy] Remove git dependency
  .github/workflows/build_and_test.yml
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/OauthResource.py
  mage_ai/api/resources/PullRequestResource.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/api.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/frontend/playwright-windows.config.ci.ts
  mage_ai/frontend/tests/basic/pipelines.spec.ts
  mage_ai/tests/authentication/oauth/test_utils.py
  mage_ai/version_control/branch/utils.py
  mage_ai/version_control/models.py
Labels: bug

#4968 [xy] Use executor type from pipeline level when block level executor is not set
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/pipeline.py
Labels: enhancement

#4975 [jk] Cancel unsaved modified file dialogue
  mage_ai/frontend/components/Files/useFileComponents.tsx
  mage_ai/frontend/components/PipelineDetail/FileTabs/Tab.tsx
Labels: bug

#4974 [xy] Always set logger in different blocks separately.
  mage_ai/data_preparation/models/block/__init__.py
Labels: bug

#4980 [dy] Fix more git issues
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
Labels: bug

#4985 [xy] Fix k8s affinity parsing.
  mage_ai/services/k8s/config.py
  mage_ai/services/k8s/utils.py
  mage_ai/tests/services/k8s/test_job_manager.py
Labels: bug

#4986 [jk] Docs for project settings features
  docs/development/project/features.mdx
  docs/mint.json
  mage_ai/frontend/components/settings/workspace/Preferences.tsx
  mage_ai/frontend/oracle/elements/Link/index.tsx
  mage_ai/frontend/oracle/elements/Text/index.tsx
  mage_ai/frontend/utils/models/project/useProject.ts
Labels: documentation

#4988 [jk] Allow disabling pipeline autosave
  mage_ai/frontend/components/MultiColumnController/index.style.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/FileHeaderMenuItem.tsx
  mage_ai/frontend/components/PipelineDetail/FileHeaderMenu/index.tsx
  mage_ai/frontend/components/PipelineDetail/StatusFooter/index.tsx
  mage_ai/frontend/components/PipelineDetail/index.tsx
  mage_ai/frontend/pages/pipelines/[pipeline]/edit.tsx
  mage_ai/frontend/storage/constants.ts
Labels: enhancement

#4990 [xy] Delay initializing the queue.
  mage_ai/orchestration/job_manager.py
Labels: bug

#4993 [xy] Support query pipelines with repo_path.
  mage_ai/api/policies/PipelinePolicy.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/tests/api/resources/test_pipeline_resource.py
Labels: enhancement

#4995 [xy] Fix None job manager.
  mage_ai/server/scheduler_manager.py
Labels: bug

#5005 [xy] Fix None Bigquery database error.
  mage_ai/io/bigquery.py
Labels: bug

#5008 [xy] Fix extracting table name from INSERT statement in SQL block.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
  mage_ai/tests/data_preparation/models/block/sql/utils/test_shared.py
Labels: bug

#5009 [xy] Not show locals in CLI exception.
  mage_ai/cli/main.py
Labels: security

#5012 [xy] Catch yaml interpolation error.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
Labels: bug
