Repository mage-ai/mage-ai, pull requests merged in 2024-05, with the labels that each got.

#5017 [xy] Not run insert query for empty dataframe.
  mage_ai/io/redshift.py
Labels: bug

#5018 [xy] Support configuring logs_dir_path in environment variable.
  docs/development/variables/environment-variables.mdx
  mage_ai/data_preparation/logging/logger_manager.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/settings/server.py
Labels: enhancement

#5014 [dy] Add prune option for fetch
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/data_preparation/git/api.py
  mage_ai/frontend/components/VersionControl/Remote/index.tsx
  mage_ai/frontend/components/VersionControl/constants.ts
  mage_ai/frontend/components/VersionControl/index.tsx
Labels: enhancement

#4896 [xh]Create streaming oracle destination
  docs/mint.json
  docs/streaming/destinations/oracledb.mdx
  mage_ai/data_preparation/templates/data_exporters/streaming/oracledb.yaml
  mage_ai/frontend/components/PipelineDetail/AddNewBlocks/utils.tsx
  mage_ai/streaming/sinks/oracledb.py
  mage_ai/streaming/sinks/sink_factory.py
  mage_ai/tests/streaming/sinks/test_oracledb.py
Labels: feature

#5025 [dy] Fix git and seed issues
  mage_ai/api/presenters/SyncPresenter.py
  mage_ai/api/resources/SeedResource.py
  mage_ai/api/resources/SyncResource.py
  mage_ai/authentication/permissions/seed.py
  mage_ai/data_preparation/git/utils.py
  mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
  mage_ai/frontend/interfaces/SyncType.ts
  mage_ai/frontend/pages/settings/workspace/roles/index.tsx
  mage_ai/frontend/pages/settings/workspace/sync-data.tsx
  mage_ai/orchestration/db/__init__.py
  mage_ai/tests/base_test.py
Labels: bug

#5027 [xy] Include server and scheduler process id in status response.
  mage_ai/api/presenters/StatusPresenter.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/server/scheduler_manager.py
Labels: enhancement

#5030 [xy] Add pipeline_run_id to kwargs.
  docs/orchestration/triggers/schedule-pipelines.mdx
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/tests/orchestration/test_pipeline_scheduler.py
Labels: enhancement

#5038 [xy] Fix custom template issue on server start.
  mage_ai/data_preparation/models/custom_templates/utils.py
  mage_ai/tests/data_preparation/models/custom_templates/test_utils.py
Labels: bug

#5041 [jk] Fix syntax for iframe in Roadmap doc
  docs/about/roadmap.mdx
Labels: documentation

#5046 [xy] Comment out flaky unit tests
  mage_ai/tests/api/operations/base/test_base_with_user_authentication.py
  mage_ai/tests/api/operations/base/test_base_with_user_permissions.py
Labels: bug

#5042 [jk] Allow files to be selected for pipeline zip import
  mage_ai/frontend/components/FileUploader/index.tsx
  mage_ai/frontend/components/PipelineDetail/UploadPipeline/index.tsx
  mage_ai/frontend/oracle/elements/Inputs/MultiFileInput.tsx
Labels: bug

#5045 [dy] Update git email field
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/data_preparation/git/utils.py
Labels: bug

#5050 [dy] Fix circular dependency
  mage_ai/settings/platform/__init__.py
  mage_ai/shared/parsers.py
Labels: bug

#5051 [xy] Allow configuring authentication mode in mssql config.
  mage_ai/tests/api/operations/base/test_base.py
  mage_integrations/mage_integrations/connections/mssql/__init__.py
  mage_integrations/mage_integrations/destinations/mssql/README.md
  mage_integrations/mage_integrations/destinations/mssql/__init__.py
  mage_integrations/mage_integrations/destinations/mssql/templates/config.json
  mage_integrations/mage_integrations/sources/mssql/README.md
  mage_integrations/mage_integrations/sources/mssql/__init__.py
  mage_integrations/mage_integrations/sources/mssql/templates/config.json
  mage_integrations/mage_integrations/tests/destinations/mssql/test_mssql.py
Labels: enhancement

#5044 Add configuration parameters to V1JobSpec in k8s executor
  docs/production/configuring-production-settings/compute-resource.mdx
  mage_ai/services/k8s/config.py
  mage_ai/services/k8s/job_manager.py
  mage_ai/tests/services/k8s/test_job_manager.py
Labels: enhancement

#4953 Reload libraries when running blocks from edit pipeline
  mage_ai/autocomplete/utils.py
  mage_ai/server/websocket_server.py
  mage_ai/utils/code.py
Labels: enhancement

#5057 [xy] Support configuring concurrency config via env vars.
  docs/design/data-pipeline-management.mdx
  mage_ai/orchestration/concurrency.py
  mage_ai/settings/server.py
Labels: enhancement

#5053 Add OIDC_ROLES_MAPPING support
  mage_ai/authentication/providers/oidc.py
  mage_ai/settings/keys/auth.py
  mage_ai/settings/server.py
  mage_ai/tests/authentication/providers/test_oidc.py
Labels: enhancement

#5068 [xy] Update some docs
  docs/development/troubleshooting.mdx
  docs/integrations/databases/PostgreSQL.mdx
  docs/production/configuring-production-settings/compute-resource.mdx
Labels: documentation

#5072 [jk] Improve visibility of variable/secret names
  mage_ai/frontend/components/Sidekick/GlobalVariables/Secrets.tsx
  mage_ai/frontend/components/Sidekick/GlobalVariables/VariableRow.tsx
Labels: enhancement

#5088 [td] Fix IDE outputs
  mage_ai/data_preparation/models/block/outputs.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/BlockLayout/BlockLayoutItem/index.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/OutputRenderer.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/TableOutput.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/TextOutput.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/CodeBlock/index.tsx
  mage_ai/frontend/components/DataTable/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/KernelOutputType.ts
  mage_ai/frontend/package.json
  mage_ai/frontend/yarn.lock
  mage_ai/server/kernel_output_parser.py
  mage_ai/server/utils/custom_output.py
  mage_ai/server/utils/output_display.py
  mage_ai/shared/parsers.py
  mage_ai/shared/yaml.py
Labels: bug, enhancement

#5089 [td] Fix git issue
  mage_ai/api/resources/VersionControlProjectResource.py
Labels: bug

#5090 Td fix git2
  mage_ai/api/resources/VersionControlProjectResource.py
Labels: bug

#5091 [td] Upgrade deltalake because of Docker image build error
  requirements.txt
Labels: bug

#5094 [xy] Fix websocket authentication.
  mage_ai/server/websocket_server.py
Labels: bug

#5079 [xy] Cache project platform settings data in API calls.
  mage_ai/api/operations/base.py
  mage_ai/api/parsers/PipelineScheduleParser.py
  mage_ai/api/presenters/BlockPresenter.py
  mage_ai/api/presenters/PipelinePresenter.py
  mage_ai/api/resources/GitBranchResource.py
  mage_ai/api/resources/PipelineResource.py
  mage_ai/api/resources/PipelineRunResource.py
  mage_ai/api/resources/PipelineTriggerResource.py
  mage_ai/api/resources/ProjectResource.py
  mage_ai/api/resources/StatusResource.py
  mage_ai/api/resources/VariableResource.py
  mage_ai/cache/base.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/git/__init__.py
  mage_ai/data_preparation/models/block/data_integration/mixins.py
  mage_ai/data_preparation/models/block/spark/mixins.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/project/__init__.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/orchestration/db/models/schedules_project_platform.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/orchestration/pipeline_scheduler_project_platform.py
  mage_ai/presenters/pages/models/page_components/pipeline_schedules.py
  mage_ai/server/server.py
  mage_ai/settings/platform/__init__.py
  mage_ai/settings/platform/utils.py
  mage_ai/settings/repo.py
  mage_ai/shared/custom_logger.py
  mage_ai/tests/api/endpoints/test_custom_designs.py
  mage_ai/tests/api/endpoints/test_pipeline_runs.py
  mage_ai/tests/api/resources/test_pipeline_resource.py
  mage_ai/tests/data_preparation/git/test_git.py
  mage_ai/tests/data_preparation/models/test_project.py
  mage_ai/tests/orchestration/db/models/test_schedules.py
  mage_ai/usage_statistics/logger.py
Labels: enhancement

#5095 [td] Fix interpolating dictionaries when adding custom code to ide execution
  mage_ai/server/utils/execute_custom_code.py
  mage_ai/server/utils/output_display.py
  mage_ai/server/websocket_server.py
Labels: bug

#5098 [xy] Fix switching active kernel
  mage_ai/api/resources/ClusterResource.py
  mage_ai/cluster_manager/aws/emr_cluster_manager.py
  mage_ai/server/utils/output_display.py
Labels: bug

#5099 [xy] Fix retry in streaming pipeline.
  mage_ai/data_preparation/executors/streaming_pipeline_executor.py
Labels: bug

#5105 [td] Track resource usage and run block execution function in a context
  mage_ai/data/models/base.py
  mage_ai/data/tabular/mocks.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/outputs.py
  mage_ai/data_preparation/models/block/settings/variables/mixins.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/models/variables/constants.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/ApplicationManager/useApplicationManager.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/TableOutput.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/system/memory/utils.py
  mage_ai/system/memory/wrappers.py
  mage_ai/system/models.py
  mage_ai/system/storage/__init__.py
  mage_ai/system/storage/utils.py
  mage_ai/tests/data_preparation/models/test_block.py
  mage_ai/≡ .DS_Store
  scripts/frontend/fix.py
  scripts/server/write_tests.py
Labels: enhancement

#5108 [xy] Fix performance issue of fetching variables.
  docker-compose.yml
  mage_ai/data/models/base.py
  mage_ai/data/models/manager.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/variable_manager.py
Labels: bug

#5115 [jk] Fix max concurrent runs value for backfill
  mage_ai/frontend/components/Backfills/Edit/index.tsx
Labels: bug

#5122 [xy] Fic circular dependency.
  mage_ai/data/models/manager.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/variable_manager.py
Labels: bug

#5125 [xy] Speed up pipeline update endpoint.
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/extension/utils.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/repo_manager.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/settings/repo.py
  mage_ai/shared/yaml.py
Labels: enhancement

#5121 [td] Dynamic block stream mode
  docs/_snippets/debugging-backend.mdx
  mage_ai/data/constants.py
  mage_ai/data/models/manager.py
  mage_ai/data/models/writer.py
  mage_ai/data/tabular/models.py
  mage_ai/data/tabular/writer.py
  mage_ai/data_preparation/executors/block_executor.py
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/child.py
  mage_ai/data_preparation/models/block/dynamic/counter.py
  mage_ai/data_preparation/models/block/dynamic/data.py
  mage_ai/data_preparation/models/block/dynamic/factory.py
  mage_ai/data_preparation/models/block/dynamic/models.py
  mage_ai/data_preparation/models/block/dynamic/shared.py
  mage_ai/data_preparation/models/block/dynamic/utils.py
  mage_ai/data_preparation/models/block/dynamic/variables.py
  mage_ai/data_preparation/models/block/dynamic/wrappers.py
  mage_ai/data_preparation/models/block/outputs.py
  mage_ai/data_preparation/models/block/settings/dynamic/constants.py
  mage_ai/data_preparation/models/block/settings/dynamic/mixins.py
  mage_ai/data_preparation/models/block/settings/dynamic/models.py
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/utils.py
  mage_ai/data_preparation/models/variable.py
  mage_ai/data_preparation/models/variables/summarizer.py
  mage_ai/data_preparation/models/variables/utils.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/frontend/components/CodeBlock/CodeOutput/OutputRenderer.tsx
  mage_ai/frontend/components/CodeBlock/CodeOutput/ProgressOutput.tsx
  mage_ai/frontend/components/DataTable/index.tsx
  mage_ai/frontend/components/PipelineDetail/utils.ts
  mage_ai/frontend/components/TripleLayout/index.tsx
  mage_ai/frontend/interfaces/BlockType.ts
  mage_ai/frontend/interfaces/KernelOutputType.ts
  mage_ai/frontend/package.json
  mage_ai/frontend/pages/pipelines/[pipeline]/runs/[run]/index.tsx
  mage_ai/frontend/yarn.lock
  mage_ai/io/base.py
  mage_ai/orchestration/db/models/dynamic/controller.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/server/kernel_output_parser.py
  mage_ai/server/utils/execute_custom_code.py
  mage_ai/shared/models.py
  mage_ai/shared/strings.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_combos.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_counter.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_factory.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_variables.py
  mage_ai/tests/orchestration/db/models/test_schedules_dynamic_blocks.py
Labels: enhancement

#5132 [td] Don’t raise error if can’t load
  mage_ai/shared/outputs.py
Labels: bug

#5134 [xy] Fix custom template creation.
  mage_ai/api/resources/CustomTemplateResource.py
Labels: bug

#5135 [xy] Fix variables API and BaseEnum
  mage_ai/data_preparation/storage/gcs_storage.py
  mage_ai/data_preparation/storage/local_storage.py
  mage_ai/data_preparation/storage/s3_storage.py
  mage_ai/data_preparation/variable_manager.py
  mage_ai/shared/models.py
Labels: bug

#5136 [xy] Disable autoreload in non-dev environments.
  mage_ai/server/server.py
  mage_ai/settings/server.py
Labels: enhancement

#5137 [xy] Reduce CPU usage in scheduler.
  mage_ai/data_preparation/models/pipeline.py
  mage_ai/data_preparation/models/triggers/__init__.py
  mage_ai/orchestration/db/models/schedules.py
  mage_ai/orchestration/pipeline_scheduler_original.py
  mage_ai/shared/config.py
Labels: enhancement

#5142 [td] Fix after on pipeline dashboard
  mage_ai/frontend/components/PipelineDetailPage/index.tsx
  mage_ai/frontend/components/TripleLayout/index.tsx
Labels: bug

#5143 [td] Fix after panel showing up everywhere
  mage_ai/frontend/components/TripleLayout/index.tsx
Labels: bug

#5145 [xy] Update pypi github action
  .github/workflows/publish_to_pypi.yml
Labels: enhancement

#5146 [xy] Fix delete workspace.
  mage_ai/api/resources/WorkspaceResource.py
Labels: bug
