Repository mage-ai/mage-ai, pull requests merged in 2024-10, with the labels that each got.

#5457 [jk] Display ID in block runs table
  mage_ai/frontend/components/PipelineDetail/BlockRuns/Table.tsx
Labels: enhancement

#5464 [td] Add block overview
  docs/design/blocks.mdx
Labels: documentation

#5465 [td] Add case study to streaming pipelines
  docs/streaming/overview.mdx
Labels: documentation

#5466 [td] Fix blocks doc
  docs/design/blocks.mdx
Labels: documentation

#5502 [Oracle DB] Modify inefficient code that converts dataframe to list of tuples
  mage_ai/io/oracledb.py
Labels: enhancement

#5508 Add support to multiples webhook endpoints for Microsoft Teams notification service
  mage_ai/services/teams/config.py
  mage_ai/services/teams/teams.py
  mage_ai/tests/orchestration/notification/test_config.py
Labels: enhancement

#5493 [Bug] Updated SalesForce source to handle multiple date formats
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/__init__.py
  mage_integrations/mage_integrations/sources/salesforce/client/tap_salesforce/salesforce/__init__.py
Labels: bug

#5526 [td] Add GA to docs
  docs/mint.json
Labels: documentation
