Repository mage-ai/mage-ai, pull requests merged in 2025-01, with the labels that each got.

#5631 Mage Pro getting started documentation
  docs/getting-started/setup.mdx
Labels: documentation

#5635 [cf] Mage Pro environment variables and getting started
  docs/development/variables/environment-variables.mdx
  docs/getting-started/setup.mdx
Labels: documentation

#5606 [hw] Resolve the input path issue with R transformer blocks
  mage_ai/data_preparation/models/block/__init__.py
  mage_ai/data_preparation/models/block/dynamic/constants.py
  mage_ai/data_preparation/models/block/dynamic/counter.py
  mage_ai/data_preparation/models/block/r/__init__.py
  mage_ai/data_preparation/models/constants.py
  mage_ai/tests/data_preparation/models/block/dynamic/test_counter.py
Labels: bug

#5653 [xh]Fix disable query preprocessing
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/mssql.py
Labels: bug

#5655 [xy] Support pool_size and max_overflow in mssql connect kwargs.
  mage_ai/io/mssql.py
Labels: enhancement

#5664 [xy] Resolve dbt library conflicts.
  Dockerfile
  dev.Dockerfile
  requirements.txt
  setup.py
Labels: bug

#5665 [xy] Add safe_db_query_async decorator.
  mage_ai/api/resources/SessionResource.py
  mage_ai/orchestration/db/__init__.py
Labels: bug

#5667 [xy] Pass execution_partition to interpolate content method.
  mage_ai/data_preparation/models/block/sql/__init__.py
  mage_ai/data_preparation/models/block/sql/utils/shared.py
Labels: bug
