Repository mage-ai/mage-ai, pull requests merged in 2025-02, with the labels that each got.

#5676 [xy] Auto cast timestamp columns for bigquery exporter.
  mage_ai/io/bigquery.py
Labels: enhancement

#5677 [xy] Fetch git secret with repo query.
  mage_ai/api/resources/SyncResource.py
  mage_ai/orchestration/db/models/secrets.py
Labels: bug

#5683 [cf] workspaces documentation
  docs/guides/developer-ux/workspaces.mdx
  docs/mint.json
Labels: documentation

#5679 [xh] Add allow_local_infile to MySQL config to enable support for "LOAD DATA LOCAL INFILE"
  docs/design/data-loading.mdx
  mage_ai/io/config.py
  mage_ai/io/mysql.py
Labels: feature

#5686 [xy] Not save token to triggers.yaml if HIDE_API_TRIGGER_TOKEN is true.
  mage_ai/api/resources/PipelineScheduleResource.py
  mage_ai/api/resources/PipelineTriggerResource.py
Labels: enhancement

#5687 [xy] Fix MySQL error.
  mage_ai/io/mysql.py
Labels: bug

#5691 [xy] Fix bigquery write with replace policy.
  mage_ai/io/bigquery.py
Labels: bug

#5693 [cf] workspaces mage pro banner
  docs/guides/developer-ux/workspaces.mdx
Labels: documentation

#5694 [cf] vscode video commit
  docs/guides/developer-ux/visual-studio-code.mdx
  docs/mint.json
Labels: documentation

#5705 [xy] Only allow api trigger endpoint for API trigger.
  mage_ai/server/api/triggers.py
Labels: bug

#5707 [xy] Fix API trigger request authentication.
  mage_ai/server/api/triggers.py
Labels: bug

#5704 [xy] Add teradata source and destination to data integration pipeline
  mage_ai/data_integrations/destinations/constants.py
  mage_ai/data_integrations/sources/constants.py
  mage_integrations/mage_integrations/connections/sql/base.py
  mage_integrations/mage_integrations/connections/teradata/__init__.py
  mage_integrations/mage_integrations/destinations/snowflake/__init__.py
  mage_integrations/mage_integrations/destinations/sql/base.py
  mage_integrations/mage_integrations/destinations/teradata/README.md
  mage_integrations/mage_integrations/destinations/teradata/__init__.py
  mage_integrations/mage_integrations/destinations/teradata/templates/config.json
  mage_integrations/mage_integrations/destinations/teradata/utils.py
  mage_integrations/mage_integrations/sources/sql/base.py
  mage_integrations/mage_integrations/sources/teradata/README.md
  mage_integrations/mage_integrations/sources/teradata/__init__.py
  mage_integrations/mage_integrations/sources/teradata/templates/config.json
  mage_integrations/requirements.txt
Labels: feature

#5710 [xy] Add docs for databricks integration.
  docs/guides/developer-ux/workspaces.mdx
  docs/integrations/compute/databricks.mdx
  docs/integrations/databases/Databricks.mdx
  docs/mint.json
Labels: documentation
